.gitignore, Cargo.toml, README.md, appveyor.yml
Updated the appveyor config to build in x86 an x64 using mingw. Pointing the sodiumoxide dependency to use the fork.
=> Appveyor integration

.travis.yml, Cargo.toml, README.md
Must enable coveralls.io for routing repository for coverage results to be published in coveralls.io. README updated for SQLite.
=> Coverage integration

src/sentinel.rs
found two more corrections.  Importantly, one was caused by type erasure of cryptographic types over all Vec<u8>; the test gave the Public encryption keys, not the public signature keys
=> Sentinel improve

appveyor.yml
```
Redirection to 'nul' failed: FileStream will not open Win32 devices such as disk partitions and tape drives. Avoid use of "\\.\" in the path.
At line:1 char:156
+ ... -20141001.7z"; 7z x -oC:\ mingw-w64-dgn-x86_64-20141001.7z > nul; Start-FileDown ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : RedirectionFailed
```
=> Remove nul redirect in Appveyor

src/lib.rs
The logic can be used from other libraries. Since there will be a version update, I thought of pushing this along with the update.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/128)
=> Exposing closer_to_target as public

src/routing_node.rs, src/routing_table.rs
Continues our_authority in routing_node
Sorry; I agree it wasn't a priority, but I couldn't leave the code in that state
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/129)
=> clean up of functions; better handling of Option<NameType>

src/messages/find_group_response.rs, src/messages/get_group_key_response.rs
includes previous pull request and extends the same logic of merging target_id also for GetGroupKeyResponse; after handling FindGroupResponse in previous PR
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/122)
=> Update merge logic of FindGroupResponse GetGroupKeyResponse

src/routing_table.rs
this test verifies that the returned close group is sorted.
removed uneffective sort from existing our_close_group test
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/135)
=> independent additional test on routing_table::our_close_group()

src/name_type.rs, src/routing_node.rs, src/routing_table.rs, src/sentinel.rs, src/types.rs
Removing stray RoutingTrait. It is now replaced by Sendable.
Also it was used for Pmid keys, which is not desirable.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/140)
=> Removing stray RoutingTrait

src/messages/find_group_response.rs, src/messages/get_group_key_response.rs, src/routing_node.rs, src/sentinel.rs, src/test_utils/messages_util.rs
Because it was redundant (message.header.from_group is always the same) and was complicating the merge logic.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/141)
=> Removes target_id from FindGroupResponse and GetGroupKeyResponse

src/accumulator.rs, src/messages/find_group_response.rs, src/messages/get_group_key_response.rs, src/sentinel.rs, src/types.rs
Fixes merge logic for FindGroupResponse and GetGroupKeyResponse messages. Unfortunately these changes break tests in the corresponding message .rs files and sentinel.rs. I believe the fix needs to be done in the tests.
The main changes that cause the test failures are these two lines ([L42](https://github.com/inetic/routing/blob/master/src/messages/find_group_response.rs#L42), [L43](https://github.com/inetic/routing/blob/master/src/messages/find_group_response.rs#L43)) for FindGroupResponse and these two lines ([L43](https://github.com/inetic/routing/blob/master/src/messages/get_group_key_response.rs#L43), [L44](https://github.com/inetic/routing/blob/master/src/messages/get_group_key_response.rs#L44)) for GetGroupKeyResponse. Commenting out these lines makes the tests pass again as …
=> Signature checks and more correct `merge` (exploits faults in tests!)

src/message_header.rs
Create a single place to mutate headers on Action::SendOn or Action::Reply; this gets called by a managed node after the interface has returned an Action to routing
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/164)
=> Message header sendon reply

examples/routing.rs, src/generic_sendable_type.rs, src/routing_node.rs, src/sendable.rs
Sendable trait refresh and merge fn updated. In example/routing.rs the trait had mismatch, thus resolved to get the test running
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/170)
=> Sendable trait changes - refresh & merge

src/error.rs, src/types.rs
Reverts maidsafe/routing#284
The decoding and encoding of the error would lose the payload of the error message
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/286)
=> Revert "add ResponseError::FailedToStoreData"

src/client_interface.rs, src/error.rs, src/node_interface.rs
#[deny(missing_docs)] on MethodCall results in error. But it is fine on other traits
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/294)
=> documenting MethodCall, RoutingError, Interface traits

src/routing_membrane.rs, src/routing_node_new.rs
Patch: on connect_request, directly add to relay_map - bypass the "remember public_id"
The assumption was that first a connect_request was received on our listening port, and when both sides 'connection_manager.connect' a 'CRUST::NewConnection' would be triggered.
Turns out that CRUST gives a new CRUST::NewConnection for every single sided connect, and the NewMessage comes after that, for a given endpoint.  This patch should do, but post-sprint this logic needs to be reworked.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/319)
=> Directly add to relay_map on connect_request

src/routing_membrane.rs, src/routing_node_new.rs
debug remnant;
Added FIXME: probably we can drop the zero_node special handler for PutPublicId
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/323)
=> Fix was trivial, first node started membrane explicitly unrelocated_id

examples/simple_key_value_store.rs, src/lib.rs, src/relay.rs, src/routing_client.rs, src/routing_membrane.rs, src/routing_node.rs, src/who_are_you.rs
Implement filter for Connect Requests as a filter on ConnectRequests to avoid exponential load; significantly improves network boot-up time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/344)
=> Issue 343: filter / fake Sentinel for FindGroupResponse/ConnectRequest

examples/simple_key_value_store.rs, src/lib.rs, src/relay.rs, src/routing_client.rs, src/routing_membrane.rs, src/routing_node.rs, src/who_are_you.rs
Turned out it responses were being given from cache; took a long time to remember that after long hours :)
Inserted interception points to relay back to relay node / client;  It is clear we need a more elegant approach; to rush things I have replicated the same code on several locations; at least the should be put in one function-  issue raised to clean this up
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/350)
=> Debug PUT/GET flow - Issue 347

src/authority.rs
Needed correction to updated Authority definitions as it the introduction of OurCloseGroup had broken NaeManager, and as such broke the PutPublicId; 
Corrected by additional condition on Nae is from_group != destination  (because the OurCloseGroup is purely for group-to-group) (not from a single node)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/364)
=> Needed correction to updated Authority 

src/message_header.rs, src/routing_membrane.rs, src/types.rs
Needs correction to message_filter now such that filter does not falslely block a sent-on message
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/396)
=> preserve message_id on SendOn

src/routing_membrane.rs
The review of unauthorised put was moved out of the sprint and slipped under the radar.  For now just enable it as a normal put
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/406)
=> enable handler for unauthorised put

src/routing_membrane.rs
caused by reduced group size to 23
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/407)
=> quickly reduce intermittent failure chance; 

src/routing_membrane.rs
send back put response to Client;
on FailedToStoreData from ManagedNode with different data, apply patch
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/424)
=> Patch for Vault Handle Put behaviour;

CHANGELOG.md, src/routing_membrane.rs, src/routing_node.rs, src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/426)
=> Act on churn

Cargo.toml, src/error.rs, src/routing_node.rs, src/routing_table.rs
This will fail until the third party crate `term` is updated.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/432)
=> Fixes breakages when using latest nightly version of Rust.

src/routing_client.rs
As it is the correct id of the relay node. (I would prefer the approach discussed where there would be just `header` instead of `destination` and `source`, but did it this way to avoid confusion for now)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/449)
=> RelayedForClient from_address set back to bootstrap node

src/messages.rs, src/public_id.rs, src/routing_client.rs, src/utils.rs
And few RelayedForClient takes a PublicKey
not name of the client (this would have been caught
by the compiler later though).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/456)
=> PUT messages should go to ClientManager

src/node_interface.rs
This reverts commit f56fda28106e3c6f19a702db2c8da048b4d2ff31.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/469)
=> Revert "correction to NodeInterface"

examples/simple_key_value_store.rs, src/client_interface.rs, src/routing_client.rs
So that client can start sending/receiving messages right after
bootstrap fn returns. Also renames 'run_one' fn to 'poll_one' to
be use consistent terminology with boost asio.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/534)
=> Block bootstrap fn until IAm msg arrives

src/messages.rs, src/routing_node.rs, src/types.rs
The Signature in the SignedMessage is already the hash of all fields, including claimant and RoutingMessage, making it a unique identifier for detecting duplicate versions of the same message without additional overhead
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/573)
=> use SignedMessage::Signature as FilterType for filtering messages

examples/simple_key_value_store.rs, src/data.rs, src/event.rs, src/lib.rs, src/message_accumulator.rs, src/messages.rs, src/routing.rs, src/routing_core.rs, src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/576)
=> Accumulator

appveyor.yml
Fix the `libsodium` dependency by setting the env var `SODIUM_LIB_DIR` used by the custom build script for sodiumoxide.
While this PR fixes the dependency issue it also highlights the current compile failure in sodiumoxide module for x86 windows.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/595)
=> Fix appveyor sodium dependency

src/hello.rs, src/routing_core.rs, src/routing_node.rs
This is a second patch to node::handle_hello to ensure that mutliple connections between two nodes only have a single resulting connection, correctly labelled on both sides.
The first patch ensured that a single connection was left standing after duplicate connections were detecting, by introducing rules to decide which node should take action (named alpha); however the non-alpha node would already update the core, potentially leaving it to refuse the the correct identification from the core, as decided upon by the alpha.
This is resolved here by having the alpha send a confirmation hello on the connection that he has added to his core, initiating the non-alpha to also add that connection as the connection to use to its core.
There are possibly security loop holes / opportunities for …
=> Synchronise core

examples/simple_key_value_store.rs, src/event.rs, src/id.rs, src/routing.rs, src/routing_core.rs, src/routing_node.rs, src/structured_data.rs
continuing work on finishing Client and Event implementation
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/620)
=> Event connected implementation

examples/simple_key_value_store.rs, src/authority.rs, src/messages.rs, src/routing.rs, src/routing_client.rs, src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/640)
=> Adds nonce to ExternalRequest. Fixes #629.

examples/simple_key_value_store.rs, src/messages.rs, src/routing_node.rs
To accommodate both efficiency and also reduction in CPU usage. Can possibly be improved by only having a nanosleep when loop has not actually matched any receive channel. For now this appears to be successful in ensuring nodes are stable. There was an issue waiting on crust actions whilst routing was attempting to handle an event.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/660)
=> Refactor main event loop in routing 

examples/key_value_store.rs, src/event.rs, src/filter.rs, src/lib.rs, src/refresh_accumulator.rs, src/routing.rs, src/routing_node.rs
The code needed for the library is limited.  The key_value_store however, has no refresh message to test this behaviour at the routing layer.  I will further expand the example in the 8 points, to include an account, and corresponding refresh message.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/672)
=> Maid 1349 refresh authority

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/691)
=> Link to QA libsodium installation doc

src/structured_data.rs
I'm not sure what the code I'm removing is supposed to do but it just seems to be a convoluted way of calculating `self.previous_owner_signatures.len() > (owner_keys.len() + 1) / 2`.
The code I'm replacing it with does what the comment says it does.
Thoughts?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/724)
=> check duplicate previous_owner keys

src/relay.rs, src/routing_core.rs, src/routing_node.rs, src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/733)
=> MAID-1378 on core::reset(), collect all open connections and re-initialise

src/name_type.rs, src/routing_table.rs, src/structured_data.rs, src/test_utils/messages_util.rs, src/types.rs, src/utils.rs
This PR removes/changes some of the functions in types.rs
* The `array_as_vector` function is pointless - you can already do this with `Vec::from(slice)` or `slice.to_owned()`.
* The `vector_as_u8_{32,64}_array` functions should takes slices not vectors - there's no reason for them to be taking owned data.
Note that several other repos will have to be updated to bring them in line with these changes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/755)
=> Fix types vector functions

Cargo.toml, src/lib.rs, src/routing_node.rs
<1>
removing internal signalling which might give unexpected results - eg.,
Current flow:
fun_0() -> fun_1() { queue event_x; queue_event_y; } -> return to fun_0 -> return to event loop -> execute fun_x -> return to event loop -> execute fun_y
Now the flow will be:
fun_0() -> fun_1() { fun_x(); fun_y(); }
which appears to be better as it is suspicious to have thread-A queue events in a thread-A itself.
<2>
Integrating Using maidsafe_utilities
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/770)
=> Code clean up - intra-thread channel communication removal

src/routing_node.rs
removing internal signalling which might give unexpected results - eg.,
Current flow:
fun_0() -> fun_1() { queue event_x; queue_event_y; } -> return to fun_0 -> return to event loop -> execute fun_x -> return to event loop -> execute fun_y
Now the flow will be:
fun_0() -> fun_1() { fun_x(); fun_y(); }
which appears to be better as it is suspicious to have thread-A queue events in a thread-A itself.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/771)
=> add_peer() purged of action_sender

src/error.rs, src/routing_node.rs, src/utilities/expiration_map.rs
removing internal signalling which might give unexpected results - eg.,
Current flow:
fun_0() -> fun_1() { queue event_x; queue_event_y; } -> return to fun_0 -> return to event loop -> execute fun_x -> return to event loop -> execute fun_y
Now the flow will be:
fun_0() -> fun_1() { fun_x(); fun_y(); }
which appears to be better as it is suspicious to have thread-A queue events in a thread-A itself.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/774)
=> Replacing Intra Thread signalling

src/routing_node.rs
In `message_received` ignore incoming message correctly when message exists in `claimant_message_filter `.
Also add our own public_id to the close_group list when sending the `public_ids` back for `InternalResponse::RelocatedNetworkName`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/786)
=> Fix message_received checks

examples/churn_node.rs, examples/node.rs, examples/utils/example_client.rs, examples/utils/example_node.rs, src/acceptors.rs, src/client.rs, src/connection_management/hole_punching_state.rs, src/core.rs, src/data.rs, src/immutable_data.rs, src/lib.rs, src/messages.rs, src/node.rs, src/structured_data.rs, src/utils.rs
- Add NONCE to External Requests
This prevents repeated requests from getting filtered out, thereby allowing clients to request the same chunk twice. Also in the process of churn, NaeManagers might request a ManagedNode for a chunk which it might have previously retrieved for a client within the filter duration.
`Client` API generates a Nonce internally per request made by upper libraries.
`Node` API expects a Nonce in the API function for requests and responses since these will purely be used to respond to requests made by client from which the nonce is expected to be used to continue the message flow. The only action initiated by vaults directly for now is when chunks are relocated for `LostCloseNode`, for this a nonce is derived from the `lost_node` which should thereby yield the same …
=> Churn handling fixes

.travis.yml, appveyor.yml, src/core.rs
This is even if we have multiple connections to a node
also updated the ci scripts to pipe output to file and only print output if successful. This helps ci machines time out the run if test takes a long time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/867)
=> Only send messages on one connection

Cargo.toml, examples/utils/example_node.rs, src/core.rs, src/lib.rs, src/types.rs
MessageId generated for churn event raised by routing is unique between a node added / lost.
This prevents churn getting ignored when a Node is Added and soon after lost. In this case previously both `MessageId`'s were the same thereby getting filtered by `signed_msg_filter`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/870)
=> Churn fixes

src/core.rs, src/messages.rs
Limit the number of prospective nodes in the bootstrapping process to one per proxy node.
We also disabled the direction check for now, since we found that it makes the ci_test less reliable. This is to be expected since the notion of a "close node" is currently ill-defined, but we should consider re-enabling it once that issue is fixed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/878)
=> Join limit

src/core.rs
NewNode notifications should be sent to the other contacts in the
routing table, not to the new node itself!
Thanks @madadam for noticing this!
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/905)
=> Fix NewNode notifications.

examples/ci_test.rs, examples/utils/example_node.rs, src/core.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/926)
=> Cache MessageIds in the example node's request cache, and don't accumulate GetCloseGroup responses.

examples/utils/example_node.rs, src/core.rs, src/messages.rs
This prevents them from being filtered out if a client retries relocating.
(Also: Some fixes to log messages in example_node.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/949)
=> Add a message ID to GetNetworkName and ExpectCloseNode

src/immutable_data.rs, src/lib.rs
Implements RFC-0023.
Allow all ImmutableData type managers to obtain a copy of a chunk from any ImmutableData type manager by applying a deterministic naming scheme to the 3 ImmutableData types. 
Refer to https://github.com/maidsafe/rfcs/blob/master/proposed/0023-immutable-data-type-naming/0023-immutable-data-type-naming.md which includes the code used in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/950) &emsp; Multiple assignees:&emsp;<img alt="@Fraser999" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/190532?s=40&v=3">&nbsp;<a href="/maidsafe/routing/pulls/assigned/Fraser999">Fraser999</a>,&emsp;<img alt="@afck" …
=> Implements RFC-0023.

Cargo.toml, examples/ci_test.rs, examples/key_value_store.rs, examples/utils/example_client.rs, examples/utils/example_node.rs, src/messages.rs, src/node.rs
The `ClientManager` now waits for a `PutSuccess` from the `NaeManager`
before sending it on to the client, more success and failure responses
are now handled, and cause corresponding updates to the `dm_accounts`.
Also, the output of ci_test is now a bit less redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/961)
=> Implement responses in the example node.

src/core.rs, src/types.rs
This returns a MessageId with value 0 that can be used if there is no
danger of duplication anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/974)
=> feat/types: Add a zero constructor for MessageId.

appveyor.yml, src/structured_data.rs, src/timer.rs
This changes `Timer` so that it doesn't spawn a detached thread per scheduled task.  It also makes
`Timer` stop running the thread when dropped, whereas previously the spawned threads would sleep
unconditionally until their exipiry times.  A test for `Timer` is also added.
FIX: #1008
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1009)
=> refactor/timer: change `Timer` to use a single thread and be stoppable

src/core.rs, src/stats.rs
Also: Log `GetNetworkName` and `ExpectCloseNode` message stats.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1013)
=> perf/core: use a size instead of time limit for data_cache

examples/key_value_store.rs, examples/utils/example_node.rs, src/core.rs, src/core_tests.rs, src/data.rs, src/immutable_data.rs, src/messages.rs, src/node.rs, src/plain_data.rs, src/types.rs, tests/ci.rs, tests/utils.rs
Fix build errors and Clippy errors with Rust nightly, and rename
`Role::RoutingNode` to `Role::Node`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1020)
=> fix/core: fix build with nightly, and some cleanups

.travis.yml, Cargo.toml, appveyor.yml, examples/utils/example_client.rs, examples/utils/example_node.rs, src/action.rs, src/client.rs, src/core.rs, src/core_tests.rs, src/error.rs, src/lib.rs, src/messages.rs, src/node.rs, src/stats.rs, tests/ci.rs
This splits up requests and responses into chunks of at most 20 kB to
reduce network latency.
The caching functionality is removed, since hop nodes now only get to
see parts of `GetSuccess` responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1038)
=> feat/core: split up large and deduplicate group messages

examples/utils/example_client.rs, examples/utils/example_node.rs, src/core.rs, src/core_tests.rs, src/event.rs, src/lib.rs, src/messages.rs, src/mock_crust/crust.rs, src/mock_crust/support.rs, src/node.rs, src/peer_manager.rs, src/stats.rs, src/tunnels.rs, tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1044)
=> fix/send: fix acks, test with prng, rename some events

Cargo.toml, src/core.rs, src/stats.rs
Make the message stats log message more concise and add counters for
the message routes and failed (unacknowledged) messages.
The new format looks like this:
```
Stats - Sent 5500 messages in total, comprising 4127344 bytes, 21 uncategorised, routes/failed: [890, 4, 0, 0, 0, 0, 0, 0]/0
Stats - Direct - NodeIdentify: 3, NewNode: 61, ConnectionUnneeded: 0
Stats - Hops (Request/Response) - GetNodeName: 82/30, ExpectCloseNode: 144, GetCloseGroup: 356/446, ConnectionInfo: 315, Ack: 2931, GroupMessageHash: 638
Stats - User (Request/Success/Failure) - Get: 121/121/0, Put: 66/64/0, Post: 0/0/0, Delete: 0/0/0, GetAccountInfo: 0/0/0, Refresh: 101
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
=> feat/stats: add routes/unacked to stats and simplify the log

src/lib.rs
The `Put` flow should be described in safe_vault, not routing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1054)
=> fix/docs: remove obsolete documentation

src/mock_crust/support.rs
This fixes an issue where the RNG returned by `Network::get_rng()` is different depending on whether
called from a test which was used to initialise libsodium or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1065)
=> Make seeded RNG consistent regardless of running single or multiple tests

src/cache.rs, src/client.rs, src/core.rs, src/core_tests.rs, src/messages.rs, src/node.rs
Sorting nodes by name causes the `name()` method to be called, which
causes mock Crust event polling. Sorting should therefore only be done
when there are no events to process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1066)
=> fix/core_tests: fix node sorting

CHANGELOG.md, Cargo.toml, src/core.rs, src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1071)
=> Version change to 0.23.2

examples/ci_test.rs, examples/utils/example_client.rs, examples/utils/example_node.rs, src/core_tests.rs, src/data.rs, src/immutable_data.rs, src/plain_data.rs, src/structured_data.rs, tests/ci.rs
Avoid computing hashes in the `name` methods of the data types and data
identifier. Also replace the structured data identifier with a name,
instead of computing the name as a hash of the type tag and identifier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1074)
=> perf/data: make the name method a simple getter

src/core.rs, src/core_tests.rs, src/mock_crust/crust.rs, src/mock_crust/support.rs
This is a regression test for PR #1069. It asserts that when retrying to
bootstrap, a node first disconnects from its current bootstrap node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1075)
=> test/core: add a regression test for rebootstrap

examples/utils/example_node.rs, src/client.rs, src/core.rs, src/core_tests.rs, src/lib.rs, src/node.rs, src/peer_manager.rs, tests/ci.rs
This enables the ci test and makes the "ci_test" example work again by
making the one-node-per-local-network limit configurable when
constructing a node.
Also fixes a bug in `PeerManager` that caused valid connection info tokens to
be considered expired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1076)
=> fix/tests: re-enable ci tests, and fix a peer manager bug

tests/ci.rs
Waiting only for `GROUP_SIZE - 1` of them caused the test to fail occasionally: If the nodes weren't fully connected when they arrived at the `NodeLost` test, some `NodeLost` events were missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1081)
=> fix/test: wait for all NodeAdded events in ci.rs

src/core.rs, src/message_filter.rs
The test failed again on Travis. This increases the timeouts tenfold.
Also fixes a Clippy lint and applies `rustfmt` to core.rs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1086)
=> fix/test: further increase message filter test timeouts

src/core.rs, src/messages.rs, src/peer_manager.rs
This sends `NodeIdentify` messages instead of calling
`crust::Service::connect` for proxy and client nodes. The latter would
not result in a `ConnectSuccess` and fail to put the peer into the
routing table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1087)
=> fix/peer_manager: avoid calling connect for proxies or clients

src/peer_manager.rs, src/states/client.rs, src/states/node.rs
Don't disconnect from a client or proxy on a `ConnectionUnneeded`
message. Make the proxy node time out, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1093)
=> fix/node: ignore ConnectionUnneeded from proxies and clients

src/ack_manager.rs
This removes two iterations through the whole ack map to find a
particular timer token, at the cost of having to keep the maps in sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1105)
=> perf/ack_manager: add a map to index by timer token

src/peer_manager.rs, src/states/common/mod.rs, src/states/node.rs
This adds a new `AwaitingNodeIdentify` state to the peer manager which
comes before `Connected`. With this, a peer is in `Connected` state if
and only if it is in the routing table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1104)
=> feat/peer_manager: add AwaitingNodeIdentify peer state

CHANGELOG.md, Cargo.toml, src/ack_manager.rs, src/client.rs, src/node.rs
This reverts commit 5cadaf9430ef38e99de2abb2e362bf08a7f96c9a.
The `unwrap!` _did_ panic in the mock Crust safe_vault tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1110)
=> Version change to 0.25.1

src/messages.rs, src/states/bootstrapping.rs, src/states/common/base.rs, src/states/node.rs
Replace `send_direct_message` with `send_message` and remove
`wrap_direct_message`, to get rid of some unnecessary indirection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1114)
=> refactor/base: simplify the Base trait

src/states/client.rs, src/states/node.rs, src/timer.rs
- Do not stop timer when transitioning to Client/Node
- Remove `Timer::stop` method (the timer now stops on drop)
- Timer is now replaced with dummy mock version when use-mock-crust is enabled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1120)
=> fix/timer: timer related fixes

Cargo.toml, src/message_accumulator.rs, src/states/client.rs
This PR implements proper handling of the QuorumSize action in the client. Since this requires a change to Accumulator (maidsafe/accumulator#65) I have temporarily updated the cargo dependency definition (it should not be merged like this).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1103)
=> Handle QuorumSize action in client

src/peer_manager.rs, src/states/node.rs
Added timeout mechanism for peers awaiting a `NodeIdentify` message. It works both when we already know the peer (the `peer_manager` sets the peer state to `AwaitingNodeIdentify`) and also when we don't know the peer yet (the `peer_manager` adds the node to a map of `unknown_peers`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1130)
=> Disconnect timed out peers waiting for node identify

examples/ci_test.rs, examples/key_value_store.rs, examples/utils/example_client.rs, examples/utils/example_node.rs, src/authority.rs, src/core_tests.rs, src/messages.rs, src/states/client.rs, src/states/common/bootstrapped.rs, src/states/node.rs
Make `Authority` `Copy`.
Make the `ExampleNode` store by `DataIdentifier`, not name.
=> refactor/all: several cleanups

src/messages.rs, src/peer_manager.rs, src/routing_table/mod.rs, src/states/node.rs, src/stats.rs
This updates the 'RoutingTable' message to be a RoutingMessage (sent from a group) rather than a
'DirectMessage'.  It also adds the sending and handling of 'GroupSplit' messages.
=> MAID-1638 fix/all: add missing handling of group split messages

.travis.yml, examples/ci_test.rs, examples/key_value_store.rs, examples/utils/example_client.rs, src/lib.rs
This allows the ci_test example to pass again, but with a reduced network size of 10 nodes.  It also
fixes a long-standing bug in the key_value_store example.
=> MAID-1638: refactor/examples: fix examples

src/messages.rs, src/peer_manager.rs, src/routing_table/mod.rs, src/routing_table/network_tests.rs, src/states/node.rs, src/stats.rs
This removes the 'RoutingTable' message type, replacing it by changing the 'GetNodeNameResponse' to
contain the contents of the RT.
=> MAID-1664: fix/node: pass Prefixes as well as PublicIds to joining nodes

README.md
As explained in [this topic](https://safenetforum.org/t/please-update-your-forum-bookmark-to-safenetforum-org/11358), the previous URL is no longer working. The new URL of the SAFE Network Forum is [safenetforum.org](https://safenetforum.org/).
I also added a link to the new [Dev Forum](https://forum.safedev.org/).
=> add link to SAFE Dev Forum and fix link to SAFE Network Forum

.travis.yml, src/routing_table/mod.rs, src/routing_table/network_tests.rs, src/states/node.rs
This resolves an issue where some lists of prefixes related to merging groups were not sorted,
causing the merge test to fail sporadically.
=> fix/routing_table: update group merge prefixes to remain consistently sorted

.travis.yml, src/core_tests.rs
The joining node can legitimately receive a `GroupSplit` message as soon as it has connected to a quorum of its new group.
=> MAID-1706 fix/core_tests: don't fail on early GroupSplit events

src/states/node.rs, tests/mock_crust/churn.rs, tests/mock_crust/mod.rs, tests/mock_crust/utils.rs
This adds to pending acks beofre sending a signature or accumulating a message at hop 0.  It also
fixes a hanging mock-crust test which curently depends on acks timing out.
=> MAID-1734: fix/node: add missing pending acks

src/mock_crust/support.rs, tests/mock_crust/requests.rs
Also re-enabled test which was particularly affected by this bug.
=> MAID-1729: fix/mock-crust: fix bug in teardown of mock-crust network

src/data/mod.rs, src/data/mutable_data.rs, src/error.rs, src/lib.rs, src/messages_new.rs
Modify entry mutation procedures according to the message format in the RFC. Implement entry version checks.
This PR supersedes https://github.com/maidsafe/routing/pull/1232 and addresses the raised review comments.
=> New Request/Response types & single entry mutation function

src/peer_manager.rs, src/routing_table/mod.rs, src/routing_table/network_tests.rs
The routing table always has a group entry that corresponds to the node's
own group. Separating that from the map of groups is in many places more
natural and removes the need for unwrapping.
=> MAID-1775 separate own group and exclude own ID from needed merge contacts

src/routing_table/mod.rs, tests/mock_crust/cache.rs, tests/mock_crust/churn.rs, tests/mock_crust/utils.rs
This updates the test setup which waits for a 'GroupSplit' event to not rely on that event being
triggered by the newest node.  The new node doesn't trigger that event since it now gets constructed
with post-split groups.  This commit also re-enables a couple of tests.
=> MAID-1774: fix/test: fix mock crust test utility function

src/ack_manager.rs, src/messages.rs, src/routing_table/mod.rs, src/routing_table/network_tests.rs, src/signature_accumulator.rs, src/states/client.rs, src/states/common/bootstrapped.rs, src/states/node.rs, tests/mock_crust/accumulate.rs, tests/mock_crust/mod.rs
This is a - probably temporary - workaround for the problems with
sending a group message while merging or splitting. If we require only
the `MIN_GROUP_SIZE` nodes closest to the source address to sign the
message, it works in both cases, and replaces the other workarounds: we
don't need to store group lists in the ack manager anymore, and we can
stop resending messages when we moved out of the sending group.
=> MAID-1787 merge at most two groups at once, and fix group messages while merging

src/peer_manager.rs, src/states/node.rs
Add the necessary log statements to make it possible to compute a node's
current routing table from the logs, i.e. log every time a node is added
to or removed from the routing table, or when the prefixes change.
=> feat/node: log prefixes and connected nodes

src/routing_table/mod.rs, tests/mock_crust/churn.rs
Also extends the `churn` test by testing messages from and to `Section`s.
=> MAID-1878 Fix routing via empty groups

src/peer_manager.rs, src/routing_table/mod.rs, src/routing_table/network_tests.rs, src/states/node.rs, tests/mock_crust/churn.rs, tests/mock_crust/merge.rs, tests/mock_crust/utils.rs
Don't respond to `OwnGroupMerge` messages, as there might still be
entries left in `expected_peers`. Instead, always wait until the own
group is also ready for merging, and check for merging after expected
peers time out.
Adapt the tests so that they simulate the expected peers timing out.
=> MAID-1892 MAID-1894 fix and simplify merging, fix pm::insert and enable tests

.travis.yml, src/states/node.rs, tests/mock_crust/mod.rs
A joining node could miss a split event in a neighbouring section if it
happens between the `GetNodeNameResponse` and the first connection.
=> MAID-1908 perform missed splits on SectionUpdates

.travis.yml, examples/ci_test.rs, examples/key_value_store.rs, src/lib.rs
The examples will now build with 'use-mock-crust' enabled, but when run will print a warning and
return an error code.  Also, clippy with 'use-mock-crust' is now enabled in the Travis script.
=> MAID-1923: refactor/examples: allow examples to compile with 'use-mock-crust' enabled

src/client.rs, src/event_stream.rs, src/node.rs, src/state_machine.rs, tests/mock_crust/utils.rs
This ensures that calling `next_ev` will continually block and process all
events, necessary for, e.g. `run` in safe_vault.
Additionally, using the mpsc error types allows users of `try_next_ev` to determine
if an error was returned because there were no events available, or because of a permanent failure.
This change (mainly the first part) is necessary for my refactor of `safe_vault`
=> Fix blocking behaviour of next_ev and propagate non-blocking errors.

.travis.yml
Using multiple codegen units allows us to compile quickly in release mode, which makes the whole testing process loads faster!
Let's see what Travis makes of it...
=> Run tests in release mode

src/messages.rs, src/states/node.rs
I noticed while reviewing the message flow that a `SectionListSignature` currently contains 2 copies of the same prefix, which could be cause for confusion
=> fix/messages: remove duplicate Prefix from SectionListSignature

src/peer_manager.rs, src/states/node.rs
- Change Candidate Status log format and interval to 60 seconds.
- Accurately indicate dropped routing node log.
- Peer manager debug trait to include the section prefix
- Pruned excessive log messages from RT recovery
=> chore/misc: general cleanup

Cargo.toml, src/action.rs, src/client.rs, src/lib.rs, src/mock_crust/crust.rs, src/node.rs, src/state_machine.rs, src/states/bootstrapping.rs, src/states/client.rs, src/states/node.rs, tests/ci.rs, tests/mock_crust/utils.rs
**WARNING**: This PR needs this other one first: https://github.com/maidsafe/crust/pull/807
And then I need to change `Cargo.toml` to use upstream `crust` again
=> refactor/client: expose `crust::Config`

examples/ci_test.rs, examples/key_value_store.rs, examples/utils/example_client.rs, tests/ci.rs
I've been using the nightly compiler a bit (for incremental compilation), and it's smart enough to know that these declarations aren't used.
=> Remove unused #[macro_use] and extern crate decls

src/routing_table/mod.rs, src/states/node.rs
Updated version of https://github.com/maidsafe/routing/pull/1353
=> Estimate network size as per @Thierry61's suggestion

src/peer_manager.rs, src/routing_table/mod.rs, src/routing_table/network_tests.rs, src/states/node.rs, tests/mock_crust/utils.rs
This is another step towards fully-deterministic tests, and also allows simpler debugging of logs
containing these section members.
=> refactor/routing_table: use BTreeSet to hold section members

src/states/bootstrapping.rs, src/states/common/base.rs, src/states/node.rs
Don't return an error from send_message if serialisation fails; just log an
error and drop the message.
(This is the first of several refactors I have.)
=> chore/base: simply error handling in Base::send_message

src/routing_table/network_tests.rs
The test has been updated to handle an imbalanced network where more than one split is triggered by
the addition of a single new node.  Also 'HashSet's and 'HashMap's have been replaced with
'BTreeSet's and 'BTreeMap's respectively to make the test deterministic, and some unneeded types
and imports removed.
=> chore/test: fix bug in RT network test

src/states/node.rs
There is one change to behaviour: reject UserMessageParts while a candidate. Not 100% sure on this.
r? @afck
=> Exclusive matching in dispatch_routing_message and cleanup of handle_timeout

Cargo.toml, src/ack_manager.rs, src/lib.rs, src/messages.rs, src/routing_message_filter.rs, src/sha3.rs, src/states/client.rs
Main changes:
* `UserMessagePart`s now include the SHA3-256 hash of the full message, rather than just a SipHash.
* Outgoing routing messages are now de-duplicated using SHA3-256 instead of SipHash.
=> Use SHA-3 everywhere instead of SipHash

src/message_filter.rs, src/states/node.rs, src/tunnels.rs
This fixes a couple of issues in node when handling 'TunnelDirect' messages - one where a tunnel
client would ignore a message intended for it, and another where _any_ 'DirectMessage' being handled
by a tunnel node from a pending tunnel client would cause the node to accept both clients.
Also fixed a todo in tunnels.rs to clean up 'new_clients' when moving a pair to 'clients'.
=> fix/tunnels: fix bug when handling tunnel messages

src/lib.rs
This structure is used for verification by vaults when a new account is created.
=> feat/acct-packet: add account registration packet struct

CHANGELOG.md, Cargo.toml, src/peer_manager.rs, src/states/node.rs
Give a fresh timestamp for newly connected peers else remove_expired_peers would remove them immediately if the existing timestamp indicated >60 <90secs.
Fix bug where the tunnel node split off from the tunnel client and would never deliver TunnelSuccess message to it.
=> Version change to 0.29.0

src/routing_table/xorable.rs
In the Rust compiler, a pull request is being considered (see GitHub PR rust-lang/rust#41336) that will add support for `a |= &b` (instead of only `a |= b`) for numeric types like `u64`.
Unfortunately, this breaks the build of routing, because routing currently does the following in xorable.rs:
`result |= From::from(*elem);`
Rust is currently able to infer that the result of the `From::from()` must be `$t`, because it gets bitor-ed to a `$t`. But if the PR on the compiler is accepted, this type inference will no longer be possible, because the type of the right-hand side could then also be `&'a $t` for some lifetime `'a`.
This commit specifies the output type of the conversion explicitly, so that it doesn't require any type inference.
=> Future-proof a dependency on type inference

src/state_machine.rs, src/states/joining_node.rs
Allow mock-crust to access timer-tokens for joining node so that it can be allowed to select alternate routes in-case say the relocation request failed via the 1st route that was taken.
=> fix/joining-node: timer-tokens for joining node exposed for mock-crust

Cargo.toml, src/messages/mod.rs, src/mock_crust/crust.rs, src/mock_crust/support.rs, src/mock_crust/tests.rs, src/peer_manager.rs, src/states/bootstrapping.rs, src/states/joining_node.rs, src/states/node.rs
- This will allow external reachability check to succeed when bootstrapping as a CrustUser::Node role.
- Enable Service discovery as first node on startup and in other cases only after NodeApproval completes successfully.
- Also fix log format for node add/remove to RT and RT size msg.
- Remove redundant log/comments about NodeIdentify.
=> fix/bootstrapping: Also start listening as JoiningNode before bootstrap

src/states/node.rs
check if conn info req is sent to existing candidate. In this case, set peer as valid and them to the RT.
=> Conditionally promote peer from Candidate to Routing state

.travis.yml, src/messages/mod.rs, src/mock_crypto.rs, src/peer_manager.rs, src/states/bootstrapping.rs, src/states/node.rs, src/stats.rs
This adds a new 'PeerState' variant for bootstrapping peers which contains the type of connection
(client or node).  That's used to replace the 'bootstrappers' container in 'Node'.
There are further restrictions placed on the types of messages clients and bootstrappers can send,
and some trivial renaming changes included in this commit.
=> MAID-2080: update handling of bootstrapping nodes

src/data/mod.rs, src/data/mutable_data.rs, src/lib.rs
It should no longer be possible to exceed the limits using the operations that perform validation (`mutate_entries`, `set_user_permissions`, ...).
=> Make mutable data validation more strict

src/client.rs
This function executes the new RPC request, `GetMData`
=> feat/client: add missing get_mdata function

src/action.rs, src/client.rs, src/mock_crust/crust.rs, src/state_machine.rs, src/states/bootstrapping.rs, src/states/client.rs, src/states/joining_node.rs, src/states/node.rs
Now the Crust config is resolved by using the new exposed function `crust::read_config_file`, so we don't
need to exchange `Action::Config` messages and get the bootstrap config from Crust services anymore.
=> refactor/config: get config from Crust statically

src/client_error.rs, src/data/mutable_data.rs, src/lib.rs
This PR improves the errors returned from operations on `MutableData`:
- `ClientError::InvalidSuccessor` now contains the current version, so if the client want's to re-send the request with the correct version, it doesn't have to first send additional request to fetch the version.
- new variant `ClientError::InvalidEntryActions` is returned from `mutate_entries` and it contains breakdown of the errors per entry. This makes it easier to re-send the request with corrected actions.
=> feat/mutable-data: make errors more descriptive

src/peer_manager.rs, src/states/node.rs
Due to the nature of parallel bootstrap attempts by crust it can happen that two clients with same IP successfully trigger a bootstrap accept in the same proxy but one of them decides to choose another proxy. That client will have disconnected from this proxy but the other client, C, could have decided to choose this one. So C gets a bootstrap connect. However if C was the latter of the two for this proxy and if this proxy hasn't yet realised that the first client has disconnected before it got the bootstrap accept for C, it is going to reject C on basis of one-client-per-IP rule. So C will get a disconnect event after it has received a bootstrap connect.
Moving this check to Bootstrap request should prevent this as only the ones who are interested in this proxy will be sending the …
=> fix/bootstrap: enforce one client per IP only on bootstrap request

src/messages/mod.rs, src/node.rs, src/rate_limiter.rs, src/state_machine.rs, src/states/node.rs, tests/mock_crust/client_restrictions.rs
1. Refund on overcharge for get response
2. Soft-limit for clients - `max(MAX_IMMUT_DATA_SIZE, MAX_SOFT_CAP/clients_in_rate_limiter)`
Incorporates #1508 and #1510. The Ninja-ing continues.
=> MAID-2198: improve rate limiter

src/chain.rs, src/network_event.rs
Update naming of State for DataChain and Adult containers. Chain is a state transition sequence (ordered) and the Adults are a simple current state of applicable Peers container.
=> Update the Enders Adults enum to SectionState

.travis.yml, examples/key_value_store.rs, scripts/clippy, scripts/tests
Hi Jean/Pierre,
This now runs 4 jobs in parallel:
* Clippy on Linux
* Clippy on OSX
* Tests on Linux
* Tests on OSX
As we discussed, the 2 long-running tests have been disabled.
Here is a log with timings for the 2nd run, where the cache takes effect: 
https://travis-ci.com/jacderida/routing/builds/103562433
There is also a small fix for something clippy flagged up.
Cheers,
Chris
=> CI Test Run Refactor

examples/key_value_store.rs
To fix clippy error in CI
"error: use of deprecated item 'core::str::<impl str>::trim_right_matches': superseded by `trim_end_matches`"
=> chore/ci: update deprecated item as per clippy

routing_model/index.html
For readibility, it is important that the width of the text section is
limited. However, some graphs become a bit too compact if held to the
same constraints.
Modify the css to allow for different standards for the width of text
blocks (.description) and diagrams (.mermaid)
=> Allow the graphs to be wider than the text

src/chain/chain.rs, src/states/node.rs
- Remove old compatible neighbour pfx not restricted to a strict parent/child prefix in Chain on updating neighbour_infos.
- Send ParsecPoke to all section members to prevent connection timeouts triggering invalid Offline votes while JoiningNode is getting established. This prevents invalid test failures with unaccumulated Parsec::Remove blocks.
=> NeighbourInfo cleanup and send ParsecPoke to all members

routing_model/index.html
We are already in a shared state when entering ProcessMerge as we come
from consensus on a timer event.
All nodes agree, so we can send the RPC imediately.
=> Send Merge RPC without extra consensus round

Cargo.toml, appveyor.yml, scripts/clippy, scripts/tests, scripts/travis_wait, src/lib.rs, src/mock_crust/support.rs, src/mock_parsec/mod.rs, src/mock_parsec/tests.rs, src/states/node.rs
So mock crust / mock crypto can be enabled independently from mock parsec.
Also rename `mock_parsec::init` to `mock_parsec::init_mock` for more explicitness.
=> Add mock_parsec feature

routing_model/index.html
Rendered:
https://raw.githack.com/maidsafe/routing/34a0bb7adbcebafb25c1d923365f6c65bda87677/routing_model/index.html
(first 4 commits: https://raw.githack.com/maidsafe/routing/1b760bc491526a193a94022207450666b9fadd65/routing_model/index.html)
(first 2 commits: https://raw.githack.com/maidsafe/routing/81f5b6043660f59caefb0c19b32e05ca8d0abdd6/routing_model/index.html)
Note:
Initially remove re-send ExpectCandidate to section with shorter_prefix.
It complicates flow by involving unknown number of section in the process.
Re-add this functionality between the connection being established and the resource proof started as an immediate relocate with the same age.
Handles RPC Replay for ExpectCandidate/RelocateResponse:
- Destination only trust a CandidateInfo if it has proof that the source …
=> Routing model handle replay,loss,trust and split

routing_model/src/actions.rs, routing_model/src/scenario_tests.rs, routing_model/src/utilities.rs
This will support migration to the new flow diagram that include
work unit increment.
=> Switch from mocking to faking work unit to decide relocation

src/mock_crust/support.rs
This deserialisation took ~7% of CPU time in merge_four_balanced_sections_into_one.
=> perf/mock_parsec: Optimize Network::send, don't deserialise.

routing_model/index.html
If receiving the Merge RPC from our sibling trigger the merge, then
we need to proceed with voting the new section imediatly and not wait
forever.
Rendered: https://raw.githack.com/maidsafe/routing/90d6cb146bf4fdbb2730971606d8f68f8f32ad43/routing_model/index.html
=> routing_model: fix merge when receive Merge RPC first.

routing_model/src/flows_dst.rs, routing_model/src/lib.rs, routing_model/src/scenario_tests.rs, routing_model/src/state.rs
Implemented the suggested simplification from https://github.com/maidsafe/routing/pull/1601#discussion_r274847539
=>  Flow tests: simplify ProcessElderChange subprocess

Cargo.toml, scripts/clippy, src/lib.rs, src/messages/mod.rs, src/mock_crust/crust.rs, src/mock_crust/mod.rs, src/mock_crust/support.rs, src/states/bootstrapping.rs, src/states/client.rs, src/states/common/base.rs, src/states/common/bootstrapped.rs, src/states/common/mod.rs, src/states/joining_node.rs, src/states/node.rs, src/states/proving_node.rs
Not serialize when sending messages.
Not serialising full content when verifying HopMessage
mock_crust::churn::aggressive_churn
seed: Some([0,1,2,4]):
Before: 100 seconds  (features=mock_parsec)
After:   23 seconds  (features=mock_serialise_send)
Note:
- The big remaining serialisation item is SignedMessage::check_integrity, we may remove it as part of N/3 message passing. Removing it aggressive_churn is 13.5 seconds.
- After that, what remains is in mock parsec, and the Message clone used to mock serialization.
=> mock serialise: 4x speed up aggressive churn

Cargo.toml, examples/ci_test.rs, examples/key_value_store.rs, examples/utils/mod.rs, scripts/clippy, src/ack_manager.rs, src/chain/chain.rs, src/chain/mod.rs, src/client.rs, src/data/immutable_data.rs, src/lib.rs, src/macros.rs, src/message_filter.rs, src/node.rs, src/peer_manager.rs, src/rate_limiter.rs, src/resource_prover.rs, src/routing_table/mod.rs, src/routing_table/network_tests.rs, src/state_machine.rs, src/states/bootstrapping.rs, src/states/client.rs, src/states/joining_node.rs, src/states/node.rs, src/time.rs, src/timer.rs, src/types.rs, src/utils.rs, tests/ci.rs, tests/mock_crust_tests.rs
Rename `mock` to `mock_base`.
Re-add `mock` feature to mean mock all: mock_parsec,mock_serialise.
For fastest soak testing use features=mock.
Test:
time RUSTFLAGS=-g cargo test --release --features=mock
=> 1 min
time RUSTFLAGS=-g cargo test --release --features=mock_serialise --
--skip aggres --skip messages_during_churn
=> 22 min
mock_crust::churn::aggressive_churn seed: Some([0,1,2,4])
=> Killed after 2 hours as it was still running.
=> chore/routing: change 'mock' to mock all, and rename to `mock_base`.

Cargo.toml, src/parsec.rs, tests/mock_crust/churn.rs
- refactor: use is_opaque from parsec
- make messages_during_churn match new node acceptance threshold match aggressive_churn
- randomise proxy and inserted indexes for new nodes to highlight any sequential poll issues with mock_base.
=> make churn tests more aggressive and minor refactoring

src/chain/mod.rs, src/chain/network_event.rs, src/messages/mod.rs, src/peer_manager.rs, src/resource_prover.rs, src/states/node.rs, src/states/relocating_node.rs, tests/mock_crust/mod.rs
Add:
-ExpectCandidate struct from MessageContent::ExpectCandidate.
-NetworkEvent::ExpectCandidate to consensus the RPC and the
RPC destination used as the source of the response.
Remove:
-MessageContent::AcceptAsCandidate replacing its function with consensus
through Parsec of NetworkEvent::ExpectCandidate.
-Candidate::Expecting that was used when waiting AcceptAsCandidate.
-CANDIDATE_ACCEPT_TIMEOUT_SECS
Replace:
-expect_candidate with has_candidate: Do not raise an error in handling
the parsec event because we already have a candidate.
Update handling ExpectCandidate:
-handle_expect_candidate only vote for the received RPC.
-new handle_expect_candidate_event take on combined responsabilities
of handle_expect_candidate and handle_expect_candidate_event.
-only processed events if member of …
=> Replace AcceptAsCandidate RPC

src/mock_parsec/block.rs, src/mock_parsec/mod.rs, src/mock_parsec/observation.rs
Observation is cloned and stored multiple times. It is also cloned
between the different mock_parsec instances for the same section.
Use Rc to keep a single copy, increasing speed and space efficiency.
Test: aggressive_churn (features=mock) (seed: Some([0,1,2,4]))
Before:  16.2 seconds - 1.2 GB
After:   14.7 seconds - 457 MB
=> perf/mock_parsec: use Rc to avoid duplicating Observation

src/states/node.rs
remove_expired_peers update peer_manager.candidate that we want to move
to the chain eventually: Simplify behaviour so it only happen in
this time out. Remove implied constraint that remove_expired_peers was
needed.
Test:
Soak test churn 22 others 250.
=> fix/routing: only remove_expired_peers on timeout.

src/client.rs, src/mock_parsec/mod.rs, src/mock_parsec/observation.rs, src/node.rs, src/parsec.rs, src/peer_manager.rs, src/state_machine.rs, src/states/bootstrapping.rs, src/states/bootstrapping_peer.rs, src/states/client.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/common/bootstrapped_not_established.rs, src/states/common/mod.rs, src/states/common/not_established.rs, src/states/common/proxied.rs, src/states/common/relocated.rs, src/states/common/relocated_not_established.rs, src/states/establishing_node.rs, src/states/mod.rs, src/states/node.rs, src/states/proving_node.rs, src/states/relocating_node.rs, tests/mock_crust/drop.rs, tests/mock_crust/utils.rs
This is a refactoring PR with almost no functional changes. Exceptions are some minor changes for the sake of simplicity, clarity or performance. They are listed below:
1. When `EstablishingNode` receives `NodeApproval`, it backlogs it and once it becomes `Node` it logs and ignores it. Previously it would immediately log and ignore it.
2. In `EstablishingNode`, `handle_hop_message` and `send_routing_message_via_route` now work the same way as in `ProvingNode` as opposed to the way they work in `Node`. This makes it more explicit what the responsibilities of each of the states are.
=> Refactor Node state: extract EstablishingNode state

src/ack_manager.rs, src/client.rs, src/node.rs, src/peer_manager.rs, src/rate_limiter.rs, src/routing_message_filter.rs, src/state_machine.rs, src/states/node.rs, tests/mock_crust/client_restrictions.rs, tests/mock_crust/mod.rs, tests/mock_crust/utils.rs
Refactor in multiple commits to ease access to node state in test avoiding much boiler plate code.
Add new test verifying behaviour when a candidate does not go through with resource proof.
Extend poll_and_resend with pool_and_resend_until to stop progression when condition reached.
=> test candidate fail resource proof

Cargo.toml, src/mock_parsec/mod.rs, src/node.rs, src/parsec.rs, src/peer_manager.rs, src/resource_prover.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/common/relocated.rs, src/states/common/relocated_not_established.rs, src/states/establishing_node.rs, src/states/node.rs, src/states/proving_node.rs, src/utils.rs, tests/mock_crust/utils.rs
- get rid of `notified_nodes` (not needed as `PeerManager` can handle the logic itself now)
- rename `PeerState::Routing` to `PeerState::Node` and `add_to_routing_table` to `add_node`
- change `self.chain.is_valid_peer` to `self.is_valid_peer`
- bump parsec version and rename `has_unconsensused_observations` to `has_unpolled_observations` in mock parsec.
- backlog `Event::NodeAdded`/`Event::NodeLost` until we become `Node` to make sure they are send *after* `Event::Connected`.
- Improve logging by introducing `LogIdent` utility struct which is to be used as prefix for all log messages for log consistency.
=> Misc code cleanup

src/chain/chain.rs, src/chain/network_event.rs, src/node.rs, src/peer_manager.rs, src/state_machine.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/establishing_node.rs, src/states/node.rs
We want to ensure eventually that the candidate is a state shared by
all peers in the section. To do that all modification must be the
result of reaching consensus on an event.
We use a new consensused event PurgeCandidate to decide together
whether a candidate failed or succeeded.
=> consistent failed candidate when timing out

src/chain/mod.rs, src/chain/network_event.rs, src/peer_manager.rs, src/states/common/approved.rs, src/states/establishing_node.rs, src/states/node.rs, tests/mock_crust/utils.rs
Add new tests to cover when PurgeCandidate comes before Online event.
Fix the code to ensure the test pass:
- Add new field to NetworkEvent::Online with the old_public_id.
- Use that field to decide whether we should accept the new member
or vote it offline consistently imediately.
Both auth_client and old_public info are needed because the current
node did not receive the CandidateInfo. Keep them together in a
struct that will be serialized as related_info.
Note:
-This is not ideal because it introduce a new quirk: when candidate is
rejected, it is added then removed. This did not happen before.
The benefit is all node behave consistently, and this will be better
addressed soon when introducing Opaque Online/Offline NetworkEvent.
-Now PeerManager::candidate has an expectation to only …
=> fix/states: remove candidate when PurgeCandidate event comes first

src/mock_parsec/mod.rs, src/mock_parsec/observation.rs, src/mock_parsec/state.rs, src/mock_parsec/tests.rs
So that observations which initially didn't have enough votes for consensus, but later due to some peers being removed have enough, are properly consensused.
=> mock-parsec: reevaluate previously unconsensused votes

src/resource_prover.rs
Addresses a minor TODO in the code to use 'break' with value syntax which is now supported by Rust.
=> chore: use break with value syntax

src/chain/chain.rs, src/chain/network_event.rs, src/mock_crust/support.rs, src/node.rs, src/parsec.rs, src/peer_manager.rs, src/state_machine.rs, src/states/common/approved.rs, src/states/common/relocated.rs, src/states/establishing_node.rs, src/states/node/mod.rs, src/states/node/tests.rs, tests/mock_crust/utils.rs
Avoid temporarily adding candidate that fail resource proof.
Open door for Node Ageing Adults that do not become Elder. 
Some additional test uncover more issues that will not be addressed here:
https://github.com/maidsafe/routing/pull/1636
=> use opaque Offline/Online event

Cargo.toml
We had some soak testing issues with the previous PARSEC head that used
a concrete coin.
The problem came from different nodes sometimes having a different
perception of the concrete coin, which was to be expected by definition
of a concrete coin. It was an issue due to an implicit assumption that
existed in the PARSEC code that if a node learnt about consensus, any
node hearing from them should immediately reach the same conclusion.
Rather than changing the erroneous assumption, we replaced the concrete
coin with a common coin that is predictable.
It suffers from a lack of asynchrony as an adversary which controls the
scheduler could use this property to affect Liveness; but should be good
enough as a place-holder until we implement DKG, BLS and a proper common
coin.
Having routing point …
=> fix/parsec: Update to Parsec with temp common coin

src/messaging/mod.rs, src/routing_table/mod.rs, src/state_machine.rs, src/states/node/mod.rs, tests/ci.rs
I silenced the error below as the suggested fix didn't make sense and was unsure how to resolve:
```
error: identical conversion
--> src/states/node.rs:3099:21
|
3099 |         for part in user_msg.to_parts(priority)? {
|                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider removing `user_msg.to_parts(priority)?()`: `user_msg.to_parts(priority)?`
|
note: lint level defined here
--> src/lib.rs:105:5
|
105  |     warnings
|     ^^^^^^^^
= note: #[forbid(clippy::identity_conversion)] implied by #[forbid(warnings)]
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#identity_conversion
```
All other errors are fixed
=> chore/clippy: resolve clippy errors

src/node.rs, src/state_machine.rs, src/states/adult.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/mod.rs, src/states/proving_node.rs
This PR is purely a rename to facilitate upcoming changes regarding node-ageing impl spec.
=> rename EstablishingNode to Adult and Node to Elder

src/peer_manager.rs, src/states/elder/mod.rs
candidate_timer_token was used before we moved to Parsec to ensure
the RPC from different elders would be sent at the same time.
This is no longer needed with Parsec: Send it when resource proof is
complete.
=> clean up timer to vote node is approved

src/chain/chain.rs, src/chain/mod.rs, src/chain/shared_state.rs, src/chain/test_utils.rs, src/states/common/approved.rs, src/states/elder/mod.rs
This PR adds a new struct - `SharedState` - which contains all the eventually-consistent data shared among all elders of a section. 
It also changes the way `our_infos` are stored to statically guarantee they are never empty, which simplifies some code and allows to remove one `unwrap` from production code.
=> Extract shared state

src/node.rs, src/states/elder/mod.rs, src/states/proving_node.rs, tests/mock_network/mod.rs, tests/mock_network/utils.rs
This PR contains the work of making a joining_node resend ConnectionInfoReq and CandidateInfo to an elder in case of not having connection to it or hasn't started resource proofing with it. Which allows resource proofing to be carried out with lagging elders.
A test is also create to confirm that the update will work as expected.
=> Resource proofing with lagging elders

tests/mock_network/requests.rs
Addresses a TODO to assert that 'quorum' number of put and get requests are received.
=> test: assert quorum in request tests

src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs
This is another attempt at fixing the problem described in 9fdadac3c296a672f1acf3705355af5855ae5e95 which triggers failures in mock_crust::merge::concurrent_merge.
When adding new sections either cache the ProvingSections in case a prefix change causes the accumulation to fail so we can vote for them again in the new prefix, or vote for them straight away if we just have gone through a prefix change where the other half of the section has not caught up yet.
=> Fix concurrent merge test fail by adding a ProvingSection cache

.travis.yml, scripts/fixup_check
Hi Pierre/Fraser,
This is a bit trivial, but Stephen wanted me to come back to this issue of some protection against fixup commits.
This isn't completely perfect because I don't know how to get the commits just for a particular PR. There is a mechanism for doing that with `git log fleming..branch_name`, but on Travis it only seems to have the current branch in the clone, so if you try to do it that way it errors.
It's also possibly a bit excessive to have this in its own job because that spins up a machine, but I wasn't sure how to specify the 'if PR' conditional without doing that.
[Here](https://travis-ci.com/jacderida/routing/builds/114561421) is an example of the job not triggering on a PR. [Here](https://travis-ci.com/maidsafe/routing/builds/114561425) is an example of it failing a …
=> Check for Fixup Commits

src/messages/mod.rs, src/mock/crust/support.rs, src/states/adult.rs, src/states/client.rs, src/states/common/base.rs, src/states/common/bootstrapped_not_established.rs, src/states/elder/mod.rs, src/states/proving_node.rs, src/states/relocating_node.rs
With secure message relay, we used to verify each hop message to avoid
transmitting spammy messages to the rest of the network.
This pattern is going away with the introduction of Reliable Message
Delivery where we ensure that any message passed to us will be
transmitted.
The logic to ensure message validity will only happen at destination
once Secure Message Delivery is introduced.
Fixes #1661
=> Remove all verification logic from hops

src/error.rs, src/messages/mod.rs, src/resource_prover.rs, src/states/client.rs, src/states/common/mod.rs, src/states/elder/mod.rs, src/states/relocating_node.rs
Replace `MessageContent::UserMessagePart` with `MessageContent::UserMessage` which contains the whole message. Remove all the logic around splitting the message into parts and reassembling it back.
This is possible to do because quic-p2p internally re-prioritizes the messages based on size, so big messages no longer block the small ones and so it's no longer necessary to chunk them.
Closes #1695
=> Remove UserMessage chunking

appveyor.yml, scripts/tests, src/mock/quic_p2p/network.rs, tests/mock_network/utils.rs
So we still get the seed in case the tests get stuck.
Also modify the CI scripts to run tests with --features=mock instead of --features=mock_parsec to speed them up.
=> Print rng seed before tests start

src/mock/quic_p2p/mod.rs, src/mock/quic_p2p/node.rs, src/mock/quic_p2p/tests.rs, src/states/common/base.rs
This PR contains the change to resolve a clippy error due to the change in quic-p2p crate.
=> fix/mock: catch up with the change in quic-p2p

src/chain/test_utils.rs, src/states/common/base.rs, src/states/elder/mod.rs
Closes #1684
Because of additional messages sent, soak test experienced a performance hit.
Remove main bottle neck for performance that came from previous way of establishing trust that is disabled currently and will be replace by Secure Message Delivery.
=> fix performance issue following PR 1705

src/lib.rs, src/mock/quic_p2p/tests.rs, src/network_service/mod.rs, src/states/bootstrapping_peer.rs, src/states/common/base.rs
Spandan higlighted that Bytes is a reference counted type.
This clarified that we were being inefficient in memory and CPU when
sending 3 messages.
quic_p2p take in a Bytes type that is a reference counted type:
- Refactor to do cheap operation multiple time (Rc clone) instead of
expansive operation (serialize + allocate memory for message 3 times).
- Refactor mock_serialize to follow the same pattern.
Ensure all messages go through the same resend process and hide the
token implementation detail.
=> perf/quic_p2p: avoid many serialization on send/use Rc

src/chain/bls_emu.rs, src/chain/chain.rs, src/chain/mod.rs, src/chain/shared_state.rs, src/lib.rs
This PR makes some initial changes related to SMD:
- Add a BLS emulation layer in order to enable writing code that pretends to use BLS before BLS is merged in
- Add `our_history` and `their_keys` to the shared state
- Update `our_history` together with `our_infos`
Closes #1672
Closes #1673
Closes #1674 
Closes #1675
=> Secure Message Delivery initial changes

src/chain/chain.rs, src/chain/shared_state.rs, src/state_machine.rs, src/states/elder/mod.rs
=> Update their_keys on consensus about a section info

src/messages/mod.rs, src/node.rs, src/routing_table/prefix.rs, src/state_machine.rs, src/states/elder/mod.rs, src/states/relocating_node.rs, tests/mock_network/mod.rs
=> feat/node: send Ack on consensused message

src/chain/chain.rs, tests/mock_network/churn.rs, tests/mock_network/merge.rs
Merge functionality is partially broken and will be more as
development continue ignoring it. New functionality will break down
on Merge.
We may want to completely strip the merge functionality out since it
is now untested and will rapidely bit-rot requiring a rewrite if we
want to re-add it.
-Ensure that no test proceed to trigger merge: panic if merge occur.
-Update churn tests to not trigger merge, but still cover churn and
prefix change (split).
Test:
Run soak tests.
=> feat/routing: disable merge in tests - panic on merge

src/chain/bls_emu.rs, src/chain/chain.rs, src/chain/mod.rs, src/chain/shared_state.rs, src/parsec.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs
This place the building block of sharing state with only part of
SharedState. Follow up will add their_keys, and neighbour_infos as
weel as their_knowledge.
Disable prunning our_infos, this is required until their_knowledge
is solid and shared state as we require updates to our_infos to be
shared by all peers in exactly the same way.
Test:
Run soak tests.
=> feat/routing: ensure part of our state is shared our_infos/our_history

src/chain/chain.rs, src/chain/mod.rs, src/chain/network_event.rs, src/messages/mod.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/relocating_node.rs, tests/mock_network/mod.rs
Partial fix for #1670
Their knowledge is a map of their prefix to our version that they know.
The AckMessage need to contain the prefix, and the consensused message
need to consensus that prefix with the version.
We incorrectly used our own section that we consensused and then update
our prefix and version.
Test:
Update check_section_info_ack so it fails without this fix.
Run clippy+ soak test
=> fix/routing: update their_knowledge for correct prefix

src/chain/bls_emu.rs, src/chain/chain.rs, src/chain/mod.rs, src/chain/shared_state.rs, src/error.rs, src/lib.rs, src/messages/mod.rs, src/mock/quic_p2p/tests.rs, src/signature_accumulator.rs, src/states/common/bootstrapped_not_established.rs, src/states/elder/mod.rs
This is completing PR https://github.com/maidsafe/routing/pull/1721
This adds the facilities in SignedRoutingMessage and Chain necessary for checking whether a message can be trusted: Closes #1668 
Also fill the security metadata in appropriate places in the code Closes #1669 
This is the first building block of the end to end solution.
There are some limitations. In particular:
- This security is only done for Message with Section as the source.
- their_knowledge is not used as it can be unreliable so we send the full proof from genesis with all messages.
- We are filtering before the signature check
- We are adding SectionInfo before signature check
Test:
Run soak tests + clippy
=> Implement sender verification

src/chain/chain.rs, src/chain/mod.rs, src/chain/network_event.rs, src/chain/section_info.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs
Closes #1737 
Closes #1667 
When updating their_knowledge, we need to ensure that all nodes we
will communicate with will have enough information to check trust.
In order to achieve this, we have to have all nodes in a section
acknowledging updating their_keys before sending the AckMessage.
This is not something we could do at the signature accumulation stage
as a malicious node could still send the message early.
The failure mode here is that we do not send AckMessage and we receive
more information than needed. It is much better than what we have
currently implemented as we currently send all proofs.
Additionally, we will be able in the future to detect this as Malice
and punish nodes. We will in the future also need to ensure this
SendAckMessage consensus even in case of membership …
=> feat/routing: use their_knowledge ensuring it is never ahead of a node

src/chain/chain.rs, src/chain/shared_state.rs, src/states/elder/mod.rs
Closes #1742 
Because of message re-ordering, some older key version could consensus after the new ones.
Ensure we ignore these so section would not loose the ability to trust each other:
- if we notified with AckMessage that we trust a version, and then reverted their_keys to a previous version, we would no longer trust messages coming from that section.
- Additionally the code does not handle merge, so if a previous version was for a shorter prefix, this would cause additional issues.
=> ensure old key versions are ignored

src/chain/chain.rs, src/chain/mod.rs, src/chain/network_event.rs, src/chain/shared_state.rs, src/messages/mod.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, tests/mock_network/mod.rs
Closes #1740 
Closes #1744 
Closes #1746 
- Ensure we update their_keys/their_knowledge for ourselves so we can trust message from self section, and send minimal proof to self section: prune proof similarly when we receive an AckMessage.
- Move adding received messages src SectionInfo/SecurityMetadata only when we are the final recipient and have check the signature.
- Use new NetworkEvent to handle receiving Section Signatures:
=> Fix their_knowledge after split since we no longer ignore that version when sending Ack.
=> Ensure we get their_keys, and send AckMessage for non neighbour sections that were filtered in `add_new_section`.
=> fix split their knowledge

src/chain/bls_emu.rs, src/chain/chain.rs, src/chain/mod.rs, src/chain/network_event.rs, src/chain/section_info.rs, src/chain/shared_state.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs
Prepare to address https://github.com/maidsafe/routing/issues/1748.
-NeighbourInfo sent as a Section message like other messages so we can trust the content and reduce number of messages
-Rename to SectionKeyInfo as it will be used in multiple context to address #1748 
-Clean up handling of message from self, ensuring their_keys are propulated with our keys from the very first block.
=> Clean ups related to neighbour info

src/chain/bls_emu.rs, src/chain/chain.rs, src/chain/shared_state.rs, src/messages/mod.rs, src/mock/quic_p2p/tests.rs, src/signature_accumulator.rs, src/states/common/bootstrapped_not_established.rs, src/states/elder/mod.rs
Closes #1748 
src_section should not be part of SignedRoutingMessage. In order to remove it we need to first use security_metadata to update `their_keys`, second send the SectionInfo with NeighbourInfo.
The first commit restructure the code so the SectionProofChain contain the needed info to update their_keys. (BlsPublicKey, Version, Prefix, all held in SectionKeyInfo). All this info should be signed by the proof contained in SectionProofChain. Currently this is done by holding on to a signed SectionInfo under the hood. When using real BLS, we will need to sign the SectionKeyInfo, and that SectionKeyInfo will directly contain BlsPublicKey, Version, Prefix.
The second commit update NeighbourInfo, and remove the use of src_section.
=> use security metadata and remove src section

src/messages/mod.rs, src/routing_table/authority.rs, src/states/common/relocated.rs, src/states/elder/mod.rs
Closes #1738 
- This only provide moderate additional security: We validate that the
'src' of the message has signed the message (src+dst+content).
- Also use that to check that new connection are comming from the 'src'.
Note: For ManagedNodes (but not for Client Authority), it would be
possible to ensure the node is a valid member of a section
(https://github.com/maidsafe/routing/issues/1751).
Note: We are still allowing untrusted communication. We will need to
ensure that we do not treat untrusted communication as trusted (see
https://github.com/maidsafe/routing/issues/1756)
Test:
Clippy + soak test
=> feat/routing: sign and check single source message with ED key

src/messages/mod.rs, src/states/common/bootstrapped_not_established.rs
Closes #1756 
All routing messages should be signed as we then use the content to
make decision within routing base on the accuracy on the information.
Unsigned messages need to be handled separately as we cannot trust its
content. Currently they are not used, but for Vault to send RMD messages
this will probably be unsigned messages (though they could also be
single source signed like we do for relocate requests here).
Test:
Clippy + soak test
=> feat/routing: do not implicitly trust unsigned messages

src/messages/direct.rs, src/signature_accumulator.rs
The test `section_src_add_signature_last` relies on using using mocked time.
Fixes `cargo test` when run without `mock`.
=> Move unit test to mock_base

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/mod.rs
chain_accumulator & completed_events work together.
We will need to update them to handle signing BLS key, so extract them and add unit test.
Partially address https://github.com/maidsafe/routing/issues/1768
=> refactor chain accumulation and add tests

src/mock/parsec/mod.rs, src/mock/parsec/tests.rs
The bug happened in a situation like this:
Say there are 8 nodes in the section and the genesis group size is 4. A new node X joins. Another node Y is in the process of being voted in, but so far has only 4 votes. X receives a gossip which triggers the consensus calculation. In mock parsec, this means reaching into the shared state and picking the first unconsensused observation. That happens to be Add(Y). There are 4 votes for it. X only knows about 4 valid voters at this point (the genesis group), so it thinks there are enough votes and marks the observation as consensused. Thus Add(Y) is consensused prematurelly.
The fix is to make sure the new node catches up to all the previously consensused blocks before it itself performs the consensus calculation.
=> Fix premature consensus in mock parsec

src/chain/bls_emu.rs, src/lib.rs, src/signature_accumulator.rs, tests/mock_network/accumulate.rs
This makes the emulated BLS more compatible with the real BLS. Some tests had to be updated, because they were making explicit assumptions about the number of signatures needed for a message to accumulate.
Parts of the `messages_accumulate_with_quorum` test are being removed, because they became irrelevant. The reason is explained below.
In earlier versions of the code, only the accumulating nodes would generate the full message, and the others would only send signed hashes. Because of that, a message couldn't accumulate until an accumulating node also generated a signature and the message itself along with it. That's the case these parts of the code were testing.
However, since RMD and SMD, all nodes send full messages when they send signatures. This means that the case they were testing …
=> Change the threshold in BLS to just one third of the members

src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs
This PR changes the candidate approval process so that it now happens on consensusing `Online`. This promotes the candidate to Adult which allows them to participate in parsec gossip and thus in the DKG. This PR does not implement the DKG handling itself though.
Closes #1773
=> Approve candidate earlier to allow them to participate in DKG

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/mod.rs, src/chain/network_event.rs, src/chain/proof.rs, src/chain/section_info.rs, src/chain/shared_state.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs
In order to support BLS, we need to be able to add a different signature share for each of the votes for a new SectionInfo.
This PR allow this to still accumulate based only on the SectionInfo part of the Parsec payload.
This first commit setup the test as a stepping stone using a different type.
The second commit refactor the code to be able to re-use the enum.
=> additional non accumulating signature share

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/mod.rs, src/chain/network_event.rs, src/chain/section_info.rs, src/chain/shared_state.rs, src/error.rs, src/states/elder/mod.rs, src/states/elder/tests.rs
Closes #1769 
Building on PR #1802 , we are now adding a signature share to the parsec payload containing the SectionInfo. When ready, we will be able to also/instead sign the SectionKeyInfo when we add it as a result of the DKG (i.e `NetworkEvent(SectionInfo,SectionKeyInfo)).
The initial commits clean up code that was no longer used.
=> sign SectionInfo with share

src/mock/parsec/mod.rs, src/parsec.rs
Resolves #1784
Keep track of size and number of requests/responses so we can prune/reset the parsec gossip graph before it becomes too bloated.
Note that we use `serialised_size` to accumulate the size. This may turn out to have a performance impact so we might need to address this properly in the future. Maybe to have parsec tell us the request/response size.
=> Detect if PARSEC needs pruning

src/chain/bls_emu.rs, src/lib.rs, tests/mock_network/accumulate.rs
PR #1785, which changed the emulated BLS threshold to 1/3 of the section instead of 2/3, broke the node joining process when tested with production PARSEC. Since the joining process will be significantly modified soon (when #1811 is done), we decide not to look for a proper fix, but revert the changes instead and reapply them after #1811 lands (and fix then if still necessary).
=> Revert PR #1785

src/messages/mod.rs, src/parsec.rs
Fixes the vote_prune test when runnig with `mock_base` or `mock_serialise`.
NOTE: test still fails for unrelated reasons until #1813 is merged
Resolves #1815
=> Tune prune limit for real PARSEC

Cargo.toml, src/peer_map.rs
The `PeerMap` contained fields that were `HashMap`s and were being iterated over. This changes the fields to `FxHashMap`s, which provide the same order of iteration in different runs.
Note that it wasn't possible to use `BTreeMap`s because `SocketAddr` doesn't implement `Ord`.
=> Fix indeterminism in tests

src/action.rs, src/event.rs, src/lib.rs, src/node.rs, src/peer_map.rs, src/states/adult.rs, src/states/common/base.rs, src/states/elder/mod.rs, tests/mock_network/utils.rs
Routing doesn't handle these. Simply off-load to vaults.
=> inform vaults (users) about client events

src/chain/bls_emu.rs, src/chain/chain.rs, src/chain/shared_state.rs, src/messages/mod.rs, src/node.rs, tests/mock_network/mod.rs, tests/mock_network/utils.rs
It now takes into account that two emulated-BLS signatures might not be equal according to their `Eq` impl even though they are each created from threshold + 1 signature shares from the same set of nodes. This would possibly not be the case with real BLS.
Also modifies the simultaneous_joining_nodes test to stop polling once relevant conditions are met instead of waiting until all nodes become idle which might not always happen before the max number of poll iterations is exhausted.
=> Fix SectionProofChain comparison

src/states/elder/mod.rs
An error was triggered since commit:
`Remove most of PeerManager` (186772748d42de2957ad97bd61afee354588eca0)
`ERROR 13:05:46.985250496 [routing::states::elder mod.rs:1158] Elder(29937b..(00)) Failed to resolve signature target 0b038a..`
This is stopping newly joining node (elder) from sending direct messages
to other elder in the same section. This happens because the connection
is no longer established before the node is accepted.
My understanding, is Joining node use NodeInfo for sending the
JoinRequest, but this is not setting it up as connected. Before the
Joining node would have send ConnectionRequest and received
ConnectionResponse.
In order to fix that in a way that seem in line with new design, on
JoinRequest, the Elder send back a ConnectionResponse.
This eliminate the Error from …
=> fix/routing: connect joining node on Join

src/peer_map.rs, src/states/adult.rs, src/states/common/base.rs, src/states/elder/mod.rs
Fix easy to reproduce failure in messages_during_churn:
-When connection is dropped by the destination because of split for
example, we get a quic_p2p error and we need to resend the message.
-Unfortunatly, we detected that message as from a client because we
dropped the node information before getting this error.
=> Use a straightforward client detection by storing all client address
in hash map. There may be many client but we can optimize as needed.
Also clean up interface: We were half delegating client handling to
vault and half handling it depending on our state.
=> Always delegate client handling to Vault regardless of state.
Vault can decide what to do as an adult.
Test:
Soak tests pass
Clippy pass
=> fix/routing: correctly identify messages as non client

src/states/elder/mod.rs
The redundant semicolon warning exists on rust nightly, and so the build
fails due to `#![forbid(warnings)]`.
=> chore: remove redundant semicolon to fix build on nightly

Cargo.toml, src/node.rs, src/outbox.rs, src/state_machine.rs, src/states/bootstrapping_peer.rs, src/states/elder/tests.rs, tests/mock_network/utils.rs
This change makes `StateMachine::step` non-blocking and consequently allows `Node` to process routing events in a non-blocking fashion.
As a result of this refactoring, we can now process arbitrary events within the scope of the Routing event loop, allowing us to confine the user code (e.g. Vaults) to the same thread as Routing.
This is achieved by using the `crossbeam_channel::Select` abstraction which allows to register multiple event receivers and listen on all of them at the same time.
Closes https://github.com/maidsafe/safe_vault/issues/878
=> refactor/node: refactor Node API to be used by Vaults

src/chain/chain.rs, src/chain/mod.rs, src/lib.rs, src/mock/quic_p2p/network.rs, src/mock/quic_p2p/tests.rs, src/node.rs, src/states/adult.rs, src/states/bootstrapping_peer.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs, tests/mock_network/accumulate.rs, tests/mock_network/churn.rs, tests/mock_network/drop.rs, tests/mock_network/merge.rs, tests/mock_network/messages.rs, tests/mock_network/mod.rs, tests/mock_network/node_ageing.rs, tests/mock_network/secure_message_delivery.rs, tests/mock_network/utils.rs
The ELDER_SIZE and SAFE_SECTION_SIZE constants will be used in production code; in mock tests, they will be available for setting like `min_section_size` was before.
=> Make elder_size and safe_section_size only configurable with mocks

src/chain/bls_emu.rs, src/chain/chain.rs, src/chain/elders_info.rs, src/chain/member_info.rs, src/chain/mod.rs, src/chain/network_event.rs, src/chain/shared_state.rs, src/id.rs, src/lib.rs, src/messages/direct.rs, src/messages/mod.rs, src/mock/quic_p2p/mod.rs, src/network_service/mod.rs, src/parsec.rs, src/signature_accumulator.rs, src/state_machine.rs, src/states/adult.rs, src/states/bootstrapping_peer.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs, tests/mock_network/secure_message_delivery.rs
Extracted out the first part of https://github.com/maidsafe/routing/pull/1865 together with the first steps of removing `ConnectionRequest/Response`
Part of #1855
=> Remove ConnectionRequest/Response - Part 1

src/node.rs, src/state_machine.rs
This is required to be used by Vaults: the connection info contains the generated certificate which we need to provide when connecting to a Vault.
=> Make the connection info getter public

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/network_event.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs
Closes #1870 
The core of the solution is to ensure
1- We do not process a NeighbourInfo before we processed its parent section.
2 - We do not ignore NeighbourInfo because we voted for a follow up one (still needed for quorum).
Additionally, start isolating the NeighbourInfo Parsec event, as it is not the same as a SectionInfo.
Additional work was not required to fix this issue and can be done as needed or in other PRs.
=> fix out of order neighbour info

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/mod.rs, src/lib.rs, src/states/common/approved.rs, src/states/elder/mod.rs, tests/mock_network/churn.rs
Closes #1849 
This PR contains the work of enable routing checking responsiveness.
The current ChainAccumulator is utilised that each time there is a completed event, the snapshot of members becomes expected voters (with those provided proof removed from the list).
For incoming proofs, the provider will be removed from the list (if has its name).
For the nodes appeart too many times, it will be considered as non-responsive. A vote of `Offline` will then be casted against it.
=> track node responsiveness through votes

src/lib.rs, src/states/adult.rs, src/states/mod.rs, tests/mock_network/utils.rs
This failed with Seed Some([2536718493, 1108160782, 926471325, 1679426090])
on check_section_info_ack with features=mock_base.
The problem is that this did not leave enough iteration for Parsec to
reach consensus on both AddElder and the new SectionInfo.
This timeout does also not make sense in the context of node ageing
since most Adult will stay adults and not transition to Elder.
Test:
Clippy + Soak test + mock_base with seed passing.
=> fix/states: remove timeout for Adult to transition to Elder

src/chain/bls_emu.rs, src/lib.rs, tests/mock_network/accumulate.rs
This reverts the commit 194ae9a7e8ec6efe46b7bdb4a9faa734a92cf18f, which means this re-applies the change to 1/3 DKG threshold.
Closes #1770 again.
=> Re-apply 1/3 DKG threshold

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/mod.rs, src/chain/network_event.rs, src/parsec.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, tests/mock_network/mod.rs
This modifies the way nodes joining and leaving are handled to use the same mechanism as splits - that is, by creating a new Parsec instance.
=> New method of dynamic membership handling

Cargo.toml, src/chain/chain.rs, src/chain/network_event.rs, src/mock/parsec/mod.rs, src/parsec.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, tests/mock_network/mod.rs
This PR start DKG when Online/Offline is consensused, and trigger the SectionInfo vote when the DKG complete.
This also re-enable mock_base testing with real Parsec, as newly added node get the gossip from the parsec instance they were added from, like when they were added as an elder before.
Unit tests are updated.
multiple_joining_nodes is disabled for mock_base because of timeout better solved after other works.
Closes #1774
=> DKG on top of parsec reset

src/chain/bls_emu.rs, src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/elders_info.rs, src/chain/mod.rs, src/chain/proof.rs, src/chain/shared_state.rs, src/id.rs, src/messages/mod.rs, src/node.rs, src/parsec.rs, src/signature_accumulator.rs, src/states/adult.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, tests/mock_network/secure_message_delivery.rs
- Replace member container set with map in `EldersInfo`.
- Implement order traits correctly for `P2pNode`.
- Improve performance by not unnecessarily clone and collect into sets and maps in `EldersInfo` methods. The `churn` tests show a ~10% improvement for me locally on average.
These things were pointed out during the review of #1868
=> Replace member container in `EldersInfo` and fix order trait impl

src/chain/shared_state.rs
Fix aggressive_churn Some([2134840958, 10390792, 1455924021, 536582862]).
AckMessage sent to ourselves was received when one node already purged
the relevant self key from cached keys.
Test:
Verify seed pass.
soak test.
=> fix/chain: extend cached keys to pass churn test

src/node.rs, src/state_machine.rs, src/states/elder/mod.rs
Expose connection information of the elders in our section to the
user library. Vauls for example will use this to give it to a client
wanting to connect to the network (and thus via its section).
Closes #1889
=> Access to the connection info of elders

src/chain/chain.rs, src/chain/member_info.rs, src/chain/shared_state.rs, src/peer_map.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs, tests/mock_network/secure_message_delivery.rs
This is the second part of #1865 and removes most calls to `PeerMap`.
=> Remove ConnectionRequest/Response - Part 2

src/rng.rs, tests/mock_network/utils.rs
`Node` rngs were not properly initialized using `Network`'s global rng resulting in non-repeatable tests.
=> Fix rng initialization in mock network tests not being reproducible

src/chain/chain.rs, src/mock/quic_p2p/node.rs, src/mock/quic_p2p/tests.rs, src/states/elder/mod.rs, src/states/joining_peer.rs
An assumption of the system is that quic_p2p will always return a
success or failed status for a message. However, this was not always
happening.
Ensure it is the case.
Pull in as well https://github.com/maidsafe/routing/pull/1896
=> quic_p2p always return success or failure

src/chain/chain.rs, src/chain/mod.rs, src/node.rs, src/parsec.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, tests/mock_network/churn.rs, tests/mock_network/mod.rs
This PR contains the detailed operation when a ParsecPrune event reached consensus, and the test to confirm it.
The operation utilize the current split approach, so the most part of existing `finalise_prefix_change` handling can be retained.
=> feat/routing: prune parsec as requested

src/chain/chain.rs, src/network_service/mod.rs, src/network_service/sending_targets_cache.rs, src/pause.rs, src/states/adult.rs, src/states/bootstrapping_peer.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs, tests/mock_network/secure_message_delivery.rs
- Move `PeerMap` to `NetworkService` as a prepatory step for Part 3 (#1885) in the connection request/response refactoring. The intention (in Part 3) is to strip down `PeerMap` to only keep track of client `SocketAddr` and mapping certificates to nodes.
Any notion of "connectedness" is set to be deprecated.
- Remove `peer_map` call in `send_parsec_gossip`
- Fix a few minor issues pointed out in the review of #1884
=> Move PeerMap to NetworkService

Cargo.toml, src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/mod.rs, src/chain/network_event.rs, src/error.rs, src/lib.rs, src/parsec.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs
Partially address #1891 
Use DkgResult and BLS keys to sign the next key.
This is incomplete in the sense that we are not yet signing the SectionKeyInfo as we should, but provide the initial setup to continue the work of removing bls_emu
=> Start signing next key with previous BLS key

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/elders_info.rs, src/chain/mod.rs, src/chain/network_event.rs, src/chain/shared_state.rs, src/lib.rs, src/mock/parsec/mod.rs, src/parsec.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs
Closes #1891 
Sign RealSectionKeyInfo, this also force the code & test to provide the BlsPublicKey where needed.
This is an essential part of being able to remove bls_emu.
Note:
- `self.vote_for_section_info(merged_info)?;` can no longer be called as it require a BlsPublicKey for the new section, and we do not have it. Merge is broken already so comment this out. The whole merge code may be removed when needed.
-`our_section_next_bls_keys_sig` was not doing the right thing, as that signature need to be provided by all nodes whether they were participants or not, they will have the BlsPublicKey and need to sign it.
=> Sign RealSectionKeyInfo with BLS key

src/chain/chain.rs, src/chain/shared_state.rs, src/states/elder/mod.rs
The `our_members` container is now pruned only after both post-split `SectionInfo`s are accumulated, not immediately when the new node is added. This fixes issue with parsec gossip being sent only to the subset of the nodes during ongoing split.
Closes #1909
=> Fix incorrect pruning of our_members on split

src/chain/chain.rs, src/states/adult.rs, src/states/elder/mod.rs
Small clean up to support https://github.com/maidsafe/routing/pull/1856 by taking some of the changes from it.
With Node Ageing, not all new adult node will become elders.
The promote_and_demote_elders compute the new elder state based on its
current state regardless of whether a node was added or removed.
For now this keep the same behavior, promoting all Adults to be Elders
immediately.
=> introduce single flow for promoting elders on node add/remove

src/chain/chain.rs, src/chain/shared_state.rs
Consider this situation:
A section `P` splits into `P0` and `P1`. Say `P0` already updates some other section `R` about their knowledge. Then `R` sends a message to `P0`. `P1` might not have fully caught itself to the split so it still thinks its prefix is `P` and so it considers itself in authority of that message. But if the message is proven only for `P0`, then `P1` would not trust it.
The fix is to construct the proof so that it is still trusted by both `P0` and `P1` until `P1` also realizes the split and updates `R` about their knowledge.
Closes #1810
Fixes failure of `aggressive_churn` with `features=mock` and seed `[3801065637, 2093151754, 3731311097, 4215731170]`.
=> Make sure messages are trusted by all nodes during ongoing split

src/chain/chain.rs, src/states/elder/mod.rs
The code preventing disconnection from a node relocated from neighbour to us was buggy because it assumed the node would have the same `PublicId`. Changed to lookup by `SocketAddr` instead.
=> Fix bug in preventing disconnection from nodes relocated to us

src/chain/chain.rs, src/chain/member_info.rs, src/chain/shared_state.rs, src/parsec.rs, src/state_machine.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs
A couple of minor clean up followed by the main bulky commit for demotion.
When full node ageing come into play, things will likely be somewhat different.
Some work taken from https://github.com/maidsafe/routing/pull/1856. This PR should help simplify PR 1856, and also address per-emptively issue that would likely show up.
-clean up parsec map initialization
-respond to boostrap for node we know 
-Introduce demotion stand alone to simplify remaining Node Ageing work.
-Clean up Relocation: Relocated elder see a section without it before relocating.
-Relocating Adults stage may be use to mitigate messages still coming
to relocating node because rest of the network had not caught up (future work).
Changes:
-Never relocate an Elder: MemberState is set to Relocating, and those
are not chosen …
=> Introduce demotion to adult with Relocate clean up

src/chain/chain.rs, src/parsec.rs, src/states/common/approved.rs, src/states/joining_peer.rs, tests/mock_network/churn.rs, tests/mock_network/utils.rs
- The timeout was too low and didn't account for backlogging due to heavy churn.
- When a node is relocating, it will never be rejected from joining the target section, so we need no timeout in that case (currently not even newly joining node can be rejected, but that will change soon so the timeout remains for that case).
- This commit also adds more detailed logging in a couple of places to help debugging.
=> Increase join timeout and use no timeout for relocating nodes

src/messages/mod.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/joining_peer.rs
ConnectionRequest is now mostly unused, only to try to re-establish
a connection with a lost elder. This is the remaining part of the work
to use responsiveness as an alternative to having a live connection.
However, this part of the code is no longer needed at this stage as
there is no need to try to find the connection information since we
already have them.
Test:
clippy + soak test
=> fix/routing: Remove unneeded ConnectionRequest handling

Cargo.toml, src/lib.rs, src/mock/mod.rs, src/mock/quic_p2p/mod.rs
This contains the work of export mock quick-p2p for vault use
=> feat\routing: export mock quic-p2p for vault use

src/pause.rs, src/states/adult.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs
Adults will be long lived with node ageing:
- Pass Hop messages to our Elders as we may have been demoted.
- Process signature accumulation and pass messages to our elders as we may have been demoted.
Note:
We are still keeping messages in our backlog so we can process them our_selves, we may have to vote for something as an elder. We will likely have to clean this up further to avoid stale messages being processed and fail signature check.
=> forward hop messages as an Adult

src/chain/chain.rs, src/chain/config.rs, src/chain/member_info.rs, src/chain/mod.rs, src/chain/shared_state.rs, src/lib.rs, src/node.rs, src/relocation.rs, src/state_machine.rs, src/states/adult.rs, src/states/bootstrapping_peer.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs, tests/mock_network/churn.rs, tests/mock_network/mod.rs, tests/mock_network/node_ageing.rs, tests/mock_network/utils.rs
This PR fixes a bug in the relocation override implementation which could cause a failure in the following scenario:
1. A relocation override is set for nodes in a section
2. A node which is not elder gets relocated from that section, using (and consuming) the relocation override
3. Because that node was not an elder, it does not cause new `SectionInfo` to be voted
4. Another node joins the section and is immediately promoted to elder
5. As it is catching up to the parsec history, it encounters the event that caused the above relocation
6. It processes the relocation, but as it joined later, the relocation overrides are not set on it, so it uses different relocation destination
7. And thus the new node gets out of sync with the rest of the section
The fix is to maintain a map of …
=> Fix relocation overrides

src/event.rs, src/lib.rs, src/states/adult.rs, src/states/elder/mod.rs, src/states/joining_peer.rs, tests/mock_network/churn.rs, tests/mock_network/utils.rs
Couple of commits dealing with the handling of `Event::Connected`, backported from #1929 .
=> Improve `Connected` event handling (backports from 1929)

src/chain/chain.rs, src/messages/direct.rs, src/messages/mod.rs, src/state_machine.rs, src/states/bootstrapping_peer.rs, src/states/elder/mod.rs, src/states/joining_peer.rs, tests/mock_network/churn.rs
Refactor code to allow post - processing events
Refactor code to have EldersInfo in BootstrapResponse::Join
Refactor code to have EldersInfo version in JoinRequest
Ensure new name match the same prefix has relocation destination even if split occur
JoiningPeer update and resend JoinRequest if receive BootstrapResponse::Join with newer info (could be the first responder was lagging, or the section updated).
Resend BootstrapResponse::Join if churn, or if receive JoinRequest that could have been for us in a previous section.
Commit comments have more details.
May address issue #1861 
Test:
Verify the fix address the issue found soak testing PR #1929
=> resend Join bootstrap response if outdated elder version

src/chain/chain.rs, src/chain/shared_state.rs, src/mock/parsec/key_gen.rs, src/mock/parsec/mod.rs, src/mock/parsec/state.rs, src/node.rs, src/relocation.rs, src/states/adult.rs, src/states/bootstrapping_peer.rs, src/states/elder/mod.rs, src/states/joining_peer.rs, tests/mock_network/churn.rs, tests/mock_network/mod.rs, tests/mock_network/node_ageing.rs, tests/mock_network/utils.rs
Backport a number of fixes from #1929 that stand alone.
The main item is always increase age even for infant as that was leading to stall in test otherwise. 
A number of related fixes are also included as well as the fixes necessary for soak test to pass.
Note:
The relocation_in_progress, churn_in_progress and split_in_progress could probably be improved but is left outside of the scope of that PR.
=> backport increase age even for infant from #1929

src/chain/chain.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs
We checked for promotion demotion everytime a churn event occured.
If we have some in the backlog, we risked changing multiple times in
quick sucession.
The new mechanism has multiple benefit:
- Only update elders once if multiple node in churn backlog.
- Clear interaction between the different polling (events, relocation,
backloged churn, and Elder churn).
- Avoid duplication that could break shared state in adult.
- Shorten the flow since promote Demote does not happen as a result
of an other event completing.
Test:
clippy + soak test
=> fix/routing: simplify promotion/demotion and reduce number

src/mock/parsec/mod.rs, src/parsec.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs
Backport some item written in #1929 
Also clean up the new NeighbourInfo resend mechanism so we can eventually use it for all section messages that must result in a consensus, and simplify the resend condition to always as it should only rarely happen and message filter will help.
Note: This is needed on all membership change as one of the new elder may not have received the message and voted for it otherwise (thus malicious elders could stall that event).
=> Resend neighbour info we vote for

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/member_info.rs, src/chain/network_event.rs, src/messages/direct.rs, src/mock/parsec/mod.rs, src/mock/parsec/state.rs, src/mock/quic_p2p/network.rs, src/mock/quic_p2p/tests.rs, src/node.rs, src/parsec.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs, tests/mock_network/accumulate.rs, tests/mock_network/churn.rs, tests/mock_network/messages.rs, tests/mock_network/mod.rs, tests/mock_network/utils.rs
Taking over from https://github.com/maidsafe/routing/pull/1856
Implement part of https://github.com/maidsafe/routing/issues/1835
This implements the logic for promoting and demoting Elders as needed and updates the splitting logic correspondingly.
=> Elder promotion and demotion

src/chain/chain.rs, src/chain/member_info.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs
Avoid code duplication when member change between adults and Elders.
Remove comment about NodeAdded/NodeLost now tracked by https://github.com/maidsafe/routing/issues/1950
Also remove dead code now tracked by https://github.com/maidsafe/routing/issues/1953
=> Clean member change

tests/mock_network/mod.rs
With just 3 elders, if one is paused, the remaining two won't reach consensus on the subsequent `Online` votes and the test fails by exhausting the poll iterations.
=> Fix the pause_and_resume test by increasing elder_size to 4

src/chain/chain.rs, src/chain/elders_info.rs, src/chain/shared_state.rs, src/node.rs, src/states/adult.rs, src/states/common/approved.rs, src/states/elder/mod.rs, tests/mock_network/churn.rs
This PR fixes an accidental disabling of node drops in the churn tests. That uncovered some issues which this PR also fixes.
=> Re-enable drops in churn tests

src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/elders_info.rs, src/chain/mod.rs, src/error.rs, src/lib.rs, tests/mock_network/churn.rs, tests/mock_network/messages.rs
We need to create a valid signature. With an accumulated event, we will
always have threshold + 1 valid signature share. We may have invalid
shares as well that we need to ignore when combining signature to get
a valid signature.
Resolves #1917 
Superseed https://github.com/maidsafe/routing/pull/1921
=> Only combine valid sigs for accumulated events

src/chain/chain.rs, src/states/elder/mod.rs
We need to connect to all our Adults when promoted to detect them
offline as needed.
=> fix/routing: ensure Adults are detected offline.

src/chain/chain.rs, src/node.rs, tests/mock_network/mod.rs, tests/mock_network/utils.rs
SPLIT_BUFFER has no meaning or purpose. When the network is going to split it will, there is no concept of buffer here. 
Also, the indirection of safe_section_size min_section_size and min_split_size has been simplified. When the RT is removed then it will be safe_section_size only
=> Remove SPLIT_BUFFER and safe_section size indirection.

src/chain/chain.rs
Reduce runs in unit test to allow the test to comple in a reasonable time and not timeout
=> routing/refactor 

tests/mock_network/churn.rs
Supersede https://github.com/maidsafe/routing/pull/1954
This PR improves and refactors the churn tests.
- Remove code duplication and increase code reuse
- Extract parameters to allow more configurability of the churn tests
- Make the churn tests more strict 
- Increase the number of iterations to make it more likely that interesting cases are hit
- JP: Avoid recursive split by keeping add balanced.
=> Improve churn tests

src/chain/chain.rs, src/relocation.rs, tests/mock_network/utils.rs
add_connected_nodes_until_split add all the nodes of leaf prefixes, thus
triggering recursive prefix case. Ensure that this split is not delayed
until the next online/offline event.
It is now trivial to handle recursive split in code, so remove the work
arround that was adding more nodes than needed, leaving additional split
yet to occur.
Fix the relocation suppression when adding node to section so it handle
prefix for which only a parent exists.
Test:
Run soak test + clippy.
Verify messages_during_churn [2481487885, 755787713, 2183041345, 3896795195]
does not fail, and still split properly (no relocation occur anymore).
=> fix/routing: handle recursive split and remove test work around.

src/chain/chain.rs, src/error.rs, src/messages/direct.rs, src/states/elder/mod.rs, src/states/elder/tests.rs
Addressing comment https://github.com/maidsafe/routing/pull/1954#discussion_r361638168 from PR merged as https://github.com/maidsafe/routing/pull/1983.
Remove first node special case if not enough elders.
Test:
Update unit test
soak test + clippy
=> fix/routing: treat bootstrapping to any node the same

Cargo.toml, scripts/clippy, src/lib.rs, src/messages/direct.rs, src/messages/mod.rs, src/mock/mod.rs, src/mock/quic_p2p/network.rs, src/mock/quic_p2p/tests.rs, src/network_service/mod.rs, src/node.rs, src/parsec.rs, src/pause.rs, src/rng.rs, src/state_machine.rs, src/states/adult.rs, src/states/bootstrapping_peer.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs, tests/mock_network/mod.rs
This PR simplifies the feature flags to just these two:
- `mock_base`: mock network, mock crypto and mock serialisation
- `mock`: everything from `mock_base` plus mock Parsec.
This PR also cleans up lib.rs by mostly moving some declarations around for better readability.
=> Simplify feature flags

Cargo.toml
has_unpolled_observations returns true if DKG in progress as another
block will come. This ensure our tests do not finish to early.
Test:
Verify fix at commit 7a28ba1000f72189c747a124b88c8d2d0b1dd293.
SEED="[478644160, 3867853398, 3158419497, 3646710916]" cargo test --release --features=mock_base -- simultaneous_joining_nodes_three_section_with_one_ready_to_split
SEED="[4094294122, 3867525292, 959208156, 2472265671]" cargo test --release --features=mock_base -- messages_during_churn
test mock_base + clippy
=> fix/routing: pull latest parsec with has_unpolled_observations for DKG

src/chain/chain.rs, src/states/elder/mod.rs
Closes #1963 .
Also includes a tiny refactoring.
=> Don't suppress parsec prune when relocation is in progress

Cargo.toml, scripts/clippy, src/event.rs, src/lib.rs, src/messages/direct.rs, src/messages/mod.rs, src/mock/quic_p2p/network.rs, src/mock/quic_p2p/tests.rs, src/states/common/base.rs, src/states/elder/mod.rs, tests/mock_network/utils.rs, tests/mock_network_tests.rs
Some of these should be re-applied together with fix with safe_vault if needed.
Take some commits from https://github.com/maidsafe/routing/pull/1994
Test:
Verify safe_vault test pass with small modification to cargo.toml
=> Revert some changes to allow safe_vault test to pass

src/event.rs, src/state_machine.rs, src/states/adult.rs, src/states/elder/mod.rs, src/states/joining_peer.rs, src/timer.rs, tests/mock_network/utils.rs, tests/mock_network_tests.rs
Clean up timer to allow remove the incorrect call to `self.routing_node.borrow_mut().poll();` from safe_vault.
Test:
Verify test pass without that call using new routing.
=> clean up timer to avoid work arround in safe_vault

src/states/adult.rs, src/states/elder/mod.rs, src/states/joining_peer.rs
Fix aggressive_churn: [1221425541, 378878981, 107272102, 3204539950] at
dc2abe182b4eadcbd13f67c5e6c4dcb4f5ee59e8.
Address issue introduced with #1993: Ensure we filter out all completed
events.
Also improve logs for debuging.
Test:
Verify the seed is fixed.
soak test + clippy
=> fix/routing: avoid re-voting for completed event

Cargo.toml, src/chain/chain.rs, src/chain/network_event.rs, src/event.rs, src/states/common/approved.rs, src/states/elder/mod.rs, tests/mock_network/churn.rs, tests/mock_network/mod.rs, tests/mock_network/utils.rs
Closes #1950
From a vault perspective, things like ElderChanged with a set of new
elders is likely to be more useful than individual event in sequence.
We are not really using these events in tests, and they really mean
Elder Promoted/Demoted, so remove these event.
Test:
clippy + tests.
=> fix/routing: remove uneeded NodeLost/NodeAdded

src/action.rs, src/chain/chain.rs, src/chain/shared_state.rs, src/error.rs, src/event.rs, src/lib.rs, src/location.rs, src/messages/direct.rs, src/messages/mod.rs, src/mock/env.rs, src/node.rs, src/signature_accumulator.rs, src/state_machine.rs, src/states/adult/mod.rs, src/states/adult/tests.rs, src/states/bootstrapping_peer.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/joining_peer.rs, tests/mock_network/accumulate.rs, tests/mock_network/churn.rs, tests/mock_network/messages.rs, tests/mock_network/secure_message_delivery.rs, tests/mock_network/utils.rs
Renamed Authority to Location. This is the next phase of cleanup and does appear to make more
locial sense when reading the code. It is likely Authority will make a come back though, but as
an actual authority that we can query for validity. Desing considerations though on whether
Authority will be src dst or content. There is reasonable argument that Authority should be for
whole message.
=> Authority -> Location

src/messages/mod.rs, src/routing_message_filter.rs, src/states/adult/mod.rs, src/states/adult/tests.rs, src/states/bootstrapping_peer.rs, src/states/common/base.rs, src/states/common/mod.rs, src/states/elder/mod.rs, src/states/joining_peer.rs, tests/mock_network/secure_message_delivery.rs
Partially addresses #2010 
Closes #2011 
Avoid throwing away the serialized data we get from quic_p2p, and re-use it for filtering and for re-sending the Hop message.
Building on this work, we should avoid de-serializing the full message when all we need is the destination if we are not part of the destination authority.
We can probably also futher clean up the code following this change, in particular it is not clear we still need the HopMessage type.
=> Avoid unecessary serialize for Hop messages

src/lib.rs, src/node.rs, src/states/common/base.rs, tests/mock_network/accumulate.rs, tests/mock_network/churn.rs, tests/mock_network/drop.rs, tests/mock_network/messages.rs, tests/mock_network/mod.rs, tests/mock_network/utils.rs
To prevent the confusion from the event types naming (`routing::Client`), we export the event module as a whole instead (`routing::event::Client`).
=> refactor/events: make event module public

src/chain/chain.rs, src/chain/mod.rs, src/chain/shared_state.rs, src/lib.rs, src/messages/mod.rs, src/relocation.rs, src/states/adult/mod.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/joining_peer.rs, tests/mock_network/secure_message_delivery.rs
This PR fixes two failures:
1. When we are recently joined node and we have a backlogged message that we received while still in `JoiningPeer` state, we must forward the message to our elders if we can't handle it ourselves instead of ignoring it. This prevents losing `NeighbourInfo` votes (among possibly other things)
2. When we are elder and we receive a message whose proof is too new for us, we must not fail but instead forward the message to the other elders. This is because we've already been demoted, we just haven't catched up to it yet.
=> Fix hop message handling

src/messages/mod.rs, src/states/adult/mod.rs, src/states/adult/tests.rs, src/states/bootstrapping_peer.rs, src/states/common/base.rs, src/states/common/mod.rs, src/states/elder/mod.rs, src/states/joining_peer.rs
Closes #2010 
- Partial de-serialization of Hop message (find it is `Hop`, get `dst`).
- Use tuple serialization for SigneRoutingMessage to ease partial de-serialization.
- Use hash for logging/tracing with a log at the beginning with the routing message and hash.
=> Partial deserialize for hop messages

src/chain/chain.rs, src/chain/mod.rs, src/chain/shared_state.rs, src/lib.rs, src/messages/mod.rs, src/node.rs, src/relocation.rs, src/signature_accumulator.rs, src/states/elder/tests.rs, tests/mock_network/secure_message_delivery.rs
Closes #1752 
We should only validate trust when we have the root of trust:
The root of trust bls::PublicKey is no longer part of the Hop message from a Section.
For most message the security_metadata will now only be a Prefix + version(u64).
To validate the message we must find the key we trust and either use it to validate a new
key to trust, or the message itself.
=> Remove tusted key from Hop messages

src/chain/chain.rs, src/chain/network_event.rs, src/chain/shared_state.rs, src/messages/mod.rs, src/relocation.rs, src/states/adult/mod.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/elder/tests.rs, src/states/joining_peer.rs
- If we are a newly joining node, we don't have any trusted keys so we cannot fully verify the message. Instead we only check that the proof and the message signature are valid.
- If we are relocating node, we carry the trusted keys from our previous section into the `JoiningPeer` state and use that to fully verify the message
Closes #2022 .
=> Verify NodeApproval message as JoiningPeer

Cargo.toml, src/rng.rs
A new version exists for tmp-ed25519, selected when doing upgrade.
It uses a new version of rand.
Test:
clippy + test
=> fix/rng: add compatibility for rand 0.7 for tmp-ed25519 v1.0.0-pre.3

src/chain/chain.rs, src/chain/network_event.rs, src/messages/direct.rs, src/messages/mod.rs, src/relocation.rs, src/state_machine.rs, src/states/adult/mod.rs, src/states/bootstrapping_peer.rs, src/states/common/approved.rs, src/states/elder/mod.rs, src/states/joining_peer.rs
With GenesisUpdate, we can now send a SignedRoutingMessage to one of
our members, by directly sending it the direct message MessageSignature.
The node accumulate it at reception and process it when enough signature
is received. This remove the need to sign the message before going
through Parsec.
Test:
soak + clippy
=> fix/routing: use same mechanism for Relocate as GenesisUpdate

Cargo.toml, src/event.rs, src/lib.rs, src/network_service/mod.rs, src/node.rs, src/state_machine.rs, src/states/bootstrapping_peer.rs, src/states/common/base.rs, src/states/elder/tests.rs, src/states/test_utils.rs, tests/mock_network/utils.rs
Depends on https://github.com/maidsafe/quic-p2p/pull/95
Closes https://github.com/maidsafe/routing/issues/2039
This allow to provide user, safe_vault with a receiver for quic_p2p
client events directly.
This will avoid having routing mediating between quic-p2p and vaults for
client events.
=> pull quic-p2p with separate channel for client and node

Cargo.toml
Fix the failure occurring in the multi-threaded tokio runtime
=> Update quic-p2p dependency

src/states/elder/mod.rs
A lagging node might not recognize a signature sender but we still need to process it, otherwise the message might not get accumulated. This is a quick and dirty fix which should be revised at some point and audited for potential security implications.
=> Accept message signatures from unknown senders

Cargo.toml, examples/minimal.rs, src/chain/chain.rs, src/chain/chain_accumulator.rs, src/chain/shared_state.rs, src/event.rs, src/macros.rs, src/messages/accumulating_message.rs, src/network_service/sending_targets_cache.rs, src/parsec.rs, src/states/common/approved.rs, src/states/common/base.rs, src/states/elder/mod.rs, src/states/joining_peer.rs, tests/mock_network/utils.rs
=> Add minimal example

src/chain/chain.rs, src/chain/shared_state.rs, src/lib.rs, src/log_utils.rs, src/messages/with_bytes.rs, src/node.rs, src/parsec.rs, src/signature_accumulator.rs, src/state_machine.rs, src/states/approved_peer/mod.rs, src/states/approved_peer/tests/adult.rs, src/states/common/base.rs, src/states/joining_peer.rs, src/utils.rs, tests/mock_network/churn.rs, tests/mock_network/messages.rs, tests/mock_network/mod.rs, tests/mock_network/node_ageing.rs, tests/mock_network/utils.rs
Followup to #2072. Changes start at the"Implement thread-local log identifier" commit.
When running the integration tests, it's very useful to be able to tell from the log output which node each log line belongs to. To achieve this, we prefix each log line with a short identifier of the node. It looks like this:
```
Elder(2d390f..(001))
```
The way this was implemented before this PR was to have a `Display` impl in each node state which produces the identifier and then manually output `self` in every log statement:
```rust
debug!("{} - handle SectionInfo: {:?}", self, info)
``` 
This works, but has several issues:
- works only if `self` is a node state. If we need to log inside one of the other structs, we need to capture the ident before and pass it explicitly:
```rust
let log_ident = …
```
=> Improve log identifier

src/chain/chain.rs, src/chain/member_info.rs, src/chain/shared_state.rs, src/node/mod.rs, src/node/stage/approved.rs, src/xor_space/prefix.rs, tests/mock_network/accumulate.rs, tests/mock_network/churn.rs, tests/mock_network/messages.rs, tests/mock_network/mod.rs, tests/mock_network/node_ageing.rs, tests/mock_network/secure_message_delivery.rs, tests/mock_network/utils.rs, tests/mock_network_tests.rs
This PR makes infants different from adults in these two ways:
1. Infant joining or leaving a section no longer causes ageing of the other section nodes
2. Infants are not taken into account when deciding splits
This change makes the network more resilient against [sybil attacks](https://en.wikipedia.org/wiki/Sybil_attack) because it makes it much more difficult for an attacker to attempt to take over a section by spawning large number of nodes under their control. 
The bulk of this PR however is in the test code, namely in the utilities to trigger splits. This now requires more work as it's no longer sufficient to just add new nodes until the section splits.
This PR also contains two seemingly unrelated changes:
1. It fixes a bug that was probably introduced in one of the recent PRs …
=> Treat infants differently from adults

src/message_filter.rs, src/mock/env.rs, src/mock/parsec/mod.rs, src/node/mod.rs, src/node/stage/approved.rs, src/node/stage/joining.rs, src/node/tests/bootstrapping.rs, src/parsec.rs, src/relocation.rs, tests/mock_network/accumulate.rs, tests/mock_network/churn.rs, tests/mock_network/drop.rs, tests/mock_network/messages.rs, tests/mock_network/mod.rs, tests/mock_network/node_ageing.rs, tests/mock_network/secure_message_delivery.rs, tests/mock_network/utils.rs
This PR changes the testing strategy. Instead of using `poll_and_resend` which kept polling the network until some mythical "idle" state, we now have `poll_until` where the termination condition is specified explicitly. This condition differs from test to test - for example: "poll until node joined", "poll until node becomes elder", "poll until section splits", "poll until a message gets delivered", and so on.
Also the `verify_section_invariants_between_nodes` function was removed because it was based on unrealistic assumptions that all the nodes in the network can ever get to the same state at the same time. Instead of this, we now check only that the nodes got to a given state at some point, but never that they all are in it at the same time.
These changes uncovered a bug in the …
=> Test improvements

src/chain/chain.rs, src/chain/member_info.rs, tests/mock_network/node_ageing.rs
This PR changes the node ageing logic so during the network startup, all churn events cause age increments. 
Partially addresses #2078
=> Node ageing during network startup

src/node/stage/approved.rs
When relocating an elder, we first demote them to adult, then wait for a "relocation cool-down period" and only then send them the `Relocate` message. This makes it very unlikely that they would still see themselves as elder by the time they receive it. It's not impossible however and when it happens, the node must still proceed with the relocation because it must always obey section decisions. However, we weren't doing it and so this commit fixes it.
=> handle Relocate message also as elder

src/macros.rs, src/node/mod.rs, src/node/stage/approved.rs
Messages for `DstLocation::Section` or `DstLocation::Prefix` are only meant to be handled by elders and could fail validation if attempted to be handled by non-elder.
Also use the log ident in the panic branch of the `log_or_panic` macro.
=> only handle UserMessage as non-elder if addressed directly to us

examples/minimal.rs, src/event.rs, src/node/mod.rs, src/node/stage/approved.rs, src/section/section_members.rs, src/section/shared_state.rs, tests/mock_network/utils.rs
- Add method that returns the current section adults sorted by distance to a given name (Closes #2092)
- Add events raised when a node joins and leaves the section (Closes #2093)
- Add method that returns the current BLS secret key share (Closes #2094)
=> API enhancements

Cargo.toml, src/core.rs, src/messages/with_bytes.rs, src/node/tests/bootstrapping.rs, src/node/tests/elder.rs, src/transport/mod.rs
This PR also updates the versions of bytes, crossbeam-channel and
parsec
=> Update transport module and use latest quic-p2p

src/consensus/event_accumulator.rs, src/consensus/genesis_prefix_info.rs, src/consensus/parsec.rs, src/core.rs, src/location.rs, src/messages/mod.rs, src/messages/src_authority.rs, src/messages/variant.rs, src/messages/with_bytes.rs, src/node/mod.rs, src/node/stage/approved.rs, src/node/stage/bootstrapping.rs, src/node/stage/joining.rs, src/node/tests/adult.rs, src/node/tests/elder.rs, src/node/tests/utils.rs, src/relocation.rs, src/section/elders_info.rs, src/section/member_info.rs, src/section/section_map.rs, src/section/section_proof_chain.rs, src/section/shared_state.rs, src/signature_accumulator.rs, src/transport/mod.rs, tests/mock_network/secure_message_delivery.rs
This PR introduces the distinction between untrusted and unknown messages and implement their handling logic:
- **untrusted** message is a message which is otherwise valid but whose proof cannot be trusted by the recipient because none of the keys in it is known by them
- **unknown** message is a message that cannot be handled by the recipient in its present state. For example a message is meant to be handled by elders but the recipient is adult or infant.
When receiving untrusted message from section X, the node will wrap it in `Variant::BouncedUntrustedMessage`, set the `dst_key` field to the latest known key of X and send it back to X. Then X will extend the proof so that it starts at the given `dst_key` and send the message back.
When receiving unknown message, the handling differs by …
=> Untrusted and unknown messages handling

.github/workflows/pr.yml
We have had a couple of unexplained CI failures recently and would
like to rule out low disk space being the cause.
=> chore(ci): Print CI machine disk space stats on failure

Cargo.toml, src/node/stage/approved.rs
The previous broadcasting DKG messages by send_routing_message
will send DKG messages to elders multiple times un-necessarily.
Also could send to non-participants elder during split.
This commit reduce the duplication of messages by sending to
participants directly. Also fixed a bug that DKG messages between
two non-elder participants not get transmitted previously.
=> fix/approved: sending DKG message to the participants directly

src/consensus/event_accumulator.rs, src/consensus/mod.rs, src/consensus/network_event.rs, src/consensus/parsec.rs, src/mock/parsec/mod.rs, src/node/stage/approved.rs, src/node/tests/elder.rs, src/section/shared_state.rs
This PR removes the logic around handling of the `Genesis` parsec event which isn't needed now we have the `Promote` message. This should have been part of the PR to address https://github.com/maidsafe/routing/issues/2126, but it must have been missed. 
Also remove the explicit gossip peer adding which isn't needed either, because now only elders participate in parsec gossip.
=> Remove Genesis event handling

src/node/stage/approved.rs, src/section/section_map.rs
also only vote their_knowledge for sibling section when being a
newly promoted elder during split
=> fix/approved: remove unnessary send_neighbour

tests/mock_network/mod.rs
Occasionally, CI encounters `Over Buffer` issue.
It's noticed that each time such error happens, the `sibling_knowledge_update_after_split` test is running over time.
It turned out that test is the only test running with 8 elders (normally are 4) AND multiple sections.
=> fix/testing: reduce memory usage for integration tests

src/node/mod.rs, src/node/stage/approved.rs, src/node/tests/adult.rs, src/node/tests/elder.rs, src/section/shared_state.rs
When creating the new `SharedState` (on `EldersUpdate` or `NodeApproval`), we incorrectly used the previous section key instead of the latest one for the section chain. This made every `EldersUpdate` message bounce back as untrusted.
=> Fix incorrect section key assigned to non-elders

src/consensus/dkg.rs, src/node/stage/approved.rs
After a DKG completion, routing will carry out votes of OurKey and
SectionInfo. Only after these votes got consensused, will then the
section_key_index got updated. So, a routing level check of
section_index will not be enough within the gap. i.e. any DKG message
received during the gap will cause a new round of DKG for the same.
Hence the info of completed highest section_key_index shall be recorded
and checked against to cover the gap.
=> fix/dkg_voter: record completed DKG section_key_index

Cargo.toml, src/consensus/mod.rs
Must only be merged once PR [here](https://github.com/maidsafe/safe-network-signature-aggregator/pull/7) updating signature aggregator crate name has been merged, and that repo's name has been updated.
=> chore(deps): use updated crate name

src/consensus/dkg.rs, src/node/stage/approved.rs
Handle DKGOldElders message only after accumulating quorum of them.
To avoid vulnerable to malice.
Close https://github.com/maidsafe/routing/issues/2173
=> fix/dkg: Accumulate DKGOldElders messages

Cargo.toml
Must first publish the [bls_dkg crate](https://crates.io/crates/bls_dkg) before merging this PR 
UPDATE: bls_dkg now published so was able to run CI - clippy errors are found, though they seem unrelated to anything changed in this PR. Attempted to resolve but suggested fixes are leading to further clippy errors so IMO it's best to leave a fix for a Rust dev working on this crate.
The 3 `Test` CI jobs have passed - merging
=> chore(deps): use updated bls_dkg crate

Cargo.toml, examples/minimal.rs, src/consensus/dkg.rs, src/consensus/mod.rs, src/consensus/vote.rs, src/event.rs, src/lib.rs, src/messages/message_accumulator.rs, src/messages/variant.rs, src/node/mod.rs, src/node/stage/approved.rs, src/node/stage/bootstrapping.rs, src/node/stage/joining.rs, src/node/tests/elder.rs, src/section/elders_info.rs, src/section/member_info.rs, src/section/mod.rs, src/section/section_keys.rs, src/section/section_members.rs, src/section/section_proof_chain.rs, src/section/section_update_barrier.rs, src/section/shared_state.rs, tests/mock_network/accumulate.rs, tests/mock_network/utils.rs
This PR refactors and modifies the DKG module with the aim of fixing bugs in it and making it simpler. The new flow goes somehow like this:
1. On every churn, the current elders propose the new elders as the `elder_size` oldest nodes of the section.
2. If the proposed elders are the same as current elders, we are done
3. Otherwise they send `DKGStart` message (signed with their BLS key share) to the proposed elders (also called DKG paricipants)
4.When the `DKGStart` message accumulates, the participant initiates a DKG session and starts exchanging DKG messages with the other participants
5. When the DKG session completes successfully or fails, the participants send `DKGResult` message carrying the result to the current elders
6. The current elders accumulate this message and when they get …
=> Fix some bugs around DKG and relocation

.github/workflows/rustdoc.yml
Why is this needed? We are having to add a custom index.html in
the root gh-pages branch, pointing to the index.html in a
subfolder. Without `keep_files: true` all existing files are
removed - we need this set to true so the index.html file remains.
Note that `force_orphan: true` and `keep_files: true` are not
compatible in the action v3, but will be in v4, hence the need to
delete `force_orphan: true`.
=> docs(gh-pages): update CI to keep existing gh-pages branch content

src/consensus/dkg.rs, src/consensus/proven.rs, src/consensus/vote.rs, src/lib.rs, src/location.rs, src/messages/hash.rs, src/messages/mod.rs, src/messages/plain_message.rs, src/messages/src_authority.rs, src/messages/variant.rs, src/network/mod.rs, src/network/prefix_map.rs, src/peer.rs, src/section/member_info.rs, src/section/mod.rs, src/section/section_peers.rs, src/section/section_proof_chain.rs
switching to the formal setup as stated at https://serde.rs/derive.html
=> fix: no longer use serde macro derive

.github/workflows/pr.yml, src/consensus/dkg.rs, src/consensus/mod.rs, src/routing/approved.rs, src/routing/command.rs, src/routing/mod.rs, src/routing/stage.rs
This is a part of the effort to simplify the `Approved` struct by extracting parts of it into separate self-contained modules.
=> Extract most of the DKG logic out of Approved and into DkgVoter + adds some DKG tests

Cargo.toml, src/consensus/dkg.rs, src/consensus/mod.rs, src/lib.rs, src/node.rs, src/peer.rs, src/routing/approved.rs, src/routing/bootstrap.rs, src/routing/mod.rs, src/routing/stage.rs, tests/bootstrap.rs
- Add proptest for DKG
- Remove DKG bounce. The issue it was supposed to fix was not reproducible in tests and the implementation was problematic. For example, it only handled the initial DKG after a node joins, but not the subsequent DKGs. Fixing that was tricky, because it's difficult to tell whether an incoming DKG message for an unknown session should be bounced because the session is only about to be created, or ignored because the session was already discarded. There might be ways to fix this, but it doesn't seem worth the complexity at the moment. We might want to revisit this in a different PR if necessary.
- Add bootstrap message backlog - cache unknown messages during the bootstrap phase, then process them after being bootstrapped.
- Prevent scheduled timeouts from keeping …
=> Startup tweaks

src/routing/approved.rs, src/routing/tests/mod.rs, src/section/member_info.rs
As discussed, rejoin node with same name will be immediately relocated with half of original age.
Close https://github.com/maidsafe/sn_routing/issues/2214
=> feat: allow rejoin with same name

src/consensus/vote.rs, src/routing/approved.rs, src/routing/command.rs, src/routing/mod.rs, src/routing/stage.rs
This contains the work to allow node to tell routing whether new node shall be accepted.
This is also being a solution to prevent sybil attack.
=> feat: joins_allowed to toggle accept new node or not

src/error.rs, src/routing/mod.rs, src/section/section_keys.rs
BREAKING CHANGE:
- remove `Routing::secret_key_share` (use `Routing::sign_with_secret_key_share` instead).
- Rename `Error::InvalidElderDkgResult` to `Error::MissingSecretKeyShare`
- `Routing::public_key_set` and `Routing::our_index` now return `MissingSecretKeyShare` instead of `InvalidState` on error.
=> Do not expose BLS secret key share

Cargo.toml, src/messages/mod.rs, src/messages/variant.rs, src/relocation.rs, src/routing/approved.rs, src/routing/bootstrap.rs, src/routing/mod.rs, src/routing/tests/mod.rs, src/section/mod.rs, src/section/section_peers.rs, tests/bootstrap.rs, tests/drop.rs, tests/messages.rs
This PR contains the work of using resource_proofing to challenge the joining node so that any joined node can now be considered as an adult immediately.
=> feat: carry out resource proofing during bootstrap

Cargo.toml, examples/minimal.rs, src/lib.rs, src/network/stats.rs, src/routing/stage.rs, tests/drop.rs, tests/utils/mod.rs
Use [`tracing`](https://docs.rs/tracing/0.1.22/tracing/) for logging instead of the `log` crate. This allows us to use structured logging and spans. There should be no change necessary on the consumers of this crate as `tracing` is compatible with `log`.
=> Log with the tracing crate

src/routing/approved.rs, src/routing/tests/mod.rs, src/section/section_peers.rs, tests/bootstrap.rs
- Do not require resource proof from relocated nodes
- Add test for handling join request from relocated node
- Fix incorrect test assertion that a newly joined node is never instantly relocated
- Forward `ResourceChallenge` to the bootstrap task (not necessary, but good future proofing)
- Refactor `handle_join_request` by extracting the resource proof logic into separate methods
- Fix a bug with section update being permanently blocked when there is only one elder and he wants to demote himself and promote another single node
- Fix a bug with promotion being blocked when all the current elders are being relocated and there is fewer than `ELDER_SIZE` other joined nodes in the section
- Fix the `test_startup_section_bootstrapping` test by taking relocations into account.
=> Do not require resource proof from relocated nodes + bugfixes

src/consensus/dkg.rs, src/consensus/mod.rs, src/consensus/vote.rs, src/crypto.rs, src/messages/mod.rs, src/messages/variant.rs, src/node.rs, src/routing/approved.rs, src/routing/command.rs, src/routing/mod.rs, src/routing/split_barrier.rs, src/routing/stage.rs, src/routing/update_barrier.rs, src/section/mod.rs, src/section/section_keys.rs
This PR refactors the DKG and its outcome handling in order to simplify the codebase:
- ~~DKG failures are no longer reported to the current elders. If a DKG participant detects a failure, it automatically restarts the DKG~~
- DKG failures are still reported, but differently - they are now accumulated by the DKG participants themselves and only when they accumulate a majority are they sent to the current elders. The elders validate it and restart the DKG if necessary. This makes things simpler because we don't need to track potentially multiple DKG sessions or deal with the invalidation of the accumulators. It also offloads the work to the nodes that benefit from it, which seems neater.
- The separate DKG result accumulator is gone. We now use the regular vote accumulator.
- So there is …
=> Refactor section update

.github/workflows/pr.yml, Cargo.toml, tests/messages.rs
This fetches a shared deny.toml from the QA repo before running the cargo deny GH Action.
=> chore(ci): add cargo deny check to CI

src/routing/mod.rs
Run cargo intraconv to change markdown link to intra-doc link.
Originally this PR also added `cargo deadlinks` scan to CI but there were several broken doc links from external deps so would have been too much noise - removed that commit.
=> Run cargo intraconv to change markdown link to intra-doc link

examples/stress.rs, src/consensus/dkg.rs, src/error.rs, src/location.rs, src/messages/mod.rs, src/messages/src_authority.rs, src/messages/variant.rs, src/relocation.rs, src/routing/approved.rs, src/routing/bootstrap.rs, src/routing/tests/mod.rs, src/section/mod.rs, src/section/section_keys.rs, src/section/section_proof_chain.rs
Various fixes and tweaks that came up during stress testing. Most notably:
- Fix `Sync` messages not being sent when split and demote happen at the same time
- Add support for multiple concurrent DKG sessions (fixes a situation where a DKG neither completes nor fails)
- Fix `update_state` failing when a node is elder but doesn't yet have its secret key share
- Prevent more than one relocation of the same node at the same time
=> Various churn related fixes

src/lib.rs, src/network/mod.rs
`deny` can be overriden with `allow`, unlike `forbid`. This allows us to `allow` some warnings on a case-by-case basis which is especially useful in macros. Without this, some macros from other crates caused compilation errors on nightly, however it's possible it would eventually affect stable as well.
=> chore: use deny(warnings) instead of forbid(warnings)

.github/workflows/master.yml, .github/workflows/pr.yml
Removed previously as it seemed to be causing CI failures - no longer able to replicate.
=> chore(ci): readd macOS cache generation to CI

examples/minimal.rs, examples/stress.rs, src/event.rs, src/lib.rs, src/routing/approved.rs, src/routing/mod.rs, tests/bootstrap.rs, tests/drop.rs, tests/messages.rs, tests/utils/mod.rs
- Removes `PromotedToAdult` and `Demoted` variants of `Event` enum.
- Adds `NodeElderChange` enum.
- Adds the flag `self_status_change` to `EldersChanged` variant, indicating whether the node got promoted, demoted or did not change.
=> refactor(event): move promoted/demoted to elderschanged

.github/workflows/semgrep.yml
Shouldn't need to specify config in semgrep.yml - replaced API key at same time as this change as perhaps this is why it was failing before.
=> chore(ci): update semgrep ci check to use config from semgrep.dev

Cargo.toml
BREAKING CHANGE: new Sequence data-type doesn't allow Policy mutations.
=> chore(data-types): upgrading data-types to v0.16.0 and sn_messaging to v8.0.0

examples/minimal.rs, src/event.rs, src/routing/approved.rs
BREAKING CHANGE: remove `Event::PromotedToAdult` and the `startup_relocation` field of `Event::MemberJoined`, both parts of public API.
=> feat!: remove unused events and event properties

examples/minimal.rs, examples/stress.rs, src/consensus/dkg.rs, src/event.rs, src/messages/variant.rs, src/routing/approved.rs, src/routing/command.rs, src/routing/mod.rs, src/routing/stage.rs, src/routing/tests/mod.rs, tests/messages.rs
BREAKING CHANGE: Added `additional_proof_chain_key` parameter to  `Routing::send_message`, added `proof_chain` field to `Event::MessageReceived`.
=> feat!: support adding additional proof chain keys to user messages

src/delivery_group.rs, src/messages/mod.rs, src/messages/variant.rs, src/relocation.rs, src/routing/approved.rs, src/routing/bootstrap.rs, src/routing/lazy_messaging.rs, src/routing/split_barrier.rs, src/routing/stage.rs, src/routing/tests/mod.rs, src/section/mod.rs, src/section/section_chain.rs
Every node now always has the genesis key. This means we can now always provide valid proof chain for anyone because if all else fails we can always fall back to sending the full section chain.
Closes #2372.
=> feat: keep the genesis key and use it for fallback proofs

src/event.rs, src/routing/core.rs
BREAKING CHANGE: The `proof_chain` field of `Event::MessageReceived` is now `Option`.
=> fix!: adults not able to send non-aggregated messages

src/peer.rs
BREAKING CHANGE: new version of routing
- This commit is mainly to cover the change of Peer. Which used by
a public struct but won't trigger the version update automatically.
=> chore!: breaking version change

src/routing/comm.rs
Using the same endpoint to check reachability will result in a false positive even when a node is not externally reachable. This fixes this by keeping a separate endpoint to verify external reachability of new peers.
﻿
=> Use separate endpoint to test reachability

src/error.rs, src/routing/comm.rs, src/routing/core.rs, src/routing/dispatcher.rs
change return of `send` to reflect the logic of delivery_group_size `delivery_group_size` or not
~~BREAKING CHANGE: return type of `Comm::send` is now `Result<SendStatus>`~~
=> refactor(comm): change return of `send` to reflect the logic of delivery_group_size

examples/minimal.rs, examples/stress.rs, src/event.rs, src/routing/core/messaging/handling/mod.rs, src/routing/core/mod.rs, src/routing/mod.rs, src/routing/tests/mod.rs, tests/drop.rs
- Removes the `sibling_elders: Option<Elders>` field from `EldersChanged`.
- Increases event data granularity by detailing the actual changes.
- Same granularity applied to `AdultsChanged`.
BREAKING CHANGE: `Event` enum variants changed and new added.
=> refactor(event): add SectionSplit, increase granularity

examples/stress.rs
This is required due the switching from mspc::unboundedSender to
mspc::Sender. With the switch, furture send without await will
be ignored.
=> fix: await on future for the stress test

.github/workflows/pr.yml, Cargo.toml, src/cache/mod.rs
- e8ed35b8 **docs(cache): Populate empty doc comments**
- a67164c7 **refactor(cache): Avoid suppressing lints**
- b5dab42c **fix(cache): Prevent exposing expired values from Cache::set**
`Cache::set` was not testing the removed item's expiry, meaning expired
values could be returned.
- 93de8c87 **ci: Install cargo-udeps without --locked**
This works around a compilation issue caused by
https://github.com/rust-lang/rust/issues/85574. A more permanent fix may
come in future.
- 37fc9daf **chore: Remove unused dashmap dependency**
This has been unused since #2556.
=> Add documentation to Cache and fix a possible bug

src/cache/item.rs, src/routing/comm.rs, src/routing/core/connectivity.rs, src/routing/tests/mod.rs
- try_send on existing connection or create new connection and send
logic has been moved to qp2p
- don't create a new connection when trying to send back a message via
an existing connection (for clients)
=> refactor(comm): use update qp2p API logic
