- Cargo.toml
- README.md
- appveyor.yml
Appveyor configuration updated to take sodiumoxide lib from bin/ folder
Cargo.toml file updated to invoke sodiumoxide dependency from original source.
> Appveyor integration

- README.md
- src/bootstrap.rs
Updated the README, also removed the unwrap from table creation statement.
> SQLite Readme updated

- Cargo.toml
- src/bootstrap.rs
CRUD test integrated for Bootstrap. Serialization test added for Contact.
> Bootstrap crud test integrated. Serialization test added for Contact.

- src/bootstrap.rs
time crate used instead of std::time
> Bootstrap FIXME resolved

- src/accumulator.rs
- src/routing_table.rs
Left one warning untouched, as it would be less trivial change - outwidth my current scope.  Just quick PR to get routing set up and scan through the project
> Resolve all but one warning

- src/types.rs
WARNING: test is a direct copy, and Will be replaced in new commit
> Introduce Pmid struct in routing

- src/sentinel.rs
- src/types.rs
Partial setup, but builds an has empty test;
Further extends Pmid and signs messages
> Sentinel tests

- src/sentinel.rs
super got lost somewhere along the git-way
> Fix lost use super::*;

- src/sentinel.rs
Addresses failing assert where Sentinel would call to send GetGroupKey/GetClientKey on every message
> Addresses failing assert (1/2)

- src/accumulator.rs
Additional tests for Accumulator written during debugging of Sentinel, all tests pass
> Added tests to assure that quorum is reached.

- src/sentinel.rs
> Minor style and comments

- src/lib.rs
- src/routing_client.rs
> Revert "link routing_client into client"

- src/accumulator.rs
- src/bootstrap.rs
- src/lib.rs
- src/message_header.rs
- src/messages.rs
- src/messages/connect.rs
- src/messages/connect_response.rs
- src/messages/find_group.rs
- src/messages/find_group_response.rs
- src/messages/get_client_key.rs
- src/messages/get_client_key_response.rs
- src/messages/get_data.rs
- src/messages/get_data_response.rs
- src/messages/get_group_key.rs
- src/messages/get_group_key_response.rs
- src/messages/post.rs
- src/messages/put_data.rs
- src/messages/put_data_response.rs
- src/routing_client.rs
- src/routing_node.rs
- src/routing_table.rs
- src/sentinel.rs
- src/types.rs
I didn't go through every file this time, because I got bored :wink: 
This code overall looks good. There's some small things that could be better, but I'd say that in general, you're on the right track.
> more style fixes

- src/routing_table.rs
- src/types.rs
This function will be used [here](https://github.com/dirvine/maidsafe_vault/blob/master/src/vault.rs#L55). Hopefully I didn't misunderstand how this value is calculated.
EDIT:
It will be used in the lines below inside of the function, not at that line obviously.
> Adding DhtId::from_data

- Cargo.toml
- src/name_type.rs
For find and get group key responses with tests
> Merge algo

- src/sentinel.rs
As part of getting to know the sentinel code.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/106)
> Mostly removing dangerous unwraps

- appveyor.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/109)
> Remove sqlite dep

- Cargo.toml
- src/accumulator.rs
- src/lib.rs
- src/message_header.rs
- src/messages/connect_request.rs
- src/messages/connect_response.rs
- src/messages/connect_success.rs
- src/messages/find_group.rs
- src/messages/find_group_response.rs
- src/messages/get_client_key.rs
- src/messages/get_client_key_response.rs
- src/messages/get_group_key.rs
- src/messages/get_group_key_response.rs
- src/messages/put_data.rs
- src/name_type.rs
- src/routing_client.rs
- src/routing_node.rs
- src/routing_table.rs
- src/sentinel.rs
- src/test_utils/messages_util.rs
- src/test_utils/random_trait.rs
- src/test_utils/types_util.rs
- src/types.rs
`NameType` needs further testing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/114)
> Replace `DhtId` with `NameType`

- Cargo.toml
- src/client_interface.rs
- src/lib.rs
- src/macros.rs
- src/name_type.rs
- src/node_interface.rs
- src/routing_client.rs
- src/routing_node.rs
- src/sendable.rs
Renamed `interface` to `node_interface`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/110)
> Initial work on client interface.

- src/name_type.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/115)
> Implement fmt Debug, Display, LowerHex for NameType

- src/generic_sendable_type.rs
- src/lib.rs
- src/node_interface.rs
- src/routing_node.rs
Vaults will dump message onto this type
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/125)
> generic-sendable-type

- src/routing_node.rs
- src/routing_table.rs
Introduce our_authority in routing_nodeand address_in_our_close_group_range() in routing_table
Signature of Our Authority will not change;
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/127)
> Introduce our_authority in routing_node

- src/node_interface.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/131)
> Added calls to cache get and put in RoutingNode.

- src/messages/get_data.rs
- src/routing_client.rs
- src/routing_node.rs
- src/test_utils/types_util.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/138)
> Get flow for RoutingNode.

- src/test_utils/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/139)
> XOR function for NameType in test-utils

- src/routing_node.rs
copied test into fresh branch to get rid of Cargo.toml mess up
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/142)
> Our authority test

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/147)
> Sign's message request.

- src/routing_node.rs
Initial setup for pre-sentinel message handling
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/144)
> handle_get_group_key

- src/routing_node.rs
- src/types.rs
The test only requires an overview && sorting merge conflict :(
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/145)
> tests put, handle_put and handle_put_response

- src/messages/get_group_key.rs
- src/test_utils/messages_util.rs
currently unused by handle of get_group_key
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/149)
> OPTIONAL: should requester be in the message?;

- src/messages/find_group_response.rs
- src/messages/get_group_key_response.rs
- src/sentinel.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/156)
> Trivial name change.

- src/messages/find_group_response.rs
- src/messages/get_group_key_response.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/162)
> Changed GROUP_SIZE to 32.

- src/sendable.rs
Signature of the merge fn in Sendable trait updated
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/163)
> Sendable trait signature change

- src/message_header.rs
sorry !  Thanks Mahmoud !
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/165)
> vitual YumYums: fixing the build I just broke !

- examples/routing.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/160)
> WIP Example RoutingNode

- Cargo.toml
- src/messages.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/169)
> OPTIONAL: Exclude routing example from test - fix build

- src/messages/put_data_response.rs
- src/routing_node.rs
- src/test_utils/messages_util.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/167)
> Finish HandlePut

- src/node_interface.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/177)
> Refresh and RoutingActions in routing-node

- src/routing_node.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/175)
> test handle put_public_pmid

- src/routing_node.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/179)
> RoutingTable has a double definition of GroupSize; set to 32

- src/sentinel.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/183)
> Fix for message_index condition in tests.

- examples/routing.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/184)
> Example routing node

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/187)
> Compile examples as part of cargo test

- examples/routing.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/198)
> Issue_192 no put_response when put succeeded

- examples/routing.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/199)
> Issue 190 implement cache handling in example

- examples/routing.rs
- src/messages/bootstrap_id_request.rs
- src/messages/bootstrap_id_response.rs
- src/routing_client.rs
- src/routing_node.rs
The old PR https://github.com/dirvine/routing/pull/191/files can be closed as it is replaced by this PR.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/200)
> Issue_193 use RoutingClient instead of RoutingNode for client

- src/routing_client.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/206)
> adds unauthorised_put in routing_client

- examples/routing.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/207)
> Issue_196 routing example: put/get (key, value)

- Cargo.toml
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/217)
> Routing node refactor - Issue #195

- src/routing_table.rs
- src/types.rs
fixes #181
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/218)
> removes duplicate declaration of GROUP_SIZE and QUORUM_SIZE #181

- examples/routing.rs
- src/routing_client.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/219)
> prakash's review comments

- .gitignore
- src/routing_node.rs
- src/sentinel.rs
Eliminates errors caused by locking mutex and fixes bug where we tried to access first element of a possibly empty list.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/225)
> Small refactor

- examples/routing.rs
- src/client_interface.rs
- src/error.rs
- src/lib.rs
- src/messages/get_data_response.rs
- src/messages/put_data_response.rs
- src/node_interface.rs
- src/routing_client.rs
- src/routing_node.rs
- src/test_utils/messages_util.rs
- src/types.rs
fixes #210
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dirvine/routing/232)
> Refactors error handling

- README.md
- src/messages.rs
- src/messages/connect_request.rs
- src/messages/connect_response.rs
- src/messages/connect_success.rs
- src/messages/find_group_response.rs
- src/messages/put_public_id.rs
- src/name_type.rs
- src/routing_node.rs
- src/routing_table.rs
- src/sentinel.rs
- src/test_utils/messages_util.rs
- src/test_utils/types_util.rs
- src/types.rs
PMID name is too specific to maidsafe and confuses with PMID type in clients of this lib, particularly vaults
> remove PMID name from lib and replace with ID.

- examples/routing.rs
- src/authority.rs
- src/lib.rs
- src/message_header.rs
- src/node_interface.rs
- src/routing_client.rs
- src/routing_node.rs
- src/routing_table.rs
- src/sentinel.rs
- src/types.rs
1. Added utility function send_to_non_routing_list in routing node
2. Moved authority to a separate file
> Cleanup only

- src/routing_node.rs
Forgot to do this as part of mormalising error handling.
> Minor: renames RecvResult to RoutingResult

- src/messages.rs
- src/routing_node.rs
Some errors were being ignored at low levels (such as sending), so I tried to move the 'ignoring' upwards. Also trying to make the ignoring explicit using the `ignore` free function.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/238)
> Further refactor of error handling

- examples/routing.rs
- src/challenge.rs
- src/lib.rs
- src/routing_node.rs
- src/routing_table.rs
- src/utils.rs
> Update routing connections

- src/routing_node.rs
resolve #229 
Check sources of all messages to add to routing table
> Issue 229 send connect

- src/routing_client.rs
> uses encoding mthods implementation in utils

- README.md
Add Network Visualiser at end of sprint
> Add Network Visualiser

- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/258)
> Include signature in derivation of name.

- examples/routing.rs
- src/routing_client.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/269)
> Interface change for async operations.

- src/lib.rs
- src/relay.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/273)
> relay module

- README.md
- src/routing_node.rs
Put bare signature of handlers for handle_put_public_id_response
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/280)
> Initial commit to allow collaboration with MAID-1039

- src/authority.rs
- src/relay.rs
- src/routing_node.rs
- src/routing_table.rs
- src/types.rs
Almost done need to get commented out test compiling.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/276)
> MAID-1040 Added assign_relocated_name and is_relocated methods to PublicId and Id.

- examples/routing.rs
- src/error.rs
- src/node_interface.rs
- src/routing_node.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/284)
> Maid-1112 new put flow

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/287)
> Reschedule tasks to accommodate Vault and Sentinel

- README.md
- src/error.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/288)
> Maid 1060 response error

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/289)
> Version bump v0.1.61

- src/authority.rs
- src/lib.rs
- src/messages/connect_request.rs
- src/relay.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/291)
> Maid 1057 : Related to making event loop in routing_node internal::

- src/authority.rs
- src/message_header.rs
- src/node_interface.rs
- src/routing_client.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/test_utils/types_util.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/298)
> Maid 1126: Reflect changes in Source / Destination

- Cargo.toml
- src/routing_membrane.rs
- src/routing_node.rs
- src/routing_node_new.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/299)
> connect_request sending a vector of endpoints

- src/node_interface.rs
- src/routing_node_new.rs
suggestion aiming to simplify routing node creatiion
> simplifies routing node creation

- src/routing_membrane.rs
- src/routing_node_new.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/307)
> WIP MAID-1070 Tying up all loose ends

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/309)
> Maid 1070 tie up loose ends

- examples/simple_key_value_store.rs
addresses issues #315 && #321 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/322)
> Issues 315 & 321

- examples/simple_key_value_store.rs
Fixed #316
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/327)
> Fix minor issues with simple_key_value_store output, issue #316

- src/message_header.rs
- src/routing_membrane.rs
#325
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/326)
> Send FindGroupResponse back directly to bootstrap if we can

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/334)
> allow crust updates quietly

- examples/simple_key_value_store.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/335)
> Fixes #314.  Fixes #324.

- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/337)
> Add with_keys constructor to Id type. Fixes #336.

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/338)
> Version bump 0.1.62->63

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/340)
> Not pop from rotuing table when query just peek

- src/lib.rs
- src/relay.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/who_are_you.rs
continues #330
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/339)
> Who are you

- examples/simple_key_value_store.rs
- src/lib.rs
- src/relay.rs
- src/routing_client.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/who_are_you.rs
resolves #342
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/346)
> Cleanup printlines - Issue 342

- Cargo.toml
- README.md
- examples/simple_key_value_store.rs
- src/relay.rs
- src/routing_client.rs
- src/routing_membrane.rs
- src/routing_node.rs
also updated readme
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/353)
> BUMP v0.1.64

- src/authority.rs
source = destination to refresh the data on the new group
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/357)
> Introduce Authority::OurCloseGroup for reflective transfers

- src/routing_membrane.rs
- src/routing_node.rs
resolves #354
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/355)
> remove debug_assert on send functions

- src/error.rs
https://maidsafe.atlassian.net/browse/MAID-1121
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/358)
> Added Encode/Decode test for Error::ResponseError

- examples/simple_key_value_store.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/356)
> Removes some unwraps.

- src/messages.rs
- src/messages/refresh.rs
resolves #361
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/365)
> Adds Refresh message and a type tag for it

- examples/simple_key_value_store.rs
- src/error.rs
- src/lib.rs
- src/messages/refresh.rs
- src/node_interface.rs
- src/refresh_accumulator.rs
- src/routing_membrane.rs
Simple refresh mechanism without traits
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/368)
> Refresh without sendable trait

- examples/simple_key_value_store.rs
- src/node_interface.rs
resolves #290
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/371)
> remove handle_get_key from interface

- src/types.rs
resolves #373
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/376)
> reduce group size to 23

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/378)
> VERSION BUMP v0.1.70

- src/relay.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/384)
> check that mock-endpoint is not already in the relay_map

- src/messages/refresh.rs
- src/test_utils/messages_util.rs
And adds test for it
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/392)
> Fixes Refresh message serialization

- src/routing_client.rs
handle_put_data_response done
still clean up other .unwraps()
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/391)
> handle_put_data_response

- examples/simple_key_value_store.rs
- src/node_interface.rs
- src/routing_node.rs
fixes issue #379
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/380)
> simplifies creation of routing_node -- issue #379

- src/routing_client.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/397)
> Preventing arithmetic overflow panic

- src/routing_client.rs
- src/routing_membrane.rs
debugs issue #395
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/399)
> Additional debug on Issue 395

- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/401)
> Version change to 0.1.71

- src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/404)
> feature gating more code

- src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/405)
> remove unneeded features

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/408)
> Version change to 0.2.0

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/409)
> Revert version change in CARGO.toml

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/413)
> Version change to 0.2.2

- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/415)
> Updated links.

- examples/simple_key_value_store.rs
- src/routing_membrane.rs
We don't act on the resulting MethodCall
Signed-off-by: Benjamin Bollen <benjamin.bollen@maidsafe.net>
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/416)
> Activate Churn Handle;

- examples/simple_key_value_store.rs
- src/routing_client.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/419)
> Correct PutResponse in client_interface

- src/routing_client.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/421)
> correct Authority unauthorised put

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/422)
> Version change to 0.2.5

- CHANGELOG.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/425)
> Version change to 0.2.6

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/428)
> Version change to 0.2.7

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/435)
> Adds TODO list to README.md

- CHANGELOG.md
- Cargo.toml
- README.md
Reverts maidsafe/routing#436
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/438)
> Revert "Version 0.2.8"

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/439)
> Version change to 0.2.8

- CHANGELOG.md
- Cargo.toml
- README.md
- src/error.rs
- src/routing_node.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/440)
> Bring 0.2 up to date with master

- src/authority.rs
- src/immutable_data.rs
- src/message_header.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/441)
> To follow PR #434.

- src/routing_client.rs
To work with the new StructuredData stuff
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/446)
> Refactorers RoutingClient

- src/messages.rs
- src/routing_client.rs
When creating Message::SignedRoutingMessage
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/450)
> Sign RoutingMessage not Unsigned(RoutingMessage)

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/447)
> Routing node changes for refactored messages.

- src/authority.rs
- src/node_interface.rs
- src/relay.rs
- src/routing_membrane.rs
Please only consider routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/448)
> WIP: Refactoring Messages

- src/routing_node.rs
- src/test_utils/types_util.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/452)
> Remove test_util errors.

- src/messages.rs
- src/node_interface.rs
- src/routing_membrane.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/453)
> work on handle_get

- examples/simple_key_value_store.rs
- src/routing_client.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/455)
> Will probaly require further updates when the error messages clear.

- src/routing_membrane.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/458)
> Fixes typos

- src/messages.rs
- src/node_interface.rs
- src/routing_membrane.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/459)
> More compilation fixes

- src/routing_membrane.rs
Few commits back I made an invalid assumptions that get
messages only arrive from non-group sources.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/461)
> Fix handling caching get

- Cargo.toml
- src/authority.rs
- src/data.rs
- src/id.rs
- src/immutable_data.rs
- src/lib.rs
- src/messages.rs
- src/plain_data.rs
- src/public_id.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/structured_data.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/463)
> Further refactoring

- Cargo.toml
- src/authority.rs
- src/data.rs
- src/id.rs
- src/immutable_data.rs
- src/lib.rs
- src/messages.rs
- src/plain_data.rs
- src/public_id.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/structured_data.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/462)
> WIP - routing membrane rework 

- src/messages.rs
- src/routing_client.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/465)
> WIP changes to send_on and reply_to

- src/messages.rs
- src/routing_client.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/utils.rs
As per discussion where the consensus was that all messages should be signed
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/464)
> Gets rid of the Message type and introduces SignedMessage

- src/node_interface.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/470)
> Adds 'location' to NodeInterface::handle_get

- src/node_interface.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/471)
> remove location from handle_get_data

- src/immutable_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/472)
> add access to type_tag for immutable_data

- src/immutable_data.rs
- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/474)
> Maid 1163 getters for structured data

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/476)
> Simplifying and proper name when msg arrives from bootstrap node

- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/477)
> Build fix.

- src/authority.rs
- src/messages.rs
tests not checked, as last remaining compilation errors still to be resolved
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/478)
> Our authority

- src/immutable_data.rs
- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/479)
> rename the function names

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/481)
> un-commenting commented tests

- src/authority.rs
- src/test_utils/messages_util.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/482)
> final corrections to our_authority

- Cargo.toml
- examples/simple_key_value_store.rs
TestData in the example still has to be converted to PlainData
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/483)
> Correct Interface for example; disabled example on test

- src/authority.rs
- src/relay.rs
- src/routing_membrane.rs
- src/routing_table.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/484)
> Disables Failing Tests

- src/client_interface.rs
- src/messages.rs
- src/node_interface.rs
- src/routing_client.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/480)
> Client and Node Interface changes

- src/authority.rs
- src/id.rs
- src/name_type.rs
- src/public_id.rs
- src/relay.rs
- src/routing_client.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/routing_table.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/486)
> Fix for routing_table tests, Implement public_id name

- src/error.rs
Not Vec<u8>
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/487)
> ResponseError::FailedToStoreData now carries Data

- src/authority.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/488)
> correct our_authority unit test

- src/error.rs
- src/routing_client.rs
- src/structured_data.rs
- src/test_utils/types_util.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/490)
> Api changes

- src/node_interface.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/485)
> MAID-1262.

- src/messages.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/491)
> Implementes RoutingMessage::create_reply + few test fixes

- src/relay.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/489)
> relay tests already were passing

- src/id.rs
- src/public_id.rs
- src/types.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/492)
> Correct unit tests Id and PublicId

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/493)
> RoutingMembrane test fixes

- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/495)
> interface addition and correction

- src/data.rs
- src/immutable_data.rs
- src/plain_data.rs
- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/494)
> Adds 'payload_size' fn to Data

- examples/simple_key_value_store.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/496)
> Compile fix.

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/501)
> Use maidsafe_sodiumoxide.

- src/authority.rs
- src/node_interface.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/502)
> Removes MethodCall::None

- Cargo.toml
- src/data.rs
- src/immutable_data.rs
- src/lib.rs
- src/plain_data.rs
- src/routing_membrane.rs
- src/sentinel_request.rs
- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/499)
> Refactor RoutingMembrane::handle_put_data as preparation for adding PureSentinel: MAID-1164

- Cargo.toml
- examples/simple_key_value_store.rs
- src/routing_client.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/510)
> WIP First option

- src/routing_membrane.rs
- src/routing_node.rs
reflective send
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/509)
> clone sender channel

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/516)
> update cargo.toml dependencies

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/517)
> Unplug sentinel

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/519)
> handles messages based on actual_source(client/group)

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/511)
> Maid 1251 relay behaviour

- examples/simple_key_value_store.rs
- src/routing_client.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/527)
> Refactors client to the new handshake protocol

- src/authority.rs
- src/messages.rs
- src/routing_membrane.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/526)
> Correct put public

- src/routing_membrane.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/529)
> Review find group

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/530)
> WIP ConnectRequest sent over Bootstrap connection

- src/client_interface.rs
- src/relay.rs
- src/routing_client.rs
- src/routing_membrane.rs
- src/routing_node.rs
- src/routing_table.rs
- src/who_are_you.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/539)
> fixes warning

- .travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/528)
> travix OSX fix 

- examples/simple_key_value_store.rs
- src/routing_client.rs
- src/routing_membrane.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/538)
> enable env_logger for routing example

- src/lib.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/541)
> reinstate LINT checkers

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/540)
> limit number of bootstrap connections by crust

- src/messages.rs
- src/relay.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/544)
> correct LINT checks

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/548)
> Remove bootstrap connections which were not used

- examples/simple_key_value_store.rs
- src/routing_membrane.rs
starting a new branch for Put Get review
relates to #547
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/549)
> Review flow

- src/routing_node.rs
until fully initialized (because we don't know which
bootstrap node initializes first).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/550)
> Store NameType for each bootstrap node

- src/routing_node.rs
Fixes stupid mistake from my previous commit
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/551)
> Don't drop all bootstrap nodes

- src/routing_membrane.rs
- src/user_message.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/520)
> adds create_forward for SentinelGetDataResponse & SentinelPutResponse

- src/routing_membrane.rs
- src/user_message.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/523)
> resolved variable should not be a pair: Maid 1268

- src/routing_membrane.rs
- src/user_message.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/524)
> renames handle_group_xxx to handle_node_xxx: Maid 1269

- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/525)
> make sure only sentinel returned variable is used in handlers: Maid 1270

- examples/simple_key_value_store.rs
- src/messages.rs
- src/routing_membrane.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/542)
> merge node-client handlers: Maid 1272

- examples/simple_key_value_store.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/559)
> compilation fix in example

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/562)
> Add ARM / Linux CI badge

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/563)
> version change to 0.3.0

- src/relay.rs
- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/566)
> bootstrap_connections

- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/567)
> RoutingNode::Send

- .travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/574)
> Fixed libsodium linking issue in .travis.yml.

- Cargo.toml
- src/lib.rs
I'm good either way, whether or not to merge this.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/575)
> temporarily remove sentinel dependency

- examples/simple_key_value_store.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/579)
> Simpler example

- src/messages.rs
- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/578)
> Connect request

- src/authority.rs
- src/messages.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/580)
> Review message received

- src/routing_node.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/585)
> Introducing debug output

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/587)
> version change to 0.3.1

- src/messages.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/588)
> correct ExternalRequest::Delete to have Data

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/589)
> Patch node handle hello

- src/routing.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/590)
> Testing routing

- src/authority.rs
- src/id.rs
- src/relay.rs
- src/routing.rs
- src/test_utils/messages_util.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/591)
> WIP - Get tests back on track

- src/authority.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/592)
> impl Debug for Authority

- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/593)
> remove unused - and not to be used - trait mergeable

- README.md
- appveyor.yml
- src/routing.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/594)
> add back appveyor

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/596)
> handle_lost_connection

- src/peer.rs
- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/598)
> WIP Testing accumulator

- src/lib.rs
- src/routing_node.rs
- src/wake_up.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/599)
> flip looping order, introduce WakeUp timer

- src/messages.rs
- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/600)
> WIP Correct ConnectRequest/Response for Routing

- examples/simple_key_value_store.rs
- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/601)
> Correction to Handle Hello for Routing Nodes

- examples/simple_key_value_store.rs
- src/lib.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/603)
> Default listen to 5483 port

- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/605)
> Correcting Structured Data (conceptually and functionally)

- src/data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/607)
> DataRequest::StrData::name() correction

- src/lib.rs
- src/messages.rs
- src/test_utils/types_util.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/609)
> Reduce public API

- src/error.rs
- src/event.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/606)
> API update for Event::Connected

- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/611)
> Fixes #506 and Optional Signature for StructuredData

- src/authority.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/614)
> re-implement auth test

- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/616)
> make validation public

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/618)
> version change to 0.3.2

- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/623)
> putting maximum allowed size of structured data

- examples/simple_key_value_store.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/624)
> Example032

- examples/simple_key_value_store.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/631)
> Remove warnings from example

- src/routing_core.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/634)
> rename fob to public_id

- examples/simple_key_value_store.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/635)
> remove feature

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/639)
> Version change to 0.3.3

- CHANGELOG.md
- Cargo.toml
- src/filter.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/643)
> version change to 0.3.4

- src/error.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/646)
> Correct remove sacrificial error

- appveyor.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/647)
> Remove allow failures from x86

- src/lib.rs
- src/name_type.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/649)
> Remove unstable feature. Fixes #560.

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/648)
> Version change to 0.3.5

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/650)
> Cache data in ttl lru cache in line with current routing requirements.

- Cargo.toml
- examples/simple_key_value_store.rs
- src/action.rs
- src/churn.rs
- src/direct_messages.rs
- src/error.rs
- src/lib.rs
- src/messages.rs
- src/name_type.rs
- src/relay.rs
- src/routing_core.rs
- src/routing_node.rs
and temporarily disable connection_filter (as unwraps in that crate are hit)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/654)
> enable Scanning

- Cargo.toml
- src/churn.rs
- src/direct_messages.rs
- src/error.rs
- src/lib.rs
- src/messages.rs
- src/name_type.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/644)
> Move Hello to signed DirectMessage:::Hello

- Cargo.toml
- src/action.rs
- src/churn.rs
- src/direct_messages.rs
- src/error.rs
- src/lib.rs
- src/messages.rs
- src/name_type.rs
- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/651)
> Handle churn

- Cargo.toml
- examples/simple_key_value_store.rs
- src/action.rs
- src/churn.rs
- src/direct_messages.rs
- src/error.rs
- src/lib.rs
- src/messages.rs
- src/name_type.rs
- src/relay.rs
- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/653)
> Simplify Connection filter

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/656)
> correct error for Refresh message; which dropped all refresh messages

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/657)
> Version change to 0.3.6

- examples/simple_key_value_store.rs
- src/messages.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/655)
> WIP enable crude data churn in the simple key value store example

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/664)
> Updated to match Crust 0.2.10 API change

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/665)
> Version change to 0.3.8

- .travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/670)
> Updated .travis.yml.

- src/error.rs
- src/routing.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/671)
> Maid 1344 low balance error

- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/684)
> address Connected and Churn behaviour as discussed in #683

- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/686)
> Version change to 0.3.10

- src/data.rs
- src/direct_messages.rs
- src/error.rs
- src/id.rs
- src/public_id.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/680)
> MAID 1361 Added unit tests for id, public_id, data, direct_message, error

- src/data.rs
- src/direct_messages.rs
- src/error.rs
- src/id.rs
- src/public_id.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/690)
> Fixes #689

- examples/key_value_store.rs
- examples/simple_key_value_store.rs
- src/action.rs
- src/authority.rs
- src/event.rs
- src/filter.rs
- src/message_accumulator.rs
- src/messages.rs
- src/refresh_accumulator.rs
- src/routing.rs
- src/routing_core.rs
- src/routing_node.rs
- src/types.rs
builds on #682, resolves issue #681 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/692)
> Issue 681 event do refresh

- src/error.rs
Fixed issue #694
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/695)
> Fixed issue #694

- src/lib.rs
- src/name_type.rs
- src/test_utils/mod.rs
fixes #674
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/696)
> expose const NAME_TYPE_LEN and cfg(test) random traits

- src/event.rs
- src/structured_data.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/699)
> implement Debug for StructuredData

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/698)
> version change to 0.3.11

- src/structured_data.rs
- src/types.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/702)
> Add tests and tidyup for minors part 2.

- src/peer.rs
- src/relay.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/703)
> Relay tests.

- Cargo.toml
- src/message_accumulator.rs
- src/refresh_accumulator.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/701)
> Maid 1357 accumulators

- src/relay.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/705)
> Make random relay endpoint more random.

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/708)
> Version change to 0.3.12

- Cargo.toml
- src/action.rs
- src/authority.rs
- src/peer.rs
- src/relay.rs
- src/routing_core.rs
- src/routing_node.rs
- src/routing_table.rs
- src/test_utils/messages_util.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/704)
> MAID-1366 BREAKS ROUTING BOOTSTRAPPING crust 3 refactor

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/713)
> version change to 0.4.0

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/715)
> Test on droplets - restoring state to compare for routing issue observed on droplets

- Cargo.toml
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/717)
> Revert-715, Interface addresses and crust dependency

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/718)
> Version change to 0.4.1

- README.md
- src/lib.rs
- tests/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/726)
> Updated lint checks and README.md.

- src/action.rs
- src/routing_core.rs
- src/routing_node.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/731)
> MAID-1377 introduce enum ::routing_core::State

- src/messages.rs
- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/727)
> Handle errors properly in <StructuredData as Debug>::fmt

- src/lib.rs
- src/utilities/expiration_map.rs
- src/utilities/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/732)
> ExpirationMap.

- src/routing_core.rs
- src/routing_node.rs
- src/utilities/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/738)
> OnConnect.

- src/routing_core.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/743)
> OnConnectRequest.

- src/routing_node.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/744)
> OnConnectResponse.

- src/connection_management/hole_punching_state.rs
- src/connection_management/mod.rs
- src/lib.rs
Hi @benjaminbollen 
Here is my first implementation!
Any [derive] intended for HolePunchingState?
Any impl?
What about variant Mapped?
Type of secret and number_of_failed_attempts correct?
Looking forward to your feedback!
Cheers!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/749)
> MAID-1448 Added HolePunchingState

- src/name_type.rs
This function would be useful in vault and is probably useful to other people as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/751)
> rename/publicise NameType::get_full_id

- src/action.rs
- src/direct_messages.rs
- src/routing_core.rs
- src/routing_node.rs
- src/routing_table.rs
- src/utilities/expiration_map.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/747)
> Maid 1437.

- src/name_type.rs
To complement `NameType::as_hex`. Also useful in safe_vault.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/754)
> Add NameType::from_hex

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/769)
> Version change to 0.4.2

- src/action.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/775)
> Removing no longer needed Actions

- src/event.rs
- src/routing.rs
- src/routing_node.rs
- src/structured_data.rs
- src/types.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/776)
> Minor fixups

- src/error.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/778)
> start to remove ignore statements, rename reset to restart

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/784)
> relocated-network-name -> Y to A

- examples/key_value_store.rs
- examples/simple_key_value_store.rs
- src/lib.rs
- tests/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/788)
> Remove lint and 100 character pernicketiness

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/791)
> handle relocation response - dont promote to node

- src/routing_node.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/792)
> handle connect request - verifying client pub key

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/793)
> Compete handling of identify message.

- src/routing_node.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/794)
> Adjusted log output to show state and name.

- src/direct_messages.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/795)
> Invoke request for network name after bootstrapping.

- src/direct_messages.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/796)
> Further debug fixes.

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/798)
> Reducing states to Disconnected, Client and Node

- Cargo.toml
- examples/key_value_store.rs
- examples/simple_key_value_store.rs
- src/authority.rs
- src/error.rs
- src/event.rs
- src/lib.rs
- src/messages.rs
- src/name_type.rs
- src/public_id.rs
- src/refresh_accumulator.rs
- src/routing.rs
- src/routing_client.rs
- src/routing_node.rs
- src/routing_table.rs
- src/test_utils/node.rs
- src/types.rs
- src/utils.rs
- tests/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/800)
> WIP - do not merge

- src/lib.rs
- src/name_type.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/806)
> Bugfix in RoutingTable.

- src/authority.rs
- src/routing_node.rs
- src/routing_table.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/810)
> Routing Table cleanup

- CHANGELOG.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/819)
> Renaming back to NameType in CHANGELOG.md

- Cargo.toml
- examples/key_value_store.rs
- src/routing_node.rs
- src/test_utils/node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/820)
> update to latest API for kademlia_routing_table

- src/routing_node.rs
- Added `want_address_in_routing_table` so we dont ignore nodes already existing in the RT with the `routing_table.want_to_add()`
- Handle case where we are the proxy node for a client not in our close group
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/825)
> Minor fixes to message handling

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/826)
> Dont accumulate GetCloseGroup Response

- examples/key_value_store.rs
- src/action.rs
- src/error.rs
- src/event.rs
- src/lib.rs
- src/messages.rs
- src/routing.rs
- src/routing_client.rs
- src/routing_node.rs
- src/test_utils/client.rs
- src/test_utils/node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/827)
> Corrections - Check commits

- src/acceptors.rs
- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/830)
> Add our endpoint to acceptors in bootstrap on_connect.

- examples/key_value_store.rs
- examples/simple_key_value_store.rs
- src/acceptors.rs
- src/action.rs
- src/authority.rs
- src/connection_management/hole_punching_state.rs
- src/data.rs
- src/error.rs
- src/event.rs
- src/id.rs
- src/immutable_data.rs
- src/lib.rs
- src/messages.rs
- src/plain_data.rs
- src/refresh_accumulator.rs
- src/routing.rs
- src/routing_client.rs
- src/routing_node.rs
- src/structured_data.rs
- src/test_utils/client.rs
- src/test_utils/messages_util.rs
- src/test_utils/mod.rs
- src/test_utils/node.rs
- src/types.rs
- src/utils.rs
- tests/churn_node.rs
- tests/lib.rs
- tests/node.rs
Can be improved / Qa request
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/831)
> Updating Documentation 

- examples/key_value_store.rs
- src/lib.rs
- src/messages.rs
- src/routing_node.rs
- src/structured_data.rs
- src/types.rs
- src/utils.rs
- tests/churn_node.rs
- tests/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/834)
> Public API exposed in lib.rs

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/835)
> Version change to 0.5.0

- src/routing_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/839)
> Correction in blocking interface error return

- src/routing.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/840)
> changing stop to take immutable self

- src/authority.rs
- src/error.rs
- src/event.rs
- src/lib.rs
- src/messages.rs
- src/routing_node.rs
- src/test_utils/node.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/847)
> Churn handling

- Cargo.toml
- examples/local_network.rs
- examples/utils/churn_node.rs
- examples/utils/client.rs
- examples/utils/node.rs
- src/connection_management/hole_punching_state.rs
- src/data.rs
- src/lib.rs
- src/structured_data.rs
- src/types.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/849)
> Examples compile and all tests pass

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/850)
> Version change to 0.5.3

- examples/utils/example_node.rs
- src/action.rs
- src/client.rs
- src/core.rs
- src/event.rs
- src/lib.rs
- src/messages.rs
- src/node.rs
- src/types.rs
Addition to PR #855 
Removed refresh_accumulator and corresponding event for refresh. Refresh is treated as a standard routing message
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/856)
> Churn handling updates

- examples/utils/example_node.rs
- src/client.rs
- src/core.rs
- src/event.rs
- src/lib.rs
- src/messages.rs
- src/node.rs
- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/855)
> WIP - Churn handling - Churn and Lost Close Node combined

- Cargo.toml
- examples/ci_test.rs
- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/core.rs
- src/event.rs
- src/node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/860)
> Trivial updates (WIP)

- Cargo.toml
- examples/ci_test.rs
- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/core.rs
- src/event.rs
- src/node.rs
Addition to PR #860 
- Fixed logging to file from `ci_test` example
Needs to be confirmed as fine from Windows/Linux too
> WIP - Examples logging

- examples/utils/example_client.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/864)
> Replacing inefficient sleep-wait with more correct idiom

- .travis.yml
- appveyor.yml
- examples/ci_test.rs
- examples/utils/example_node.rs
- src/core.rs
- src/types.rs
ci_test example is functional with default parameters.
Added ci_test run to ci builds
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/862)
> Relaxed churn threshold

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/868)
> Version change to 0.6.1

- examples/utils/example_node.rs
Also deduplicate group sorting by closeness.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/869)
> Ignore double puts in the example.

- src/id.rs
- src/lib.rs
This expands the crate-level documentation, giving code samples for node and client creation and an example put workflow for immutable data.
I will add to the documentation for the structures in a separate PR.
The detailed bootstrap, churn and node discovery mechanisms will also be added later, but probably only as a code comment, as they are not crucial to be able to use the library.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/871)
> Expand the documentation.

- src/core.rs
Add an overview of the bootstrap process as a doc comment to Core.
I use the designations A, B, X and Y in the same way they are already referenced in comments in other places in the code.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/873)
> Add bootstrap documentation to Core

- src/authority.rs
- src/client.rs
- src/id.rs
- src/immutable_data.rs
- src/node.rs
- src/plain_data.rs
- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/872)
> Expand documentation for the main structures.

- src/messages.rs
- src/node.rs
- src/plain_data.rs
- src/types.rs
- src/utils.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/877)
> Extend documentation for node, plain_data, types and utils.

- src/acceptors.rs
- src/core.rs
- src/error.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/876)
> A few documentation additions.

- src/structured_data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/879)
> Expand the StructuredData documentation.

- src/structured_data.rs
Deal with the underflow for required signatures, and change the
requirement to a strict majority.
I added a test for the strict majority (with four owners) and shortened
the tests somewhat. Also, using `unwrap()` instead of `ok()` would print
more information in case of failure.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/880)
> Fix computation of remaining required signatures for StructuredData.

- src/types.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/881)
> Replace explicit ASCII codes.

- src/core.rs
- src/messages.rs
I also made a small change to `HopMessage`'s API to make it consistent with `SignedMessage`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/882)
> Some improvements to the message.rs documentation.

- src/event.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/883)
> Improve the Event documentation.

- examples/utils/example_client.rs
- examples/utils/example_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/884)
> Add some more documentation to the example.

- src/core.rs
A client should never set a small dynamic quorum size, as that is
currently never updated. Instead of introducing a new message type to
reset the client's quorum size, let's just not accept any clients until
there are at least 8 nodes in our routing table.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/886)
> Reject clients if the routing table is too small.

- src/core.rs
Organise the use statements as recommended in:
https://aturon.github.io/style/imports.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/885)
> Follow the recommendations for imports.

- src/data.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/888)
> Fix two spelling mistakes in the comments

- examples/utils/example_node.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/889)
> Document example churn handling and make it a bit more readable.

- src/core.rs
- src/lib.rs
- src/tests.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/891)
> Add test for node connection (MAID-1534)

- .travis.yml
- appveyor.yml
- src/tests.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/893)
> Add test for sending requests and responses (MAID-1535)

- .travis.yml
- appveyor.yml
- src/tests.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/896)
> MAID-1538 & MAID-1539: test churn when nodes join or leave.

- Cargo.toml
- src/lib.rs
- tests/ci.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/898)
> Ci test binary

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/899)
> Version change to 0.6.3

- tests/ci.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/900)
> Tests for less/more than quorum responses.

- .travis.yml
- Cargo.toml
- tests/ci.rs
This avoids unconditionally setting the open file limit in the Travis script.
Now only the CI test (which is unrepresentative of normal usage conditions) on OS X will try to adjust the limit to 1024 if it's set below this.  Other tests and other OSs are unaffected.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/901)
> ulimit fix

- Cargo.toml
- examples/utils/example_node.rs
- src/authority.rs
- src/core.rs
- src/error.rs
- src/event.rs
- src/messages.rs
- tests/ci.rs
Changes needed for the new routing mechanism as per the RFC:
https://github.com/maidsafe/rfcs/blob/master/active/0019-new-kademlia-routing-logic/0019-new-kademlia-routing-logic.md
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/902)
> RFC 0019-new-kademlia-routing-logic

- src/authority.rs
- src/core.rs
- src/error.rs
- src/messages.rs
- src/plain_data.rs
- src/structured_data.rs
Apply clippy and rustfmt, and split up some methods.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/903)
> Minor core.rs refactoring

- examples/utils/example_node.rs
- src/core.rs
Also: Minor cleanup in core.rs.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/907)
> Remove group_by_closeness in example node.

- .travis.yml
- Cargo.toml
- examples/ci_test.rs
- examples/key_value_store.rs
- src/lib.rs
- tests/ci.rs
- tests/local_network.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/908)
> Add clippy and nightly for travis.

- Cargo.toml
- src/core.rs
WIP because adding and removing connections from nodes in the routing table is not implemented yet. Waiting for the crust changes to land first.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/909)
> WIP Port to kademlia_routing_table 0.3.0

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/916)
> Version change to 0.7.1

- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/core.rs
- src/event.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/917)
> Add Event::Disconnected and log disconnecting clients.

- src/authority.rs
- src/core.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/921)
> Allow several clients with the same key to join via one node.

- examples/utils/example_client.rs
- src/client.rs
- tests/ci.rs
- tests/utils.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/923)
> Return the MessageId from Client methods.

- examples/utils/example_client.rs
- src/client.rs
- tests/ci.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/927)
> Take MessageId as an argument in Client.

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/928)
> Version change to 0.10.0

- Cargo.toml
- src/core.rs
- src/mock_crust/support.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/929)
> Deduplicate serialising and sending direct messages and remove unused dependency.

- Cargo.toml
- src/error.rs
- src/lib.rs
- src/structured_data.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/930)
> replace cbor with maidsafe_utilities::serialisation

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- tests/ci.rs
- tests/local_network.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/931)
> Version change to 0.11.0

- examples/ci_test.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/932)
> Get data immediately after put. Introduce churn at some random request.

- src/core.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/933)
> Send a Disconnected event if client fails to bootstrap.

- CHANGELOG.md
- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/934)
> Version change to 0.11.1

- src/core.rs
- src/core_tests.rs
- dropping nodes.
- verification of the kademlia invariant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/938)
> More unit tests

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/939)
> Don't return from send if one connection fails.

- examples/ci_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/942)
> Allow ci_tests to run client against droplets.

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/944)
> Simplify bootstrap and disable node_id_cache check.

- src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/943)
> routing tests.

- src/types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/945) &emsp; Multiple assignees:&emsp;<img alt="@Fraser999" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/190532?s=40&v=3">&nbsp;<a href="/maidsafe/routing/pulls/assigned/Fraser999">Fraser999</a>,&emsp;<img alt="@afck" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/7894725?s=40&v=3">&nbsp;<a href="/maidsafe/routing/pulls/assigned/afck">afck</a>,&emsp;<img alt="@brian-js" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/623265?s=40&v=3">&nbsp;<a href="/maidsafe/routing/pulls/assigned/brian-js">brian-js</a>,&emsp;<img …
> MessageId incrementable and decrementable

- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/client.rs
- src/core.rs
- src/core_tests.rs
- src/error.rs
- src/lib.rs
- src/messages.rs
- src/node.rs
- tests/ci.rs
And disable the cache in the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/954)
> Make cache an option and remove name from HopMessage.

- src/core.rs
- src/messages.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/957)
> Send periodic keepalive messages to all peers.

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/958)
> Remove dropped peers from peer_map.

- examples/ci_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/959)
> Add an option for multiple batches to ci_test.

- examples/utils/example_node.rs
This caused the group to get out of sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/962)
> Revert merging on refresh in the example node.

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/963)
> Start listening on BootstrapConnect.

- Cargo.toml
- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/964)
> Remove logging of all hop messages.

- CHANGELOG.md
- Cargo.toml
- src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/967)
> Version change to 0.13.0

- Cargo.toml
- examples/ci_test.rs
- examples/utils/example_node.rs
- src/action.rs
- src/core.rs
- src/core_tests.rs
- src/messages.rs
- src/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/968)
> 1) Refresh message takes a message id now 2) updated dependencies

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/969)
> Version change to 0.14.0

- src/mock_crust/crust.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/970)
> Make mock PeerId impl Rand.

- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/messages.rs
- src/node.rs
- tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/971)
> Return data name with Put, Post and Delete success.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/972)
> Version change to 0.15.0

- src/core.rs
Also reduce some logging spam.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/973)
> Always send a NodeAdded event for a new peer.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/975)
> Version change to 0.15.1

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/978)
> Version change to 0.16.0

- src/core.rs
- src/data.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/979)
> fix/data: Fix the name of DataIdentifier::Structured.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/981)
> Version change to 0.16.1

- src/core.rs
- src/messages.rs
This keeps a list of all known recipients of a message and passes it on,
so that all recipients that already have it can be skipped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/982)
> perf/core: Keep track of recipients in HopMessage.

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/984)
> feat/core: Add HEARTBEAT_ATTEMPTS constant and use a 30 second heartbeat.

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/985)
> fix/core: Fix unneeded harvesting.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/986)
> Version change to 0.16.3

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/987)
> Version change to 0.17.0

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/988)
> fix/core: Re-enable node harvesting.

- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/core.rs
- src/data.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/989)
> chore/core: more clearly log disconnecting and update examples

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/991)
> fix/core: Skip accumulation for more response types

- examples/utils/example_node.rs
- src/core.rs
- src/event.rs
Also dont' send `GetNetworkName` if we just sent it to another node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/990)
> Add GetNetworkNameFailed and NetworkStartupFailed events.

- examples/ci_test.rs
- examples/key_value_store.rs
- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/core.rs
- src/core_tests.rs
- src/id.rs
- src/mock_crust/support.rs
- src/mock_crust/tests.rs
- src/types.rs
- tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/995)
> chore/all: Fix remaining Clippy warnings.

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/996)
> fix/core: Only request bucket groups if we are a node.

- src/core.rs
- src/event.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/997)
> fix/log: Make some debug logs more useful.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/998)
> Version change to 0.18.1

- Cargo.toml
- src/core.rs
- src/lib.rs
- src/tunnels.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1000)
> chore/all: Replace time crate with std::time.

- .travis.yml
- examples/ci_test.rs
- examples/key_value_store.rs
- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/core.rs
- src/event.rs
- src/lib.rs
- src/stats.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/999)
> feat/stats: Extract Stats from Core and add message counting.

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1001)
> Version change to 0.18.2

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1003)
> fix/core: Don't start a new network after BootstrapConnect.

- CHANGELOG.md
- Cargo.toml
- src/core.rs
- src/stats.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1002)
> Version change to 0.18.3

- src/stats.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1004)
> fix/stats: Reduce the frequency of the message stats log message.

- Cargo.toml
- build.rs
- src/lib.rs
Based on the tunnel branch, so *DO NOT MERGE* until tunnel is merged.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/960)
> Add various sequence diagrams to the main doc

- appveyor.yml
- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1007)
> fix/core: Don't log error when filtering client messages.

- Cargo.toml
- src/core.rs
- src/lib.rs
- src/messages.rs
- src/stats.rs
- src/timer.rs
- src/tunnels.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1010)
> feat/core: remove heartbeat, as that is in Crust now

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1011)
> Version change to 0.18.4

- src/core.rs
Don't initialise `tick_timer_token` to `0` as that is the first valid
timer token and may trigger `Tick` events in clients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1012)
> fix/core: don't send tick events in clients

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1014)
> Version change to 0.18.5

- Cargo.toml
- build.rs
This updates the build process to generate the docs if `--features generate-diagrams` is passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1016)
> fix/docs: generate the sequence diagrams

- Cargo.toml
- examples/ci_test.rs
- examples/key_value_store.rs
- examples/utils/example_node.rs
- src/client.rs
- src/core.rs
- src/core_tests.rs
- src/lib.rs
- src/messages.rs
- src/mock_crust/crust.rs
- src/mock_crust/tests.rs
- src/node.rs
- tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1017)
> feat/core: use a Crust priority based on message type

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1018)
> Version change to 0.19.0

- src/core.rs
- src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1019)
> style/all: fix Clippy warnings

- src/core.rs
Otherwise the quorum size might be inaccurate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1021)
> fix/core: small networks only accept new nodes via the first node

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1022)
> Version change to 0.19.1

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1024)
> fix/core: only send NetworkStartupFailed as first node

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1028)
> refactor/core: deduplicate and extract some logic from Core::send

- examples/ci_test.rs
- examples/key_value_store.rs
- src/authority.rs
- src/core.rs
- src/data.rs
- src/id.rs
- src/immutable_data.rs
- src/node.rs
- src/plain_data.rs
- src/structured_data.rs
- src/types.rs
- src/utils.rs
- src/xor_name.rs
- tests/ci.rs
This reduces the size of several messages and the danger of any hash
collisions is still negligible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1029)
> feat/core: reduce XorName size from 512 to 256 bits

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1030)
> Version change to 0.21.0

- src/xor_name.rs
- tests/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1031)
> style/test: enable lint; in 1.9, Instant has AddAssign

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1032)
> refactor/core: better separate message handling and sending

- src/core.rs
- src/peer_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1036)
> fix/core: in send, prefer direct connections over tunnels

- Cargo.toml
- examples/utils/example_node.rs
- src/client.rs
- src/messages.rs
- src/node.rs
- src/stats.rs
This adds new message variants and API functions to allow Clients to request information about their
accounts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1037)
> feat/account_info: add handling for retrieving Client account information

- src/core.rs
- src/messages.rs
Since the accumulator values could be either hashes or full messages, in
some cases they were counted twice: If a group resends a message,
another node will send the full content, so two nodes will send
something different than before, and they will be counted twice.
This separates the accumulator from the hash map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1040)
> fix/core: fix message accumulation for hash messages

- Cargo.toml
- src/core.rs
- src/mock_crust/crust.rs
- src/mock_crust/support.rs
- src/mock_crust/tests.rs
- src/peer_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1043)
> Implemented bootstrap blacklist

- src/core.rs
- src/mock_crust/crust.rs
- src/mock_crust/support.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1047)
> chore/crust: Replace io::Error with CrustError

- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1045)
> fix/core: only relocate when listening

- src/core_tests.rs
- src/mock_crust/support.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1046)
> feat/mock_crust: unidirectional blocking

- .travis.yml
- Cargo.toml
- appveyor.yml
- examples/ci_test.rs
- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/action.rs
- src/client.rs
- src/core.rs
- src/core_tests.rs
- src/error.rs
- src/event.rs
- src/lib.rs
- src/messages.rs
- src/mock_crust/crust.rs
- src/mock_crust/support.rs
- src/mock_crust/tests.rs
- src/node.rs
- src/peer_manager.rs
- src/stats.rs
- src/tunnels.rs
- tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1050)
> feat/core: mio-based crust, message splitting, group deduplication

- CHANGELOG.md
- Cargo.toml
- src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1051)
> Version change to 0.22.0

- src/core.rs
- src/core_tests.rs
- src/lib.rs
- src/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1052)
> exposing additional functions for vault mock_crust tests

- src/client.rs
- src/core.rs
- src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1055)
> refactor/core_tests: Use real Node and Client in tests

- src/core.rs
- src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1056)
> test/core: add an isolated message accumulation test

- src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1058)
> test/churn: Add tests for requests during churn

- Cargo.toml
- src/client.rs
- src/core.rs
- src/core_tests.rs
- src/data.rs
- src/immutable_data.rs
- src/lib.rs
- src/mock_crust/crust.rs
- src/mock_crust/support.rs
- src/mock_crust/tests.rs
- src/node.rs
- src/plain_data.rs
- src/structured_data.rs
- tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1060)
> Use `SeededRng` and sodiumoxide_extras to make random data in tests reproducible.

- src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1061)
> test/core_test: enable multiple_joining_nodes test

- src/cache.rs
- src/client.rs
- src/core.rs
- src/core_tests.rs
- src/lib.rs
- src/messages.rs
- src/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1059)
> Response caching

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1064)
> Version change to 0.23.0

- src/core.rs
- src/stats.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1069)
> fix/core: disconnect bootstrap node on rebootstrap

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1068)
> Version change to 0.23.1

- examples/utils/example_client.rs
- examples/utils/example_node.rs
Also removes some unneeded cloning and hashing in the examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1072)
> fix/examples: handle Terminate event

- examples/ci_test.rs
- examples/key_value_store.rs
- examples/utils/example_client.rs
- examples/utils/example_node.rs
- rustfmt.toml
- src/client.rs
- src/core.rs
- src/core_tests.rs
- src/lib.rs
- src/messages.rs
- src/mock_crust/support.rs
- src/mock_crust/tests.rs
- src/node.rs
- src/peer_manager.rs
- src/stats.rs
- src/timer.rs
- src/types.rs
- src/xor_name.rs
- tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1073)
> fix/core: handle unacked message when resending

- src/message_filter.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1078)
> fix/test: increase timeouts to make message filter test more stable

- src/core.rs
- src/peer_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1079)
> chore/peer_manager: move routing_table from core into peer_manager

- examples/utils/example_node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1082)
> simplify example_node to follow the new data flow pattern in vault

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1083)
> Version change to 0.24.0

- src/core.rs
- src/peer_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1085)
> chore/peer_manager: simplify calling to peer_manager

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1088)
> Version change to 0.24.1

- src/core.rs
- src/peer_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1084)
> Peer manager refactor

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1089)
> Version change to 0.24.2

- CHANGELOG.md
- Cargo.toml
- src/peer_manager.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1091)
> Version change to 0.24.3

- src/state_machine.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1092)
> fix/state_machine: do not drop current state on terminate

- src/core_tests.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1094)
> test/node: Add test for restarting nodes

- src/core_tests.rs
- src/event.rs
- src/messages.rs
- src/states/client.rs
This will notify the upper layers if a part of a request message could
not be delivered via any route.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1096)
> feat/client: add RequestFailure event

- src/core_tests.rs
- src/event.rs
- src/states/client.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1098)
> feat/client: rename RequestFailure to RequestTimeout and log it

- src/peer_manager.rs
- src/states/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1099)
> fix/peer_manager: don't put peers in the map if they failed to be added to the routing table

- src/states/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1101)
> fix/node: always log as , even if first node

- src/core_tests.rs
- src/event.rs
- src/messages.rs
- src/states/client.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1107)
> feat/client: remove RequestTimeout event, this is done in safe_core now

- src/states/bootstrapping.rs
- src/states/client.rs
- src/states/joining_node.rs
- src/states/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1108)
> fix/states: do not terminate when sending action result fails

- CHANGELOG.md
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1109)
> Version change to 0.25.0

- CHANGELOG.md
- Cargo.toml
- examples/ci_test.rs
- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/client.rs
- src/core.rs
- src/core_tests.rs
- src/data.rs
- src/immutable_data.rs
- src/lib.rs
- src/message_filter.rs
- src/mock_crust/crust.rs
- src/mock_crust/support.rs
- src/node.rs
- src/plain_data.rs
- src/structured_data.rs
- tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1111)
> Version change to 0.23.3

- src/client_errors.rs
- src/lib.rs
- src/messaging/error.rs
- src/messaging/mod.rs
- src/messaging/mpid_header.rs
- src/messaging/mpid_message.rs
- src/messaging/mpid_message_wrapper.rs
- src/state_machine.rs
- src/states/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1112)
> feat/common: merge safe_network_common into routing

- src/ack_manager.rs
- src/client.rs
- src/node.rs
- src/peer_manager.rs
- src/state_machine.rs
- src/states/client.rs
- src/states/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1113)
> refactor/mock-crust: better separate mock crust from production code

- src/messages.rs
- src/states/client.rs
- src/states/common/bootstrapped.rs
- src/states/node.rs
- src/stats.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1116)
> refactor/bootstrapped: simplify user message handling

- src/client.rs
- tests/ci.rs
Minor change. Fixes #1070.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1118)
> Remove unnecessary mut self in client get requests

- examples/utils/example_node.rs
- src/peer_manager.rs
- src/states/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1121)
> refactor/node: remove redundant is_proper checks

- examples/ci_test.rs
- examples/utils/example_client.rs
- examples/utils/example_node.rs
- src/core_tests.rs
- src/peer_manager.rs
- src/state_machine.rs
- src/states/node.rs
- src/timer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1122)
> fix/peer_manager: fix removal of expired peers and tokens

- src/peer_manager.rs
- src/states/node.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1123)
> refactor/node-state: simplify use of peer manager in node state

- examples/utils/example_client.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1124)
> feat/ci_test: add ExampleClient get/put timeout

- examples/ci_test.rs
- examples/key_value_store.rs
- examples/utils/example_node.rs
- src/action.rs
- src/core.rs
- src/core_tests.rs
- src/id.rs
- src/lib.rs
- src/message_filter.rs
- src/mock_crust/support.rs
- src/structured_data.rs
- src/tunnels.rs
- tests/ci.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1134)
> feat/tests: randomise message handling order in mock crust

- src/priv_appendable_data.rs
- src/pub_appendable_data.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1137)
> chore/appendable_data: remove delete function

- src/append_types.rs
- src/priv_appendable_data.rs
- src/pub_appendable_data.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1138)
> appendable_data append tests; apply_wrapper function for priv_appendable_data

- src/priv_appendable_data.rs
- src/pub_appendable_data.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1139)
> test/appendable_data: apply_wrapper and update with incorrect info

- Cargo.toml
- src/core.rs
- src/core_tests.rs
- src/mock_crust/crust.rs
- src/mock_crust/support.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1140)
> feat/core: check whitelist when accepting connections

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/routing/1142)
> Version change to 0.26.0

- rustfmt.toml
- src/structured_data.rs
- src/timer.rs
https://github.com/rust-lang-nursery/rustfmt/issues/1184
> fix/rustfmt: workaround bug

- src/routing_table/mod.rs
- src/routing_table/prefix.rs
- src/routing_table/xorable.rs
- src/xor_name.rs
Partly Andreas's work. Last commit may be pointless?
> Make split order deterministic

- .gitignore
- .travis.yml
- examples/utils/example_node.rs
- src/append_types.rs
- src/client.rs
- src/client_errors.rs
- src/data.rs
- src/error.rs
- src/immutable_data.rs
- src/lib.rs
- src/message_filter.rs
- src/messages.rs
- src/messaging/mpid_header.rs
- src/node.rs
- src/priv_appendable_data.rs
- src/pub_appendable_data.rs
- src/routing_table/xorable.rs
- src/stats.rs
- src/structured_data.rs
And other minor changes from stable.
> feat/data: port appendable data from stable

- src/messages.rs
- src/peer_manager.rs
- src/routing_table/mod.rs
- src/routing_table/network_tests.rs
- src/states/node.rs
This fixes a couple of bugs and also implements slightly different approaches to various functions/
types relating to mainly to merging groups.
> fix/merge: fix several issues relating to merging groups

- src/routing_table/network_tests.rs
- src/routing_table/prefix.rs
...so that it behaves deterministically and passes.
> MAID-1660 fix network_tests::merging_groups

- src/states/node.rs
It is confusing and error-prone to handle routing messages inside the
calls to the `send` methods themselves. This adds a message queue and
defers handling, so that messages are processed sequentially, one at a time.
> MAID-1669 Defer routing message handling.

- examples/ci_test.rs
- src/ack_manager.rs
- src/states/common/bootstrapped.rs
- src/states/node.rs
This resolves an issue in the AckManager whereby a received Ack was not cached.  Also includes some
minor updates to the ci_test example.
> MAID-1661: fix/ack_manager: fix bug in AckManager

- src/mock_crust/support.rs
Packet handling is FIFO. The drop happens when the disconnect
message is received, so prior messages on the channel survive. This
may or may not be what's intended.
> MAID-1683 fix/mock_crust: drop packets sent over a route when it is disconnected

- README.md
- src/mock_crust/crust.rs
- src/states/node.rs
As discussed. This target is implemented as much as an example as anything else.
> refactor/logging: give stats messages a custom target; update README

- src/ack_manager.rs
- src/authority.rs
- src/messages.rs
- src/routing_table/network_tests.rs
- src/state_machine.rs
- src/states/common/bootstrapped.rs
- src/states/node.rs
- src/stats.rs
These are changes I've made while working on 1694, but not directly related to fixing it.
> MAID 1694: net invariant output, refactor, doc

- Cargo.toml
- src/client.rs
- src/data/mod.rs
- src/data/mutable_data.rs
- src/lib.rs
- src/stats.rs
This PR implements mocks for client functions
> Client interface in routing for the various RPCs

- src/client_error.rs
- src/data/mutable_data.rs
- src/messages/response.rs
- AccountInfo fields renamed
- New ClientError variants
- derive(Debug) added to bunch of places
- typos fixed
> Various minor changes

- src/routing_table/mod.rs
- src/states/common/bootstrapped.rs
- src/states/node.rs
- tests/mock_crust/cache.rs
- tests/mock_crust/merge.rs
- tests/mock_crust/mod.rs
- tests/mock_crust/utils.rs
- tests/mock_crust_tests.rs
Also added a basic regression test for merging three groups into one.
> MAID-1827 MAID-1831: fixed handling of 'OwnGroupMerge' messages

- src/states/node.rs
No, not an assigned issue, but something I decided to try this evening. Glob use patterns only affect the local method and don't trigger any Clippy lints.
> style/states/node: clean up complex message matching patterns

- src/peer_manager.rs
- src/routing_table/mod.rs
- src/routing_table/network_tests.rs
- src/states/node.rs
- tests/mock_crust/merge.rs
These don't directly relate to the JIRA issue, but were done while reading code related to this issue.
Best to read these commits separately.
> MAID-1877: refactorings and tie up a loose end

- src/routing_table/mod.rs
Never return our own name from `RoutingTable::targets`.
Don't split if other groups are close to merging with us.
> fix/routing_table: minor fixes and cleanups

- .gitignore
- examples/utils/example_node.rs
- src/action.rs
- src/client.rs
- src/event_stream.rs
- src/evented.rs
- src/lib.rs
- src/node.rs
- src/state_machine.rs
- src/states/bootstrapping.rs
- src/states/client.rs
- src/states/common/base.rs
- src/states/common/bootstrapped.rs
- src/states/mod.rs
- src/states/node.rs
- tests/ci.rs
- tests/mock_crust/accumulate.rs
- tests/mock_crust/cache.rs
- tests/mock_crust/churn.rs
- tests/mock_crust/drop.rs
- tests/mock_crust/merge.rs
- tests/mock_crust/mod.rs
- tests/mock_crust/requests.rs
- tests/mock_crust/utils.rs
- tests/mock_crust_tests.rs
Issues to resolve:
* ~2 failing tests: `node_restart` and `failing_connections_group_of_three`.~
* ~Probably some formatting + linting.~
> MAID-1864: Merge the routing and vault event handling threads.

- src/event_stream.rs
This avoids a potential stack overflow discussed in https://github.com/maidsafe/routing/pull/1305. Better safe than sorry!
> fix/event: use an explicit loop in `next_ev`

- src/peer_manager.rs
- src/states/node.rs
- src/stats.rs
Also adds further log info relating to joining and resource proof process.
> refactor/node: always terminate on failure to get NodeApproval

- src/lib.rs
- src/peer_manager.rs
- src/states/node.rs
Also fixed crate-level example code.
> refactor/logs: downgrade and deduplicate some warning messages

- src/routing_table/mod.rs
Send `OtherSectionMerge` messages to the neighbouring `PrefixSection`s
of the merge prefix, too, regardless of whether those exist as sections
in the routing table. That way the messages accumulate even if a
neighbouring section is currently merging or splitting.
> fix/routing_table: send merge messages to PrefixSections

- src/routing_table/mod.rs
This refactoring now allows the test to work with any reasonable value for 'SPLIT_BUFFER'.
> MAID-1976: chore/test: refactored RT test

- Cargo.toml
- src/mock_crust/crust.rs
- src/mock_crust/support.rs
- src/peer_manager.rs
- src/rate_limiter.rs
- src/states/client.rs
- src/states/node.rs
- tests/mock_crust/mod.rs
Also remove whitelist peer checks.
Update crust to `~0.27.0`
> RateLimiter updates to thresholds and logs

- src/node.rs
- src/peer_manager.rs
- src/state_machine.rs
- src/states/node.rs
- tests/mock_crust/churn.rs
- tests/mock_crust/mod.rs
feat/peer_manager: update RoutingConnection-(Proxy/JoiningNode) to RoutingConnection::Direct after 900s time_out
fix/aggressive_churn: check demotable peers before block connection
> Check before block connection

- src/data/mutable_data.rs
Part of MAID-2224 task - it depends on this
> feat/permission-set: Add Rand impl for PermissionSet

- examples/ci_test.rs
- examples/key_value_store.rs
- src/block.rs
- src/network_event.rs
- src/proof.rs
- src/vote.rs
- tests/ci.rs
Update tests for datachain types
> Update tests 

- src/data_chain/block.rs
Tests for the stuff in https://github.com/maidsafe/routing/pull/1538
> MAID-2455: Add test for Block::votes_iter

- src/data_chain/block.rs
- src/data_chain/mod.rs
- src/data_chain/vote_accumulator.rs
Also added quorum function and test to data_chain module.
> MAID-2468: add unit tests for VoteAccumulator

- src/data_chain/chain.rs
- src/data_chain/mod.rs
- src/data_chain/node_state.rs
- src/data_chain/proof.rs
- src/data_chain/vote.rs
- src/data_chain/vote_accumulator.rs
- src/lib.rs
Also added some Debug impls and moved test helpers to avoid code duplication.
> MAID-2469: add unit tests for chain

- .travis.yml
- appveyor.yml
- examples/ci_test.rs
- examples/key_value_store.rs
- src/data/mutable_data.rs
- src/lib.rs
- src/messages/mod.rs
- src/mock_crust/support.rs
- src/mock_crust/tests.rs
- src/mock_crypto.rs
- src/peer_manager.rs
- src/resource_prover.rs
- src/routing_table/mod.rs
- src/routing_table/prefix.rs
- src/signature_accumulator.rs
- src/state_machine.rs
- src/states/node.rs
- src/tunnels.rs
- src/utils.rs
- tests/ci.rs
- tests/mock_crust/churn.rs
- tests/mock_crust/tunnel.rs
- tests/mock_crust/utils.rs
- tests/mock_crust_tests.rs
nightly to 2018-07-07
clippy to 0.0.212
rustfmt to 0.99.2
> [MAID-3107] chore/ci: update scripts to Rust stable 1.28.0

- examples/ci_test.rs
- src/cumulative_own_section_merge.rs
- src/lib.rs
- src/mock_crust/support.rs
- src/peer_manager.rs
- src/states/client.rs
- src/states/joining_node.rs
- src/states/node.rs
- src/utils.rs
- src/xor_name.rs
> chore/fmt: format using cargo fmt

- src/lib.rs
- src/peer_manager.rs
- src/states/client.rs
- src/states/joining_node.rs
- src/utils.rs
- src/xor_name.rs
FOR FLEMING BRANCH - Should resolve potential travis CI failures flagged by `cargo clippy` and `cargo fmt`
> chore/ci: add suggested cargo clippy and cargo fmt fixes

- routing_model/index.html
This is an initial attempt at decoupling the relocating flow to integrate better with merging.
Also update the documentation.
Full PR:
https://raw.githack.com/maidsafe/routing/4a51d86d04c9d68529359f532a5696f961906516/routing_model/index.html
> Decouple Relocate processing and integrate with merge

- routing_model/src/actions.rs
- routing_model/src/flows_dst.rs
- routing_model/src/lib.rs
- routing_model/src/scenario_tests.rs
- routing_model/src/state.rs
- routing_model/src/utilities.rs
Implementing tests for the CheckOnlineOffline flow in
https://raw.githack.com/maidsafe/routing/bd2d7d32cb1fcffc57e652df3fa5ff0f92f430fe/routing_model/index.html
> Fleming flow tests: add CheckOnlineOffline

- routing_model/src/actions.rs
- routing_model/src/flows_dst.rs
- routing_model/src/flows_node.rs
- routing_model/src/flows_src.rs
- routing_model/src/lib.rs
- routing_model/src/scenario_tests.rs
- routing_model/src/state.rs
- routing_model/src/utilities.rs
Collection of tidy ups and clippy fixes
> Fleming design model: code tidy and clippy warning fixes

- routing_model/index.html
Clean ups and rename that became necessary over time.
Rendered:
https://raw.githack.com/maidsafe/routing/01e821131a9562663c615bcc52c3e37578471e40/routing_model/index.html
> Fleming design model clean ups

- routing_model/src/actions.rs
- routing_model/src/flows_dst.rs
- routing_model/src/flows_src.rs
- routing_model/src/scenario_tests.rs
- routing_model/src/state.rs
- routing_model/src/utilities.rs
Clean up NodeState to be closer to recent diagrams.
Do change relocating: There is still only one kind in this implementation.
> Use set_node_state like in more recent diagrams

- routing_model/src/flows_dst.rs
- routing_model/src/scenario_tests.rs
- routing_model/src/state.rs
Extract out ProcessElderChange
> Fleming design model: extract ProcessElderChange in flow tests

- src/chain/chain.rs
Addresses a TODO in the code to remove elements from a sorted list of sections more efficiently.
> chore: optimize our section info cleanup

- src/mock/quick_p2p/network.rs
- src/mock/quick_p2p/tests.rs
This PR contains the change to make mock quic_p2p poping message randomly.
> test/quic_p2p: pop random message

- src/peer_manager.rs
- src/peer_map.rs
- src/states/adult.rs
- src/states/bootstrapping_peer.rs
- src/states/client.rs
- src/states/common/approved.rs
- src/states/common/base.rs
- src/states/common/proxied.rs
- src/states/common/relocated.rs
- src/states/common/relocated_not_established.rs
- src/states/elder/mod.rs
- src/states/elder/tests.rs
- src/states/proving_node.rs
- src/states/relocating_node.rs
This is a followup to https://github.com/maidsafe/routing/pull/1692.
Closes #1683
> Simplify connection handling

- src/chain/chain.rs
- src/messages/mod.rs
- src/routing_table/mod.rs
- src/signature_accumulator.rs
- src/states/elder/mod.rs
- tests/mock_network/accumulate.rs
> use same quorum for different authorities

- src/chain/chain.rs
- src/chain/shared_state.rs
- src/mock/parsec/observation.rs
- src/mock/parsec/state.rs
- src/mock/parsec/tests.rs
- src/states/common/approved.rs
- src/states/elder/mod.rs
Closes #1717 
- Fix mock parsec to have genesis block first.
- Ensure their_keys is shared state.
> share state with their keys

- src/chain/chain.rs
- src/peer_map.rs
- src/states/elder/mod.rs
> ensure forward progress of messages with RMD

- src/chain/chain.rs
- src/chain/shared_state.rs
- src/states/adult.rs
- src/states/common/approved.rs
- src/states/elder/mod.rs
> feat/node: move their_knowledge into shared_state

- src/chain/chain.rs
- src/chain/mod.rs
- src/chain/network_event.rs
- src/chain/proof.rs
- src/states/adult.rs
- src/states/common/approved.rs
- src/states/elder/mod.rs
Closes #1745 
Test:
clippy + soak tests
> fix/routing: remove unused ProvingSection 

- examples/ci_test.rs
- src/lib.rs
- src/states/common/relocated.rs
- tests/mock_network_tests.rs
bare_trait_objects require a bit more work to fix so silence it for now.
> fix/routing: fix build and temprorarily silence new bare_trait_objects

- src/client.rs
- src/lib.rs
- src/messaging/error.rs
- src/node.rs
- src/resource_prover.rs
- src/routing_table/mod.rs
- src/state_machine.rs
- src/states/adult.rs
- src/states/bootstrapping_peer.rs
- src/states/client.rs
- src/states/common/approved.rs
- src/states/common/base.rs
- src/states/common/relocated.rs
- src/states/common/relocated_not_established.rs
- src/states/elder/mod.rs
- src/states/elder/tests.rs
- src/states/proving_node.rs
- src/states/relocating_node.rs
- tests/mock_network/utils.rs
- tests/mock_network_tests.rs
> Fix bare_trait_objects build errors

- Cargo.toml
> chore/routing: update parsec to resolve the issue 1734

- src/chain/mod.rs
- src/chain/section_info.rs
- src/lib.rs
- src/states/elder/mod.rs
- tests/mock_network/mod.rs
- tests/mock_network/secure_message_delivery.rs
> test/routing: verify message with invalid signature will be blocked

- README.md
> Add a Lines of Code badge

- src/parsec.rs
> Fix too many open files in tests

- src/chain/chain.rs
- src/chain/network_event.rs
- src/parsec.rs
- src/states/common/approved.rs
- src/states/elder/mod.rs
- tests/mock_network/mod.rs
Resolves #1782 
- Add new `ParsecPrune` event
- Vote for pruning at the right time
- Unit and integration test
> Vote to prune PARSEC gossip graph

- src/chain/bls_emu.rs
- src/chain/chain.rs
- src/chain/chain_accumulator.rs
- src/chain/elders_info.rs
- src/chain/member_info.rs
- src/chain/mod.rs
- src/chain/network_event.rs
- src/chain/shared_state.rs
- src/chain/test_utils.rs
- src/lib.rs
- src/messages/mod.rs
- src/parsec.rs
- src/signature_accumulator.rs
- src/state_machine.rs
- src/states/adult.rs
- src/states/common/approved.rs
- src/states/elder/mod.rs
- src/states/elder/tests.rs
- tests/mock_network/secure_message_delivery.rs
It will be used for node ageing. Closes #1807 .
> Add section member infos to shared state

- src/chain/test_utils.rs
- src/node.rs
- tests/mock_network/utils.rs
Rewrite verify_single_chain in terms of public API functions on Node.
> Rewrite verify_single_chain in terms on Node API functions

- src/parsec.rs
> Remove old parsecs

- tests/mock_network/utils.rs
Previously it would control whether to stop polling even though some nodes are still busy. Now it control whether to continue polling even though all nodes are idle.
This change fixes a rare test failure which happens when a joining node is waiting for the `SectionInfo` with itself to transition to the `Elder` state. Because of quirks of the testing framework, the polling might end prematurely and the new node never receives any gossip which would make it accumulate the section info.Then the fake clock gets advanced and the new node timeouts. It then tries to rebootstrap with different id which no longer matches the prefix the test was expecting, thus it fails.
Closes #1837
> Modify the test framework to fix a test failure

- src/chain/chain.rs
- src/chain/network_event.rs
- src/event.rs
- src/node.rs
- src/state_machine.rs
- src/states/common/approved.rs
- src/states/elder/mod.rs
This is required to achieve consensus on events in Vaults.
Closes https://github.com/maidsafe/safe_vault/issues/868
> Add public API to vote for custom events

- src/chain/chain.rs
- src/chain/member_info.rs
- src/chain/mod.rs
- src/chain/shared_state.rs
- src/parsec.rs
- src/states/elder/mod.rs
- src/states/elder/tests.rs
> Introduce Infants and age counter

- scripts/fixup_check
Test:
Verify the script do not ouput anything on the fleming branch.
> fix/scripts: ignore title error script check pushed by mistake

- src/chain/chain.rs
- src/states/adult.rs
- src/states/elder/mod.rs
- tests/mock_network/mod.rs
Fix additional seeds with mock_base and mock.
Refactor/simplify code in is_validation to support debugging.
> Fix additional failures with multi join

- src/chain/bls_emu.rs
- src/chain/chain.rs
- src/chain/elders_info.rs
- src/chain/shared_state.rs
- src/error.rs
- src/id.rs
- src/states/bootstrapping_peer.rs
- src/states/common/base.rs
- src/states/elder/mod.rs
Fixes for the review comments in https://github.com/maidsafe/routing/pull/1868
That PR was merged before review comments were addressed as they were minor and blocking fixes to tests.
> Review comment fixes for #1868

- src/chain/chain.rs
- src/node.rs
- src/peer_map.rs
- src/state_machine.rs
- src/states/adult.rs
- src/states/bootstrapping_peer.rs
- src/states/common/approved.rs
- src/states/common/base.rs
- src/states/elder/mod.rs
- src/states/elder/tests.rs
- src/states/joining_peer.rs
- tests/mock_network/drop.rs
- tests/mock_network/utils.rs
Strip down peer_map to the minimum we need it to do.
> Strip down PeerMap

- src/chain/chain.rs
- src/chain/mod.rs
- src/chain/shared_state.rs
- src/lib.rs
- src/messages/mod.rs
- src/signature_accumulator.rs
- src/states/elder/mod.rs
- tests/mock_network/secure_message_delivery.rs
Closes #1911 
Fix review issues in #1906 
Also improve handling of malicious inputs not allowing them to break signature combination.
> fix review issues in initial BLS implementation 

- src/chain/chain.rs
- src/node.rs
- src/state_machine.rs
- src/states/adult.rs
- src/states/elder/mod.rs
> API for vaults

- src/messages/mod.rs
- src/mock/parsec/mod.rs
- src/mock/parsec/state.rs
- src/node.rs
- src/parsec.rs
- src/state_machine.rs
- src/states/adult.rs
- src/states/elder/mod.rs
- tests/mock_network/utils.rs
Error when reaching MAX_POLL are common and the error message and logs do not give enough information. Improve log to give the basic starting point needed to investigate failure.
> Improve log for common failures

- src/chain/chain.rs
- src/state_machine.rs
- src/states/adult.rs
- src/states/common/approved.rs
- src/states/elder/mod.rs
- src/states/elder/tests.rs
- Clarify churn_in_progress
- fix RoutingError that stop Demoting from happening
- fix misleading ElderInfo in handle_section_info_event
> additional clean up to support ageing

- src/mock/parsec/mod.rs
- src/mock/parsec/tests.rs
- src/states/elder/tests.rs
- tests/mock_network/utils.rs
Pull/rebase patches from https://github.com/maidsafe/routing/pull/1882 and add commit to fix the DKG participants part so test continue to pass.
> Fix mock gossip

- src/pause.rs
- src/state_machine.rs
- src/states/adult.rs
- src/states/elder/mod.rs
- src/states/elder/tests.rs
- tests/mock_network/mod.rs
Also improve the pause/resume tests. There are now two: one for simple, no-split case and one for when the split happens in between the pause and resume.
> Support pause/resume also for adults

- src/chain/chain.rs
- src/chain/mod.rs
- src/chain/shared_state.rs
- src/states/adult.rs
- src/states/common/approved.rs
- src/states/elder/mod.rs
Clean up chain polling
Clean up poll relocation to be as part of chain polling
> clean up poll & poll relocation

- src/states/elder/mod.rs
In some situation we might not be connected to any of our elders yet and if we then lose some other connection, then check would incorrectly trigger node termination.
> Perform the elders connection check only when we lose elder

- src/states/adult.rs
- src/states/elder/mod.rs
- tests/mock_network/utils.rs
> Clean up review comments from #1929

- .github/workflows/cicd.yml
Copy the same github action as safe_vault to run all our clippy/test target use caching and ease maintenance.
> Use safe_vault GitHub action

- tests/mock_network/churn.rs
A recipient might be demoted before receiving the message and currently we raise the `MessageRecieved` event only as elders. This might change in the future.
> Don't fail if a user messages for non-elder is not delivered

- src/chain/chain.rs
- src/messages/direct.rs
- src/messages/mod.rs
- src/states/adult.rs
- src/states/bootstrapping_peer.rs
- src/states/common/base.rs
- src/states/elder/mod.rs
- src/states/joining_peer.rs
Partial solves #1945 by implementing integrity check. We still need to check trust which will be handled in a followup PR.
Also includes minor cleanup/refactoring.
> Trusted GenesisUpdate

- src/chain/chain.rs
- src/chain/member_info.rs
- src/event.rs
- src/lib.rs
- src/node.rs
- src/signature_accumulator.rs
- src/states/common/base.rs
- src/states/elder/mod.rs
- src/states/joining_peer.rs
- tests/mock_network/utils.rs
Phase I of a name tidy up and also start of reordering if statements to give us short circuit plus more readability. 
This PR is an example, I hope of some work we will tackle across libraries as we can now see the network in operation.
> Routing name tidy up

- tests/mock_network/mod.rs
> Re-enable multiple-joining-nodes test with real parsec

- src/action.rs
- src/chain/network_event.rs
- src/error.rs
- src/lib.rs
- src/node.rs
- src/state_machine.rs
- src/states/adult/mod.rs
- src/states/bootstrapping_peer.rs
- src/states/common/base.rs
- src/states/elder/mod.rs
- src/states/joining_peer.rs
- tests/mock_network/utils.rs
Merge `InterfaceError` and `RoutingError` into one type.
> Simplify errors

- src/action.rs
- src/chain/chain.rs
- src/chain/shared_state.rs
- src/event.rs
- src/location.rs
- src/messages/direct.rs
- src/messages/mod.rs
- src/node.rs
- src/state_machine.rs
- src/states/adult/mod.rs
- src/states/bootstrapping_peer.rs
- src/states/common/base.rs
- src/states/elder/mod.rs
- src/states/joining_peer.rs
- tests/mock_network/accumulate.rs
- tests/mock_network/churn.rs
- tests/mock_network/utils.rs
Location did not need to be generic.
> reouting/refactor Location does not need to be generic

- Cargo.toml
Closes #1845
Introduced in https://github.com/maidsafe/routing/commit/be55a1f1472286c8f4ab3b8e199ba7e4aa7d09d1
> Remove unused dependency "term"

- Cargo.toml
- src/chain/chain.rs
- src/chain/shared_state.rs
- src/id.rs
- src/lib.rs
- src/messages/mod.rs
- src/messages/src_authority.rs
- src/messages/variant.rs
- src/network_service/mod.rs
- src/network_service/sending_targets_cache.rs
- src/node.rs
- src/parsec.rs
- src/signature_accumulator.rs
- src/state_machine.rs
- src/states/adult/mod.rs
- src/states/bootstrapping_peer.rs
- src/states/common/approved.rs
- src/states/common/base.rs
- src/states/elder/mod.rs
- src/states/elder/tests.rs
- src/states/joining_peer.rs
- src/states/test_utils.rs
- tests/mock_network/secure_message_delivery.rs
- tests/mock_network/utils.rs
> Replace ConnectionInfo with just SocketAddr

- Cargo.toml
- src/lib.rs
- src/mock/parsec/mod.rs
- src/parsec.rs
- src/state_machine.rs
- src/states/adult/mod.rs
- src/states/bootstrapping_peer.rs
- src/states/common/approved.rs
- src/states/common/base.rs
- src/states/elder/mod.rs
- src/states/joining_peer.rs
- tests/mock_network/utils.rs
Supersedes #2054 
Closes #2049
> Improve gossip (Take 3 of the gossip timer removal)

- examples/minimal.rs
- src/event.rs
- src/node/mod.rs
- src/node/stage/approved.rs
- tests/mock_network/utils.rs
> Expose public_key_set and add EldersChanged event

- src/node/mod.rs
Closes https://github.com/maidsafe/routing/issues/2114
> add Node::our_elders_sorted_by_distance_to method

- src/timer.rs
> Fix hang in the timer tests + refactor

- src/consensus/network_event.rs
- src/node/stage/approved.rs
- src/section/member_info.rs
- src/section/section_members.rs
- src/section/shared_state.rs
- tests/mock_network/drop.rs
- tests/mock_network/messages.rs
- tests/mock_network/mod.rs
- tests/mock_network/node_ageing.rs
- tests/mock_network/secure_message_delivery.rs
- tests/mock_network/utils.rs
Closes #2088 
Closes #2123 
Closes #2124
> Remove unneeded parts

- src/lib.rs
- src/node/mod.rs
- src/section/section_proof_chain.rs
> feat/api: add SectionProofChain getter api for Node

- .github/workflows/mock_base.yml
- .github/workflows/pr.yml
- .github/workflows/security_audit.yml
Ran updated CI on my fork initially to ensure all working fine - see [here](https://github.com/S-Coyle/routing/pull/1)
> Add code coverage and general CI refactor

- src/consensus/proof.rs
- src/node/stage/approved.rs
- src/section/member_info.rs
- src/section/section_map.rs
- src/section/section_members.rs
- src/section/shared_state.rs
Close https://github.com/maidsafe/routing/issues/2119
> feat/shared_state: ensure mutations to SharedState are approved by the section

- src/consensus/dkg.rs
- src/consensus/event_accumulator.rs
- src/consensus/mod.rs
- src/consensus/network_event.rs
- src/consensus/parsec.rs
- src/consensus/vote.rs
- src/core.rs
- src/crypto.rs
- src/error.rs
- src/message_filter.rs
- src/messages/accumulating_message.rs
- src/messages/message_accumulator.rs
- src/messages/mod.rs
- src/messages/variant.rs
- src/mock/parsec/mod.rs
- src/node/mod.rs
- src/node/stage/approved.rs
- src/node/stage/bootstrapping.rs
- src/node/stage/joining.rs
- src/node/stage/mod.rs
- src/node/tests/elder.rs
- src/node/tests/utils.rs
- src/pause.rs
- src/relocation.rs
- src/section/mod.rs
- src/section/section_keys.rs
- src/section/section_proof_chain.rs
- src/section/shared_state.rs
Implements the framework for message based voting.
Closes #2121
Closes https://github.com/maidsafe/routing/pull/2153
> Message voting

- examples/minimal.rs
- src/event.rs
- src/node/mod.rs
- src/node/stage/approved.rs
- src/section/member_info.rs
- src/section/shared_state.rs
- tests/mock_network/utils.rs
> feat/event: send event when promoted to Adult

- src/messages/variant.rs
- src/node/mod.rs
- src/node/stage/approved.rs
- src/node/stage/bootstrapping.rs
- src/node/stage/joining.rs
Closes https://github.com/maidsafe/routing/issues/2122
> feat/approved: notify lagging elders

- README.md
Also removes some links to old CI
> docs(readme): update readme with correct docs link

- .github/workflows/rustdoc.yml
fleming branch has now been deleted - switch to master.
> docs(gh-pages): generate docs on push to master branch

- Cargo.toml
> chore(deps): use updated bls_signature_aggregator crate name

- src/node/tests/adult.rs
- src/node/tests/elder.rs
This PR contains some fixing commits trying to make the parsec removal work passing with the CI tests.
> fixing parsec removal refactoring

- src/consensus/dkg.rs
- src/consensus/proven.rs
- src/delivery_group.rs
- src/event.rs
- src/lib.rs
- src/messages/mod.rs
- src/messages/src_authority.rs
- src/node/stage/approved.rs
- src/node/stage/bootstrapping.rs
- src/node/stage/joining.rs
- src/node/stage/mod.rs
- src/peer.rs
- src/section/elders_info.rs
- src/section/member_info.rs
- src/section/mod.rs
- src/section/section_peers.rs
- src/section/shared_state.rs
This PR contains the work of:
1, rename SectionMembers to SectionPeers, MemberState to PeerState
2, rename quorum to majority
3, make Peer contains the age info
> Some structs refactor work

- src/node/mod.rs
- src/node/stage/mod.rs
> feat/node: add data signing and signature verification public apis

- examples/minimal.rs
non-first node shall have non-contacts to bootstrap with
spawned handlers shall be collected and joined
On top of PR 2211
> resolve failing example

- src/routing/bootstrap.rs
- src/routing/tests/mod.rs
- src/section/mod.rs
> bug(panic) Removed a panic situation for bootstrapping nodes. 

- src/delivery_group.rs
- src/lib.rs
- src/routing/tests/mod.rs
Removed ELDER_MAJORITY and made majority func constant and inline.
> feat(consts)

- src/routing/mod.rs
A temporary change to re-expose Elder's sk_share to move ahead with the test-net as `sn_transfers` heavily relies on having the sk_share for signing at a lot of places and refactoring this would slow us down.
> refactor(keys): re-expose Elder SecretKeyShare

- src/routing/approved.rs
To avoid over relocation, we only allow relocation when there is
enough elder nodes. AND, the newly joined node will not be relocated
immediately.
> fix: avoid over relocation

- .github/workflows/pr.yml
This enables the workflow to use secrets when PR is raised from a fork.
> chore(ci): switch to use pull_request_target event

- .github/workflows/pr.yml
- .github/workflows/semgrep.yml
Only actually required for semgrep.yml at the moment
> chore(ci): switch to pull_request_target event in semgrep.yml only

- examples/stress.rs
- src/messages/variant.rs
- src/routing/approved.rs
- src/routing/bootstrap.rs
First batch of assorted bugfixes: fixes some issues the bootstrap and the stress-test.
> Bugfixes, part 1

- src/consensus/vote.rs
- src/messages/mod.rs
- src/messages/plain_message.rs
- src/messages/src_authority.rs
- src/network/mod.rs
- src/routing/approved.rs
- src/routing/command.rs
- src/routing/mod.rs
- src/routing/stage.rs
- src/routing/tests/mod.rs
Closes https://github.com/maidsafe/sn_routing/issues/2315
> Dst aggregation for all variants

- Cargo.toml
- src/consensus/dkg.rs
- src/lib.rs
- src/routing/tests/mod.rs
- src/section/mod.rs
- src/section/section_keys.rs
- tests/drop.rs
> feat: use supermajority agreement + increase elder size to 7

- src/delivery_group.rs
- src/messages/mod.rs
- src/messages/variant.rs
- src/network/mod.rs
- src/network/prefix_map.rs
- src/relocation.rs
- src/routing/approved.rs
- src/routing/lazy_messaging.rs
- src/routing/mod.rs
- src/routing/split_barrier.rs
- src/routing/tests/mod.rs
- src/section/elders_info.rs
- tests/utils/mod.rs
Keep all sections, not just neighbours.
> Remove neighbours restriction

- src/agreement/dkg.rs
- src/delivery_group.rs
- src/lib.rs
- src/messages/mod.rs
- src/routing/bootstrap.rs
- src/routing/core.rs
- src/routing/lazy_messaging.rs
- src/routing/mod.rs
- src/routing/tests/mod.rs
- src/section/elders_info.rs
- src/section/member_info.rs
- src/section/mod.rs
- tests/bootstrap.rs
genesis node use age of 255
nodes of first section use age randomized between 6 and 100
later on node has to be age of 5
> feat: nodes using different ages

- src/delivery_group.rs
- As to avoid node level issues that were best solved with AE, the delivery target size stipulated in reliable messaging was previously overridden. Now that AE is to be implemented also at node level, we can restore this value.
> feat(messaging): restore target group size

- src/delivery_group.rs
- It did not take into account the changes of min delivery group size.
> fix(tests): refactor delivery group tests

- src/delivery_group.rs
- Also adds test cases for this, however these are currently missing proper precondition setup, thus ignored for now.
> fix(delivery_targets): deliver to all when targets are final dst

- examples/stress.rs
- src/cache/item.rs
- src/cache/mod.rs
- src/message_filter.rs
- src/routing/connectivity_complaints.rs
- Reintroduces the api used with lru_time_cache.
> chore(cache): implement capacity

- src/routing/bootstrap/join.rs
- src/routing/bootstrap/mod.rs
- src/routing/core/messaging/handling/mod.rs
This PR contains work of fixing couple of bootstrap issues:
1, avoid dropping JoinResponse::Redirect mistakenly
2, new node after section split has to join with the age of MIN_ADULT_AGE
> Fixing couple of bootstrap issues
